-- ALERTS.ALTSPEC — detail specification (CLOB) for alert/report definitions
-- Deploy on ICR app DB after 59_alerts_libquery.sql.
-- Idempotent: ADD column only if missing; DELETE+INSERT ALT0000010 only.
--
-- GET path (ALT0000001) uses PKQUERYMANAGER.GETQUERY_ALT0000001 (QUERYTYPE=1).
-- After this script, add a.ALTSPEC to that function's SELECT list in PKQUERYMANAGER
-- (same position as other CLOB columns such as ALTSQL / ALTFORMAT).

SET DEFINE OFF;

DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO v_cnt
    FROM user_tab_columns
   WHERE table_name = 'ALERTS'
     AND column_name = 'ALTSPEC';

  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE ALERTS ADD (ALTSPEC CLOB)';
    DBMS_OUTPUT.PUT_LINE('ALERTS.ALTSPEC added.');
  ELSE
    DBMS_OUTPUT.PUT_LINE('ALERTS.ALTSPEC already exists — skipped.');
  END IF;
END;
/

DELETE FROM LIBQUERY WHERE QUERYNUM = 'ALT0000010';

INSERT INTO LIBQUERY (
  QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL,
  QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE
)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'ALT0000010',
       'Merge Alert',
       'Merge alert (insert or update). Body includes ALTSPEC CLOB — detail specification.',
       TO_CLOB(q'~
MERGE INTO ALERTS t
USING (
    SELECT *
    FROM json_table((SELECT REQUESTBODY
                     FROM REQUEST_QUERY_BODY
                     WHERE REQUESTID = :param1),
            '$.values[*]' COLUMNS(
                ALTID PATH '$."ALTID"',
                ALTQUERY PATH '$."ALTQUERY"',
                ALTSUBJECT PATH '$."ALTSUBJECT"',
                ALTCONTENT PATH '$."ALTCONTENT"',
                ALTUTIL PATH '$."ALTUTIL"',
                ALTFILE PATH '$."ALTFILE"',
                ALTREALTIME NUMBER PATH '$."ALTREALTIME"',
                ALTSMSCONTENT PATH '$."ALTSMSCONTENT"',
                ALTORIENTATION PATH '$."ALTORIENTATION"',
                ALTPRINTAREA PATH '$."ALTPRINTAREA"',
                ALTMARGIN PATH '$."ALTMARGIN"',
                ALTFITPAGE NUMBER PATH '$."ALTFITPAGE"',
                ALTFITHEIGHT NUMBER PATH '$."ALTFITHEIGHT"',
                ALTFITWIDTH NUMBER PATH '$."ALTFITWIDTH"',
                ALTTITLEREPEAT PATH '$."ALTTITLEREPEAT"',
                ALTFOOTER PATH '$."ALTFOOTER"',
                ALTFORMAT PATH '$."ALTFORMAT"',
                ALTFORMATXLS PATH '$."ALTFORMATXLS"',
                ALTCONTENTHTML PATH '$."ALTCONTENTHTML"',
                ALTXLSBREAK PATH '$."ALTXLSBREAK"',
                ALTSCALE NUMBER PATH '$."ALTSCALE"',
                ALTCOLMOVE PATH '$."ALTCOLMOVE"',
                ALTNBPARAM NUMBER PATH '$."ALTNBPARAM"',
                ALTPARAMDESC PATH '$."ALTPARAMDESC"',
                ALTBORDER NUMBER PATH '$."ALTBORDER"',
                ALTTITLEXLS PATH '$."ALTTITLEXLS"',
                ALTTITLEXLSCOLOR PATH '$."ALTTITLEXLSCOLOR"',
                ALTFREEZEHEADER NUMBER PATH '$."ALTFREEZEHEADER"',
                ALTFREEZECOLUMN NUMBER PATH '$."ALTFREEZECOLUMN"',
                ALTFORMATTAB2XLS PATH '$."ALTFORMATTAB2XLS"',
                ALTNOHTML NUMBER PATH '$."ALTNOHTML"',
                ALTSQL CLOB PATH '$."ALTSQL"',
                ALTSPEC CLOB PATH '$."ALTSPEC"'
            ))
) s
ON (t.ALTID = s.ALTID)
WHEN MATCHED THEN
    UPDATE SET
        t.ALTQUERY = s.ALTQUERY, t.ALTSUBJECT = s.ALTSUBJECT, t.ALTCONTENT = s.ALTCONTENT,
        t.ALTDMAJ = SYSDATE, t.ALTUTIL = s.ALTUTIL, t.ALTFILE = s.ALTFILE,
        t.ALTREALTIME = s.ALTREALTIME, t.ALTSMSCONTENT = s.ALTSMSCONTENT,
        t.ALTORIENTATION = s.ALTORIENTATION, t.ALTPRINTAREA = s.ALTPRINTAREA,
        t.ALTMARGIN = s.ALTMARGIN, t.ALTFITPAGE = s.ALTFITPAGE,
        t.ALTFITHEIGHT = s.ALTFITHEIGHT, t.ALTFITWIDTH = s.ALTFITWIDTH,
        t.ALTTITLEREPEAT = s.ALTTITLEREPEAT, t.ALTFOOTER = s.ALTFOOTER,
        t.ALTFORMAT = s.ALTFORMAT, t.ALTFORMATXLS = s.ALTFORMATXLS,
        t.ALTCONTENTHTML = s.ALTCONTENTHTML, t.ALTXLSBREAK = s.ALTXLSBREAK,
        t.ALTSCALE = s.ALTSCALE, t.ALTCOLMOVE = s.ALTCOLMOVE,
        t.ALTNBPARAM = s.ALTNBPARAM, t.ALTPARAMDESC = s.ALTPARAMDESC,
        t.ALTBORDER = s.ALTBORDER, t.ALTTITLEXLS = s.ALTTITLEXLS,
        t.ALTTITLEXLSCOLOR = s.ALTTITLEXLSCOLOR, t.ALTFREEZEHEADER = s.ALTFREEZEHEADER,
        t.ALTFREEZECOLUMN = s.ALTFREEZECOLUMN, t.ALTFORMATTAB2XLS = s.ALTFORMATTAB2XLS,
        t.ALTNOHTML = s.ALTNOHTML, t.ALTSQL = s.ALTSQL, t.ALTSPEC = s.ALTSPEC
~') || q'~
WHEN NOT MATCHED THEN
    INSERT (ALTID, ALTQUERY, ALTSUBJECT, ALTCONTENT, ALTDCRE, ALTDMAJ, ALTUTIL,
            ALTFILE, ALTREALTIME, ALTSMSCONTENT, ALTORIENTATION, ALTPRINTAREA,
            ALTMARGIN, ALTFITPAGE, ALTFITHEIGHT, ALTFITWIDTH, ALTTITLEREPEAT,
            ALTFOOTER, ALTFORMAT, ALTFORMATXLS, ALTCONTENTHTML, ALTXLSBREAK,
            ALTSCALE, ALTCOLMOVE, ALTNBPARAM, ALTPARAMDESC, ALTBORDER,
            ALTTITLEXLS, ALTTITLEXLSCOLOR, ALTFREEZEHEADER, ALTFREEZECOLUMN,
            ALTFORMATTAB2XLS, ALTNOHTML, ALTSQL, ALTSPEC)
    VALUES (s.ALTID, s.ALTQUERY, s.ALTSUBJECT, s.ALTCONTENT, SYSDATE, SYSDATE, s.ALTUTIL,
            s.ALTFILE, s.ALTREALTIME, s.ALTSMSCONTENT, s.ALTORIENTATION, s.ALTPRINTAREA,
            s.ALTMARGIN, s.ALTFITPAGE, s.ALTFITHEIGHT, s.ALTFITWIDTH, s.ALTTITLEREPEAT,
            s.ALTFOOTER, s.ALTFORMAT, s.ALTFORMATXLS, s.ALTCONTENTHTML, s.ALTXLSBREAK,
            s.ALTSCALE, s.ALTCOLMOVE, s.ALTNBPARAM, s.ALTPARAMDESC, s.ALTBORDER,
            s.ALTTITLEXLS, s.ALTTITLEXLSCOLOR, s.ALTFREEZEHEADER, s.ALTFREEZECOLUMN,
            s.ALTFORMATTAB2XLS, s.ALTNOHTML, s.ALTSQL, s.ALTSPEC)
~',
       '{:USERID, :DATABASE_SID,:LISTE_PARAM,:LANGUAGE}',
       '',
       1,
       0,
       1
  FROM dual;

COMMIT;

SET DEFINE ON;

-- PKQUERYMANAGER manual step (ICR app DB):
-- In package body PKQUERYMANAGER, function GETQUERY_ALT0000001:
--   Add a.ALTSPEC to the SELECT column list (after ALTSQL or with other CLOB fields).
-- Recompile: ALTER PACKAGE PKQUERYMANAGER COMPILE BODY;
