-- Tools menu — Barcode generator (incremental; safe on existing DBs)
-- Angular route: /barcodegenerator  |  Screen SCR0000000082
-- Deploy labels: 104_tra_labels_barcode_generator.sql
-- Re-login after deploy to refresh SET0000040 menu.

SET DEFINE OFF;

-- ── Menu group + route ───────────────────────────────────────────────────────
MERGE INTO ICR_MENU_ENTRY t
USING (
  SELECT 'GRP_TOOLS' AS MENU_CODE, NULL AS PARENT_CODE, 'GROUP' AS MENU_TYPE,
         'STANDARD' AS MENU_MODE, NULL AS ROUTE_PATH, 'fas fa-toolbox' AS ICON_CLASS,
         'Tools' AS LABEL_TEXT, 268 AS SORT_ORDER, 'tools' AS EXPAND_KEY, 1 AS ACTIVE
    FROM dual
) s ON (t.MENU_CODE = s.MENU_CODE)
WHEN MATCHED THEN UPDATE SET
  t.PARENT_CODE = s.PARENT_CODE, t.MENU_TYPE = s.MENU_TYPE, t.MENU_MODE = s.MENU_MODE,
  t.ROUTE_PATH = s.ROUTE_PATH, t.ICON_CLASS = s.ICON_CLASS, t.LABEL_TEXT = s.LABEL_TEXT,
  t.SORT_ORDER = s.SORT_ORDER, t.EXPAND_KEY = s.EXPAND_KEY, t.ACTIVE = s.ACTIVE
WHEN NOT MATCHED THEN INSERT (
  MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE
) VALUES (
  s.MENU_CODE, s.PARENT_CODE, s.MENU_TYPE, s.MENU_MODE, s.ROUTE_PATH,
  s.ICON_CLASS, s.LABEL_TEXT, s.SORT_ORDER, s.EXPAND_KEY, s.ACTIVE
);

MERGE INTO ICR_MENU_ENTRY t
USING (
  SELECT 'ROUTE_BARCODE_GEN' AS MENU_CODE, 'GRP_TOOLS' AS PARENT_CODE, 'ROUTE' AS MENU_TYPE,
         'STANDARD' AS MENU_MODE, '/barcodegenerator' AS ROUTE_PATH, 'fas fa-barcode' AS ICON_CLASS,
         'Barcode generator' AS LABEL_TEXT, 269 AS SORT_ORDER, NULL AS EXPAND_KEY, 1 AS ACTIVE
    FROM dual
) s ON (t.MENU_CODE = s.MENU_CODE)
WHEN MATCHED THEN UPDATE SET
  t.PARENT_CODE = s.PARENT_CODE, t.MENU_TYPE = s.MENU_TYPE, t.MENU_MODE = s.MENU_MODE,
  t.ROUTE_PATH = s.ROUTE_PATH, t.ICON_CLASS = s.ICON_CLASS, t.LABEL_TEXT = s.LABEL_TEXT,
  t.SORT_ORDER = s.SORT_ORDER, t.ACTIVE = s.ACTIVE
WHEN NOT MATCHED THEN INSERT (
  MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE
) VALUES (
  s.MENU_CODE, s.PARENT_CODE, s.MENU_TYPE, s.MENU_MODE, s.ROUTE_PATH,
  s.ICON_CLASS, s.LABEL_TEXT, s.SORT_ORDER, s.EXPAND_KEY, s.ACTIVE
);

-- All authenticated users (utility screen)
INSERT INTO ICR_MENU_ACCESS_RULE (MENU_CODE, FLAG_NAME)
SELECT 'GRP_TOOLS', 'ALL' FROM dual
 WHERE NOT EXISTS (
       SELECT 1 FROM ICR_MENU_ACCESS_RULE r
        WHERE r.MENU_CODE = 'GRP_TOOLS' AND r.FLAG_NAME = 'ALL'
 );

INSERT INTO ICR_MENU_ACCESS_RULE (MENU_CODE, FLAG_NAME)
SELECT 'ROUTE_BARCODE_GEN', 'ALL' FROM dual
 WHERE NOT EXISTS (
       SELECT 1 FROM ICR_MENU_ACCESS_RULE r
        WHERE r.MENU_CODE = 'ROUTE_BARCODE_GEN' AND r.FLAG_NAME = 'ALL'
 );

COMMIT;

SET DEFINE ON;
