-- TRA_LABELS.TLADESC VARCHAR2(100) → CLOB (long banner / help copy)
-- Run once on ICR app DB before scripts that seed long label text (e.g. 107 S83.WARN).
-- Re-runnable: skips migration when TLADESC is already CLOB.
-- Also patches DIC0000014 bulk MERGE (removes 200-char cap).

SET DEFINE OFF;

DECLARE
  v_type VARCHAR2(30);
BEGIN
  SELECT data_type
    INTO v_type
    FROM user_tab_columns
   WHERE table_name = 'TRA_LABELS'
     AND column_name = 'TLADESC';

  IF v_type = 'CLOB' THEN
    NULL;
  ELSIF v_type IN ('VARCHAR2', 'NVARCHAR2', 'CHAR', 'NCHAR') THEN
    EXECUTE IMMEDIATE 'ALTER TABLE TRA_LABELS ADD (TLADESC_CLOB CLOB)';
    EXECUTE IMMEDIATE 'UPDATE TRA_LABELS SET TLADESC_CLOB = TLADESC';
    EXECUTE IMMEDIATE 'ALTER TABLE TRA_LABELS DROP COLUMN TLADESC';
    EXECUTE IMMEDIATE 'ALTER TABLE TRA_LABELS RENAME COLUMN TLADESC_CLOB TO TLADESC';
  ELSE
    RAISE_APPLICATION_ERROR(-20001, 'TRA_LABELS.TLADESC unexpected type: ' || v_type);
  END IF;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    RAISE_APPLICATION_ERROR(-20002, 'TRA_LABELS.TLADESC column not found — deploy base ICR schema first');
END;
/

DELETE FROM LIBQUERY WHERE QUERYNUM = 'DIC0000014';

INSERT INTO LIBQUERY (QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'DIC0000014',
       'Labels - bulk MERGE',
       'POST :param1=REQUESTID. values[]: TLAID, TLADESC (CLOB), TLAMENU, TLASCREEN, TLALANGUE, TLAUTIL.',
       q'~
MERGE INTO TRA_LABELS t
USING (
  SELECT SUBSTR(TRIM(j.TLAID), 1, 15) TLAID,
         TO_CLOB(NVL(TRIM(j.TLADESC), ' ')) TLADESC,
         NVL(TO_NUMBER(j.TLAMENU), 0) TLAMENU,
         NVL(TRIM(j.TLASCREEN), ' ') TLASCREEN,
         NVL(NULLIF(TRIM(j.TLALANGUE), ''), 'us_US') TLALANGUE,
         TRIM(j.TLAUTIL) TLAUTIL
    FROM REQUEST_QUERY_BODY rb,
         JSON_TABLE(rb.REQUESTBODY, '$.values[*]'
           COLUMNS (
             TLAID     VARCHAR2(60)   PATH '$."TLAID"',
             TLADESC   VARCHAR2(4000) PATH '$."TLADESC"',
             TLAMENU   VARCHAR2(5)    PATH '$."TLAMENU"',
             TLASCREEN VARCHAR2(20)   PATH '$."TLASCREEN"',
             TLALANGUE VARCHAR2(10)   PATH '$."TLALANGUE"',
             TLAUTIL   VARCHAR2(20)   PATH '$."TLAUTIL"'
           )
         ) j
   WHERE rb.REQUESTID = :param1
     AND TRIM(j.TLAID) IS NOT NULL
) s
ON (t.TLAID = s.TLAID AND t.TLALANGUE = s.TLALANGUE)
WHEN MATCHED THEN UPDATE SET
  t.TLADESC = s.TLADESC, t.TLAMENU = s.TLAMENU, t.TLASCREEN = s.TLASCREEN,
  t.TLADMAJ = SYSDATE, t.TLAUTIL = s.TLAUTIL
WHEN NOT MATCHED THEN INSERT (
  TLAID, TLADESC, TLAMENU, TLASCREEN, TLALANGUE, TLADCRE, TLADMAJ, TLAUTIL)
VALUES (s.TLAID, s.TLADESC, s.TLAMENU, s.TLASCREEN, s.TLALANGUE, SYSDATE, SYSDATE, s.TLAUTIL)
~',
       ':param1=REQUESTID',
       '',
       0, 0, 1 FROM dual;

COMMIT;

SET DEFINE ON;
