-- Pallet/SSCC traceability — Warehouse box menu (incremental)
-- Angular route: /pallettrace  |  Screen SCR0000000087
-- Deploy after 110_pallet_sscc_trace_libquery.sql + 111_tra_labels_pallet_sscc_trace.sql
-- Re-login after deploy to refresh SET0000040 menu.

SET DEFINE OFF;

MERGE INTO ICR_MENU_ENTRY t
USING (
  SELECT 'ROUTE_PLTTRACE' AS MENU_CODE, 'GRP_WAREHOUSE' AS PARENT_CODE, 'ROUTE' AS MENU_TYPE,
         'STANDARD' AS MENU_MODE, '/pallettrace' AS ROUTE_PATH, 'fas fa-barcode' AS ICON_CLASS,
         'Pallet/SSCC traceability' AS LABEL_TEXT, 186 AS SORT_ORDER, NULL AS EXPAND_KEY, 1 AS ACTIVE
    FROM dual
) s ON (t.MENU_CODE = s.MENU_CODE)
WHEN MATCHED THEN UPDATE SET
  t.PARENT_CODE = s.PARENT_CODE, t.MENU_TYPE = s.MENU_TYPE, t.MENU_MODE = s.MENU_MODE,
  t.ROUTE_PATH = s.ROUTE_PATH, t.ICON_CLASS = s.ICON_CLASS, t.LABEL_TEXT = s.LABEL_TEXT,
  t.SORT_ORDER = s.SORT_ORDER, t.ACTIVE = s.ACTIVE
WHEN NOT MATCHED THEN INSERT (
  MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE
) VALUES (
  s.MENU_CODE, s.PARENT_CODE, s.MENU_TYPE, s.MENU_MODE, s.ROUTE_PATH,
  s.ICON_CLASS, s.LABEL_TEXT, s.SORT_ORDER, s.EXPAND_KEY, s.ACTIVE
);

INSERT INTO ICR_MENU_ACCESS_RULE (MENU_CODE, FLAG_NAME)
SELECT 'ROUTE_PLTTRACE', 'WAREHOUSE' FROM dual
 WHERE NOT EXISTS (
       SELECT 1 FROM ICR_MENU_ACCESS_RULE r
        WHERE r.MENU_CODE = 'ROUTE_PLTTRACE' AND r.FLAG_NAME = 'WAREHOUSE'
 );

INSERT INTO ICR_MENU_ACCESS_RULE (MENU_CODE, FLAG_NAME)
SELECT 'ROUTE_PLTTRACE', 'ADMIN' FROM dual
 WHERE NOT EXISTS (
       SELECT 1 FROM ICR_MENU_ACCESS_RULE r
        WHERE r.MENU_CODE = 'ROUTE_PLTTRACE' AND r.FLAG_NAME = 'ADMIN'
 );

COMMIT;

SET DEFINE ON;
