-- =============================================================================
-- 114_alertbug_table_libquery.sql
-- ALERTBUG — patch / bug-fix history per alert (ALERTS.ALTID)
--
-- Deploy on ICR app DB after 101_alerts_altspec.sql.
-- Re-runnable: DDL ignores ORA-01430 / ORA-00955; LIBQUERY DELETE+INSERT.
--
-- Columns (issue / resolution / notes as HTML CLOB — same pattern as ALERTS.ALTSPEC):
--   BUGID, BALTID, BUGPATCHDAY, BUGRELEASEDATE,
--   BUGISSUE, BUGRESOLUTION, BUGNOTES,
--   BUGDCRE, BUGDMAJ, BUGUTIL
--
-- LIBQUERY:
--   ALT0000040  GET  list by alert id
--   ALT0000041  GET  one by bug id
--   ALT0000042  POST MERGE (insert/update)
--   ALT0000043  POST DELETE by bug id
-- =============================================================================

SET DEFINE OFF;
SET SQLBLANKLINES ON;

-- ── DDL (run once; safe to re-run) ───────────────────────────────────────────
-- Avoid q'[...]' / NULLS LAST in CREATE INDEX (ORA-00907 on older Oracle).
DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO v_cnt
    FROM user_tables
   WHERE table_name = 'ALERTBUG';

  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE
      'CREATE TABLE ALERTBUG (' ||
      '  BUGID            VARCHAR2(50) NOT NULL,' ||
      '  BALTID           VARCHAR2(50) NOT NULL,' ||
      '  BUGPATCHDAY      DATE,' ||
      '  BUGRELEASEDATE   DATE,' ||
      '  BUGISSUE         CLOB,' ||
      '  BUGRESOLUTION    CLOB,' ||
      '  BUGNOTES         CLOB,' ||
      '  BUGDCRE          DATE DEFAULT SYSDATE,' ||
      '  BUGDMAJ          DATE,' ||
      '  BUGUTIL          VARCHAR2(50),' ||
      '  CONSTRAINT PK_ALERTBUG PRIMARY KEY (BUGID)' ||
      ')';
    DBMS_OUTPUT.PUT_LINE('ALERTBUG created.');
  ELSE
    DBMS_OUTPUT.PUT_LINE('ALERTBUG already exists - skipped.');
  END IF;
END;
/

DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO v_cnt
    FROM user_indexes
   WHERE index_name = 'IDX_ALERTBUG_BALTID';

  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE
      'CREATE INDEX IDX_ALERTBUG_BALTID ON ALERTBUG (BALTID, BUGPATCHDAY)';
    DBMS_OUTPUT.PUT_LINE('IDX_ALERTBUG_BALTID created.');
  ELSE
    DBMS_OUTPUT.PUT_LINE('IDX_ALERTBUG_BALTID already exists - skipped.');
  END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[COMMENT ON TABLE ALERTBUG IS 'Alert bug-fix / patch history (per ALTID)']';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN ALERTBUG.BUGID IS 'Patch entry PK']';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN ALERTBUG.BALTID IS 'ALERTS.ALTID']';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN ALERTBUG.BUGPATCHDAY IS 'Day the patch was applied']';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN ALERTBUG.BUGRELEASEDATE IS 'Day the fix was released']';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN ALERTBUG.BUGISSUE IS 'Issue description (CLOB)']';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN ALERTBUG.BUGRESOLUTION IS 'Resolution process (CLOB)']';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN ALERTBUG.BUGNOTES IS 'Optional notes (CLOB)']';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
-- ── LIBQUERY ─────────────────────────────────────────────────────────────────
DELETE FROM LIBQUERY WHERE QUERYNUM IN ('ALT0000040', 'ALT0000041', 'ALT0000042', 'ALT0000043');

-- ALT0000040 — list patches for an alert
INSERT INTO LIBQUERY (
  QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL,
  QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE
)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'ALT0000040',
       'Alert bug history - list',
       'GET patch history for alert. :param1=ALTID (BALTID).',
       q'!
SELECT b.BUGID,
       b.BALTID,
       TO_CHAR(b.BUGPATCHDAY, 'YYYY-MM-DD') AS BUGPATCHDAY,
       TO_CHAR(b.BUGRELEASEDATE, 'YYYY-MM-DD') AS BUGRELEASEDATE,
       b.BUGISSUE,
       b.BUGRESOLUTION,
       b.BUGNOTES,
       TO_CHAR(b.BUGDCRE, 'YYYY-MM-DD HH24:MI:SS') AS BUGDCRE,
       TO_CHAR(b.BUGDMAJ, 'YYYY-MM-DD HH24:MI:SS') AS BUGDMAJ,
       b.BUGUTIL
  FROM ALERTBUG b
 WHERE b.BALTID = :param1
 ORDER BY b.BUGPATCHDAY DESC NULLS LAST, b.BUGDCRE DESC NULLS LAST
!',
       ':param1=altid',
       'BUGID,BALTID,BUGPATCHDAY,BUGRELEASEDATE,BUGISSUE,BUGRESOLUTION,BUGNOTES,BUGDCRE,BUGDMAJ,BUGUTIL',
       1, 0, 0
  FROM dual;

-- ALT0000041 — get one patch
INSERT INTO LIBQUERY (
  QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL,
  QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE
)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'ALT0000041',
       'Alert bug history - get',
       'GET one patch entry. :param1=BUGID.',
       q'!
SELECT b.BUGID,
       b.BALTID,
       TO_CHAR(b.BUGPATCHDAY, 'YYYY-MM-DD') AS BUGPATCHDAY,
       TO_CHAR(b.BUGRELEASEDATE, 'YYYY-MM-DD') AS BUGRELEASEDATE,
       b.BUGISSUE,
       b.BUGRESOLUTION,
       b.BUGNOTES,
       TO_CHAR(b.BUGDCRE, 'YYYY-MM-DD HH24:MI:SS') AS BUGDCRE,
       TO_CHAR(b.BUGDMAJ, 'YYYY-MM-DD HH24:MI:SS') AS BUGDMAJ,
       b.BUGUTIL
  FROM ALERTBUG b
 WHERE b.BUGID = :param1
!',
       ':param1=bugid',
       'BUGID,BALTID,BUGPATCHDAY,BUGRELEASEDATE,BUGISSUE,BUGRESOLUTION,BUGNOTES,BUGDCRE,BUGDMAJ,BUGUTIL',
       1, 0, 0
  FROM dual;

-- ALT0000042 — MERGE patch (CLOB issue / resolution / notes)
INSERT INTO LIBQUERY (
  QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL,
  QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE
)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'ALT0000042',
       'Alert bug history - merge',
       'POST :param1=REQUESTID. values[]: BUGID (optional on insert), BALTID, BUGPATCHDAY, BUGRELEASEDATE, BUGISSUE, BUGRESOLUTION, BUGNOTES, BUGUTIL. Dates YYYY-MM-DD.',
       TO_CLOB(q'!
MERGE INTO ALERTBUG t
USING (
  SELECT NVL(NULLIF(TRIM(j.BUGID), ''), RAWTOHEX(SYS_GUID())) AS BUGID,
         TRIM(j.BALTID) AS BALTID,
         CASE
           WHEN j.BUGPATCHDAY IS NULL OR TRIM(j.BUGPATCHDAY) IS NULL THEN NULL
           ELSE TO_DATE(SUBSTR(TRIM(j.BUGPATCHDAY), 1, 10), 'YYYY-MM-DD')
         END AS BUGPATCHDAY,
         CASE
           WHEN j.BUGRELEASEDATE IS NULL OR TRIM(j.BUGRELEASEDATE) IS NULL THEN NULL
           ELSE TO_DATE(SUBSTR(TRIM(j.BUGRELEASEDATE), 1, 10), 'YYYY-MM-DD')
         END AS BUGRELEASEDATE,
         j.BUGISSUE AS BUGISSUE,
         j.BUGRESOLUTION AS BUGRESOLUTION,
         j.BUGNOTES AS BUGNOTES,
         SUBSTR(TRIM(j.BUGUTIL), 1, 50) AS BUGUTIL
    FROM REQUEST_QUERY_BODY rb,
         JSON_TABLE(rb.REQUESTBODY, '$.values[*]'
           COLUMNS (
             BUGID          VARCHAR2(50)   PATH '$."BUGID"',
             BALTID         VARCHAR2(50)   PATH '$."BALTID"',
             BUGPATCHDAY    VARCHAR2(30)   PATH '$."BUGPATCHDAY"',
             BUGRELEASEDATE VARCHAR2(30)   PATH '$."BUGRELEASEDATE"',
             BUGISSUE       CLOB           PATH '$."BUGISSUE"',
             BUGRESOLUTION  CLOB           PATH '$."BUGRESOLUTION"',
             BUGNOTES       CLOB           PATH '$."BUGNOTES"',
             BUGUTIL        VARCHAR2(50)   PATH '$."BUGUTIL"'
           )
         ) j
   WHERE rb.REQUESTID = :param1
     AND TRIM(j.BALTID) IS NOT NULL
) s
ON (t.BUGID = s.BUGID)
WHEN MATCHED THEN UPDATE SET
  t.BALTID         = s.BALTID,
  t.BUGPATCHDAY    = s.BUGPATCHDAY,
  t.BUGRELEASEDATE = s.BUGRELEASEDATE,
  t.BUGISSUE       = s.BUGISSUE,
  t.BUGRESOLUTION  = s.BUGRESOLUTION,
  t.BUGNOTES       = s.BUGNOTES,
  t.BUGDMAJ        = SYSDATE,
  t.BUGUTIL        = NVL(s.BUGUTIL, t.BUGUTIL)
WHEN NOT MATCHED THEN INSERT (
  BUGID, BALTID, BUGPATCHDAY, BUGRELEASEDATE,
  BUGISSUE, BUGRESOLUTION, BUGNOTES,
  BUGDCRE, BUGDMAJ, BUGUTIL
) VALUES (
  s.BUGID, s.BALTID, s.BUGPATCHDAY, s.BUGRELEASEDATE,
  s.BUGISSUE, s.BUGRESOLUTION, s.BUGNOTES,
  SYSDATE, SYSDATE, s.BUGUTIL
)
!'),
       ':param1=REQUESTID',
       'BUGID',
       0, 0, 1
  FROM dual;

-- ALT0000043 — DELETE patch
INSERT INTO LIBQUERY (
  QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL,
  QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE
)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'ALT0000043',
       'Alert bug history - delete',
       'POST :param1=REQUESTID. values[]: BUGID.',
       q'!
DELETE FROM ALERTBUG b
 WHERE b.BUGID IN (
   SELECT TRIM(j.BUGID)
     FROM REQUEST_QUERY_BODY rb,
          JSON_TABLE(rb.REQUESTBODY, '$.values[*]'
            COLUMNS (BUGID VARCHAR2(50) PATH '$."BUGID"')
          ) j
    WHERE rb.REQUESTID = :param1
      AND TRIM(j.BUGID) IS NOT NULL
 )
!',
       ':param1=REQUESTID',
       'BUGID',
       0, 0, 1
  FROM dual;

COMMIT;
