-- =============================================================================
-- 120_icr_news_patch.sql
-- Header What's new: ICR_NEWS + LIBQUERY SET0000070-0074
-- Incremental -- safe to re-run. DDL is idempotent (CREATE if missing + ALTER extra columns).
-- NOTIFICATION_DATE: login banner is shown through that calendar day (NULL = no auto banner).
-- NOTIFICATION_MSG: short text shown in the login banner (BODY stays on the archive).
-- Mail list (SET0000070) returns every published item; SET0000074 is the login banner slice.
--
-- SET0000070 GET published (everyone -- full archive)
-- SET0000071 GET all (admin)
-- SET0000072 MERGE (admin)
-- SET0000073 DELETE (admin)
-- SET0000074 GET login banner (published + NOTIFICATION_DATE still active)
-- HDR_NEWS_MAIL -- toolbar newspaper (MENU_TYPE HEADER, excluded from profile dropdown)
-- =============================================================================

SET DEFINE OFF;
SET SCAN OFF;

DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM user_tables WHERE table_name = 'ICR_NEWS';
  IF n = 0 THEN
    EXECUTE IMMEDIATE
      'CREATE TABLE ICR_NEWS (
         NEWS_ID            NUMBER         NOT NULL,
         ITEM_TYPE          VARCHAR2(10)   NOT NULL,
         TITLE              NVARCHAR2(200) NOT NULL,
         BODY               CLOB,
         PUBLISHED          NUMBER(1)      DEFAULT 1 NOT NULL,
         PUBLISHED_ON       DATE,
         PUBLISHED_BY       VARCHAR2(50),
         NOTIFICATION_DATE  DATE,
         NOTIFICATION_MSG   NVARCHAR2(2000),
         ICON               NVARCHAR2(40),
         CREATED_ON         DATE           DEFAULT SYSDATE,
         UPDATED_ON         DATE,
         CREATED_BY         VARCHAR2(50),
         UPDATED_BY         VARCHAR2(50),
         CONSTRAINT pk_icr_news PRIMARY KEY (NEWS_ID),
         CONSTRAINT chk_icr_news_type CHECK (ITEM_TYPE IN (''NEWS'',''PATCH'')),
         CONSTRAINT chk_icr_news_pub CHECK (PUBLISHED IN (0,1))
       )';
  END IF;
END;
/

DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM user_tab_columns
   WHERE table_name = 'ICR_NEWS' AND column_name = 'NOTIFICATION_DATE';
  IF n = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE ICR_NEWS ADD NOTIFICATION_DATE DATE';
  END IF;
  SELECT COUNT(*) INTO n FROM user_tab_columns
   WHERE table_name = 'ICR_NEWS' AND column_name = 'NOTIFICATION_MSG';
  IF n = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE ICR_NEWS ADD NOTIFICATION_MSG NVARCHAR2(2000)';
  END IF;
  SELECT COUNT(*) INTO n FROM user_tab_columns
   WHERE table_name = 'ICR_NEWS' AND column_name = 'ICON';
  IF n = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE ICR_NEWS ADD ICON NVARCHAR2(40)';
  END IF;
END;
/

BEGIN
  FOR r IN (
    SELECT column_name, data_type, char_length
      FROM user_tab_columns
     WHERE table_name = 'ICR_NEWS'
       AND column_name IN ('TITLE','NOTIFICATION_MSG','BODY')
  ) LOOP
    IF r.column_name = 'TITLE' AND r.data_type = 'VARCHAR2' THEN
      EXECUTE IMMEDIATE 'ALTER TABLE ICR_NEWS MODIFY TITLE NVARCHAR2(200)';
    ELSIF r.column_name = 'NOTIFICATION_MSG' AND r.data_type = 'VARCHAR2' THEN
      EXECUTE IMMEDIATE 'ALTER TABLE ICR_NEWS MODIFY NOTIFICATION_MSG NVARCHAR2(2000)';
    ELSIF r.column_name = 'BODY' AND r.data_type = 'VARCHAR2' THEN
      EXECUTE IMMEDIATE 'ALTER TABLE ICR_NEWS MODIFY BODY CLOB';
    END IF;
  END LOOP;
END;
/

UPDATE ICR_MENU_ENTRY
   SET MENU_TYPE  = 'HEADER',
       MENU_MODE  = 'BOTH',
       ICON_CLASS = 'fas fa-newspaper',
       LABEL_TEXT = q'~What's new~',
       SORT_ORDER = 5,
       ACTIVE     = 1
 WHERE MENU_CODE = 'HDR_NEWS_MAIL';

INSERT INTO ICR_MENU_ENTRY (
  MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH,
  ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE)
SELECT
  'HDR_NEWS_MAIL', NULL, 'HEADER', 'BOTH', NULL,
  'fas fa-newspaper', q'~What's new~', 5, NULL, 1
  FROM dual
 WHERE NOT EXISTS (
       SELECT 1 FROM ICR_MENU_ENTRY e WHERE e.MENU_CODE = 'HDR_NEWS_MAIL'
 );

INSERT INTO ICR_MENU_ACCESS_RULE (MENU_CODE, FLAG_NAME)
SELECT 'HDR_NEWS_MAIL', 'ALL' FROM dual
 WHERE NOT EXISTS (
   SELECT 1 FROM ICR_MENU_ACCESS_RULE r
    WHERE r.MENU_CODE = 'HDR_NEWS_MAIL' AND r.FLAG_NAME = 'ALL');

DELETE FROM LIBQUERY WHERE QUERYNUM IN ('SET0000070','SET0000071','SET0000072','SET0000073','SET0000074');

INSERT INTO LIBQUERY (
  QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT,
  QUERYACCESS, QUERYTYPE, QUERYUPDATE
)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'SET0000070',
       'News - published list',
       'All published news/patches. :param1=ITEM_TYPE NEWS|PATCH or -1 for all.',
       q'~SELECT NEWS_ID, ITEM_TYPE, TITLE, BODY, PUBLISHED, ICON,
       TO_CHAR(NVL(PUBLISHED_ON, CREATED_ON), 'MM/DD/YYYY HH24:MI') PUBLISHED_ON,
       NVL(PUBLISHED_BY, CREATED_BY) PUBLISHED_BY,
       TO_CHAR(NOTIFICATION_DATE, 'YYYY-MM-DD') NOTIFICATION_DATE,
       NOTIFICATION_MSG
  FROM ICR_NEWS
 WHERE PUBLISHED = 1
   AND (:param1 = '-1' OR ITEM_TYPE = :param1)
 ORDER BY NVL(PUBLISHED_ON, CREATED_ON) DESC, NEWS_ID DESC~',
       ':param1=item_type',
       'NEWS_ID,ITEM_TYPE,TITLE,BODY,PUBLISHED,ICON,PUBLISHED_ON,PUBLISHED_BY,NOTIFICATION_DATE,NOTIFICATION_MSG',
       1, 0, 0 FROM dual;

INSERT INTO LIBQUERY (
  QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT,
  QUERYACCESS, QUERYTYPE, QUERYUPDATE
)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'SET0000071',
       'News - admin list',
       'All news/patches including drafts. :param1=ITEM_TYPE or -1. Admin only.',
       q'~SELECT NEWS_ID, ITEM_TYPE, TITLE, BODY, PUBLISHED, ICON,
       TO_CHAR(NVL(PUBLISHED_ON, CREATED_ON), 'MM/DD/YYYY HH24:MI') PUBLISHED_ON,
       NVL(PUBLISHED_BY, CREATED_BY) PUBLISHED_BY,
       TO_CHAR(NOTIFICATION_DATE, 'YYYY-MM-DD') NOTIFICATION_DATE,
       NOTIFICATION_MSG,
       CREATED_BY,
       TO_CHAR(UPDATED_ON, 'MM/DD/YYYY HH24:MI') UPDATED_ON
  FROM ICR_NEWS
 WHERE (:param1 = '-1' OR ITEM_TYPE = :param1)
 ORDER BY NEWS_ID DESC~',
       ':param1=item_type',
       'NEWS_ID,ITEM_TYPE,TITLE,BODY,PUBLISHED,ICON,PUBLISHED_ON,PUBLISHED_BY,NOTIFICATION_DATE,NOTIFICATION_MSG,CREATED_BY,UPDATED_ON',
       0, 0, 0 FROM dual;

INSERT INTO LIBQUERY (
  QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT,
  QUERYACCESS, QUERYTYPE, QUERYUPDATE
)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'SET0000072',
       'News - MERGE',
       'Body values NEWS_ID,ITEM_TYPE,TITLE,BODY,PUBLISHED,ICON,NOTIFICATION_DATE,NOTIFICATION_MSG,UPDATED_BY. NEWS_ID 0 = insert. Admin only. ICON=emoji.',
       q'~
MERGE INTO ICR_NEWS tgt
USING (
  SELECT CASE
           WHEN NVL(TO_NUMBER(jt.NEWS_ID), 0) > 0 THEN TO_NUMBER(jt.NEWS_ID)
           ELSE (SELECT NVL(MAX(NEWS_ID), 0) + 1 FROM ICR_NEWS)
         END NEWS_ID,
         UPPER(TRIM(jt.ITEM_TYPE)) ITEM_TYPE,
         jt.TITLE TITLE,
         jt.BODY,
         NVL(TO_NUMBER(jt.PUBLISHED), 1) PUBLISHED,
         CASE
           WHEN jt.NOTIFICATION_DATE IS NULL OR TRIM(jt.NOTIFICATION_DATE) IS NULL THEN CAST(NULL AS DATE)
           ELSE TO_DATE(SUBSTR(TRIM(jt.NOTIFICATION_DATE), 1, 10), 'YYYY-MM-DD')
         END NOTIFICATION_DATE,
         jt.NOTIFICATION_MSG NOTIFICATION_MSG,
         jt.ICON ICON,
         TRIM(jt.UPDATED_BY) UPDATED_BY
    FROM REQUEST_QUERY_BODY rb,
         JSON_TABLE(rb.REQUESTBODY, '$.values[0]'
           COLUMNS (
             NEWS_ID            VARCHAR2(20)      PATH '$."NEWS_ID"',
             ITEM_TYPE          VARCHAR2(10)      PATH '$."ITEM_TYPE"',
             TITLE              VARCHAR2(400 CHAR) PATH '$."TITLE"',
             BODY               CLOB              PATH '$."BODY"',
             PUBLISHED          VARCHAR2(5)       PATH '$."PUBLISHED"',
             NOTIFICATION_DATE  VARCHAR2(30)      PATH '$."NOTIFICATION_DATE"',
             NOTIFICATION_MSG   CLOB              PATH '$."NOTIFICATION_MSG"',
             ICON               VARCHAR2(100 CHAR) PATH '$."ICON"',
             UPDATED_BY         VARCHAR2(50)      PATH '$."UPDATED_BY"'
           )
         ) jt
   WHERE rb.REQUESTID = :param1
) src
ON (tgt.NEWS_ID = src.NEWS_ID)
WHEN MATCHED THEN UPDATE SET
  tgt.ITEM_TYPE = src.ITEM_TYPE,
  tgt.TITLE = src.TITLE,
  tgt.BODY = src.BODY,
  tgt.PUBLISHED = src.PUBLISHED,
  tgt.NOTIFICATION_DATE = src.NOTIFICATION_DATE,
  tgt.NOTIFICATION_MSG = src.NOTIFICATION_MSG,
  tgt.ICON = src.ICON,
  tgt.PUBLISHED_ON = CASE WHEN src.PUBLISHED = 1 THEN NVL(tgt.PUBLISHED_ON, SYSDATE) ELSE tgt.PUBLISHED_ON END,
  tgt.PUBLISHED_BY = CASE WHEN src.PUBLISHED = 1 THEN NVL(tgt.PUBLISHED_BY, src.UPDATED_BY) ELSE tgt.PUBLISHED_BY END,
  tgt.UPDATED_ON = SYSDATE,
  tgt.UPDATED_BY = src.UPDATED_BY
WHEN NOT MATCHED THEN INSERT (
  NEWS_ID, ITEM_TYPE, TITLE, BODY, PUBLISHED, PUBLISHED_ON, PUBLISHED_BY,
  NOTIFICATION_DATE, NOTIFICATION_MSG, ICON,
  CREATED_ON, UPDATED_ON, CREATED_BY, UPDATED_BY)
VALUES (
  src.NEWS_ID,
  src.ITEM_TYPE, src.TITLE, src.BODY, src.PUBLISHED,
  CASE WHEN src.PUBLISHED = 1 THEN SYSDATE ELSE NULL END,
  CASE WHEN src.PUBLISHED = 1 THEN src.UPDATED_BY ELSE NULL END,
  src.NOTIFICATION_DATE, src.NOTIFICATION_MSG, src.ICON,
  SYSDATE, SYSDATE, src.UPDATED_BY, src.UPDATED_BY)
~',
       ':param1=REQUESTID',
       '',
       0, 0, 1 FROM dual;

INSERT INTO LIBQUERY (
  QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT,
  QUERYACCESS, QUERYTYPE, QUERYUPDATE
)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'SET0000073',
       'News - DELETE',
       'Body values NEWS_ID. Admin only.',
       q'~
DELETE FROM ICR_NEWS
 WHERE NEWS_ID = (
   SELECT TO_NUMBER(jt.NEWS_ID)
     FROM REQUEST_QUERY_BODY rb,
          JSON_TABLE(rb.REQUESTBODY, '$.values[0]'
            COLUMNS (NEWS_ID VARCHAR2(20) PATH '$."NEWS_ID"')
          ) jt
    WHERE rb.REQUESTID = :param1
 )
~',
       ':param1=REQUESTID',
       '',
       0, 0, 1 FROM dual;

INSERT INTO LIBQUERY (
  QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT,
  QUERYACCESS, QUERYTYPE, QUERYUPDATE
)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'SET0000074',
       'News - login banner',
       'Published items with an active NOTIFICATION_DATE and NOTIFICATION_MSG (login popup). :param1 unused (-1).',
       q'~SELECT NEWS_ID, ITEM_TYPE, TITLE, NOTIFICATION_MSG, ICON, PUBLISHED,
       TO_CHAR(NVL(PUBLISHED_ON, CREATED_ON), 'MM/DD/YYYY HH24:MI') PUBLISHED_ON,
       NVL(PUBLISHED_BY, CREATED_BY) PUBLISHED_BY,
       TO_CHAR(NOTIFICATION_DATE, 'YYYY-MM-DD') NOTIFICATION_DATE
  FROM ICR_NEWS
 WHERE PUBLISHED = 1
   AND NOTIFICATION_DATE IS NOT NULL
   AND TRIM(NOTIFICATION_MSG) IS NOT NULL
   AND TRUNC(NOTIFICATION_DATE) >= TRUNC(SYSDATE)
   AND :param1 = :param1
 ORDER BY NVL(PUBLISHED_ON, CREATED_ON) DESC, NEWS_ID DESC~',
       ':param1=unused',
       'NEWS_ID,ITEM_TYPE,TITLE,NOTIFICATION_MSG,ICON,PUBLISHED,PUBLISHED_ON,PUBLISHED_BY,NOTIFICATION_DATE',
       1, 0, 0 FROM dual;

COMMIT;

SET DEFINE ON;
SET SCAN ON;

PROMPT 120_icr_news_patch.sql complete - ICR_NEWS + SET0000070-0074 + HDR_NEWS_MAIL
/
