-- General Settings - Corporate, Environment, Users, User–Environment access (LIBQUERY SET0000001–SET0000034)
-- Deploy to ICR app DB. Pattern: DELETE + INSERT, QUERYID = NVL(MAX(QUERYID),0)+1 per row.
-- QUERYTYPE   0 = SQL in QUERYSQL (SELECT and DML) — required for CALLQUERY / QueryService
-- QUERYUPDATE 0 = read (SELECT), 1 = DML (MERGE/INSERT/UPDATE/DELETE)
-- QUERYACCESS 0 = admin only, 1 = everyone

DELETE FROM LIBQUERY WHERE QUERYNUM IN (
    'SET0000001','SET0000002','SET0000003','SET0000004',
    'SET0000010','SET0000011','SET0000012','SET0000013',
    'SET0000020','SET0000021','SET0000022','SET0000023',
    'SET0000030','SET0000031','SET0000032','SET0000034'
);

-- ── CORPORATE ───────────────────────────────────────────────────────────────

INSERT INTO LIBQUERY (QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'SET0000001',
       'Corporate - list',
       'List corporates. :param1=code filter or -1; :param2=desc filter or -1.',
       q'~SELECT CORPID, CORPCODE, CORPSDESC, CORPLDESC, CORPCITY, CORPCOUNTRY, CORPPHONE, CORPEMAIL, CORPDMAJ, CORPUTIL
  FROM CORPORATE
 WHERE (:param1 = '-1' OR UPPER(NVL(CORPCODE,'')) LIKE '%' || UPPER(:param1) || '%')
   AND (:param2 = '-1' OR UPPER(NVL(CORPLDESC,'')) LIKE '%' || UPPER(:param2) || '%')
 ORDER BY CORPCODE~',
       ':param1=code_filter,:param2=desc_filter',
       'CORPID,CORPCODE,CORPSDESC,CORPLDESC,CORPCITY,CORPCOUNTRY,CORPPHONE,CORPEMAIL,CORPDMAJ,CORPUTIL',
       0, 0, 0 FROM dual;

INSERT INTO LIBQUERY (QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'SET0000002',
       'Corporate - by id',
       'Single corporate. :param1=CORPID.',
       q'~SELECT CORPID, CORPCODE, CORPSDESC, CORPLDESC,
       CORPSTREET1, CORPSTREET2, CORPZIPCODE, CORPSTATE, CORPCITY, CORPCOUNTRY,
       CORPINFO, CORPPHONE, CORPFNAME, CORPLNAME, CORPEMAIL, CORPPIC,
       CORPDCRE, CORPDMAJ, CORPUTIL
  FROM CORPORATE
 WHERE CORPID = TO_NUMBER(:param1)~',
       ':param1=corpid',
       'CORPID,CORPCODE,CORPSDESC,CORPLDESC,CORPSTREET1,CORPSTREET2,CORPZIPCODE,CORPSTATE,CORPCITY,CORPCOUNTRY,CORPINFO,CORPPHONE,CORPFNAME,CORPLNAME,CORPEMAIL,CORPPIC,CORPDCRE,CORPDMAJ,CORPUTIL',
       0, 0, 0 FROM dual;

INSERT INTO LIBQUERY (QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'SET0000003',
       'Corporate - MERGE',
       'Insert/update corporate. Body {values:[{CORPID,CORPCODE,...}]}. CORPID empty/0 = new id.',
       q'~
MERGE INTO CORPORATE tgt
USING (
  SELECT
    CASE WHEN NVL(jt.CORPID, 0) > 0 THEN jt.CORPID
         ELSE (SELECT NVL(MAX(CORPID), 0) + 1 FROM CORPORATE) END AS CORPID,
    jt.CORPCODE, jt.CORPSDESC, jt.CORPLDESC,
    jt.CORPSTREET1, jt.CORPSTREET2, jt.CORPZIPCODE, jt.CORPSTATE, jt.CORPCITY,
    TO_NUMBER(jt.CORPCOUNTRY) AS CORPCOUNTRY,
    jt.CORPINFO, jt.CORPPHONE, jt.CORPFNAME, jt.CORPLNAME, jt.CORPEMAIL, jt.CORPPIC,
    jt.CORPUTIL
  FROM REQUEST_QUERY_BODY rb,
       JSON_TABLE(rb.REQUESTBODY, '$.values[0]'
         COLUMNS (
           CORPID        NUMBER        PATH '$."CORPID"',
           CORPCODE      VARCHAR2(5)   PATH '$."CORPCODE"',
           CORPSDESC     VARCHAR2(20)  PATH '$."CORPSDESC"',
           CORPLDESC     VARCHAR2(100) PATH '$."CORPLDESC"',
           CORPSTREET1   VARCHAR2(100) PATH '$."CORPSTREET1"',
           CORPSTREET2   VARCHAR2(100) PATH '$."CORPSTREET2"',
           CORPZIPCODE   VARCHAR2(20)  PATH '$."CORPZIPCODE"',
           CORPSTATE     VARCHAR2(30)  PATH '$."CORPSTATE"',
           CORPCITY      VARCHAR2(50)  PATH '$."CORPCITY"',
           CORPCOUNTRY   VARCHAR2(20)  PATH '$."CORPCOUNTRY"',
           CORPINFO      VARCHAR2(1000) PATH '$."CORPINFO"',
           CORPPHONE     VARCHAR2(30)  PATH '$."CORPPHONE"',
           CORPFNAME     VARCHAR2(100) PATH '$."CORPFNAME"',
           CORPLNAME     VARCHAR2(100) PATH '$."CORPLNAME"',
           CORPEMAIL     VARCHAR2(100) PATH '$."CORPEMAIL"',
           CORPPIC       VARCHAR2(100) PATH '$."CORPPIC"',
           CORPUTIL      VARCHAR2(20)  PATH '$."CORPUTIL"'
         )
       ) jt
  WHERE rb.REQUESTID = :param1
) src
ON (tgt.CORPID = src.CORPID)
WHEN MATCHED THEN UPDATE SET
  tgt.CORPCODE = src.CORPCODE, tgt.CORPSDESC = src.CORPSDESC, tgt.CORPLDESC = src.CORPLDESC,
  tgt.CORPSTREET1 = src.CORPSTREET1, tgt.CORPSTREET2 = src.CORPSTREET2,
  tgt.CORPZIPCODE = src.CORPZIPCODE, tgt.CORPSTATE = src.CORPSTATE, tgt.CORPCITY = src.CORPCITY,
  tgt.CORPCOUNTRY = src.CORPCOUNTRY, tgt.CORPINFO = src.CORPINFO, tgt.CORPPHONE = src.CORPPHONE,
  tgt.CORPFNAME = src.CORPFNAME, tgt.CORPLNAME = src.CORPLNAME, tgt.CORPEMAIL = src.CORPEMAIL,
  tgt.CORPPIC = src.CORPPIC, tgt.CORPDMAJ = SYSDATE, tgt.CORPUTIL = src.CORPUTIL
WHEN NOT MATCHED THEN INSERT (
  CORPID, CORPCODE, CORPSDESC, CORPLDESC, CORPSTREET1, CORPSTREET2, CORPZIPCODE, CORPSTATE,
  CORPCITY, CORPCOUNTRY, CORPINFO, CORPPHONE, CORPFNAME, CORPLNAME, CORPEMAIL, CORPPIC,
  CORPDCRE, CORPDMAJ, CORPUTIL
) VALUES (
  src.CORPID, src.CORPCODE, src.CORPSDESC, src.CORPLDESC, src.CORPSTREET1, src.CORPSTREET2,
  src.CORPZIPCODE, src.CORPSTATE, src.CORPCITY, src.CORPCOUNTRY, src.CORPINFO, src.CORPPHONE,
  src.CORPFNAME, src.CORPLNAME, src.CORPEMAIL, src.CORPPIC, SYSDATE, SYSDATE, src.CORPUTIL
)~',
       ':param1=REQUESTID',
       '',
       0, 0, 1 FROM dual;

INSERT INTO LIBQUERY (QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'SET0000004',
       'Corporate - delete',
       'Delete corporate by CORPID. Body {values:[{CORPID}]}.',
       q'~
DELETE FROM CORPORATE
 WHERE CORPID = (
  SELECT TO_NUMBER(jt.CORPID)
    FROM REQUEST_QUERY_BODY rb,
         JSON_TABLE(rb.REQUESTBODY, '$.values[0]' COLUMNS (CORPID VARCHAR2(20) PATH '$."CORPID"')) jt
   WHERE rb.REQUESTID = :param1
)~',
       ':param1=REQUESTID',
       '',
       0, 0, 1 FROM dual;

-- ── CORPENV (environment) ─────────────────────────────────────────────────────

INSERT INTO LIBQUERY (QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'SET0000010',
       'Environment - list',
       'List environments. :param1=ENVCORPID or -1 for all.',
       q'~SELECT e.ENVID, e.ENVCORPID, c.CORPCODE, e.ENVCODE, e.ENVSDESC, e.ENVLDESC,
       e.ENVTYPE, e.ENVACTIVE, e.ENVDBLINK, e.ENVGOLDSCHEMA, e.ENVDEFAULT, e.ENVTITLE, e.ENVDMAJ
  FROM CORPENV e
  LEFT JOIN CORPORATE c ON c.CORPID = e.ENVCORPID
 WHERE (:param1 = '-1' OR e.ENVCORPID = TO_NUMBER(:param1))
 ORDER BY c.CORPCODE, e.ENVCODE~',
       ':param1=corpid',
       'ENVID,ENVCORPID,CORPCODE,ENVCODE,ENVSDESC,ENVLDESC,ENVTYPE,ENVACTIVE,ENVDBLINK,ENVGOLDSCHEMA,ENVDEFAULT,ENVTITLE,ENVDMAJ',
       0, 0, 0 FROM dual;

INSERT INTO LIBQUERY (QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'SET0000011',
       'Environment - by id',
       'Single environment. :param1=ENVID.',
       q'~SELECT ENVID, ENVCORPID, ENVCODE, ENVTYPE, ENVACTIVE, ENVSDESC, ENVLDESC,
       ENVDBTYPE, ENVIP, ENVPORT, ENVUSER, ENVPASSWORD, ENVSOURCE, ENVDBLINK,
       ENVDEFAULT, ENVTITLE, ENVTITLECOLOR, ENVDOMAIN, ENVGOLDSCHEMA, ENVSTKDBLINK, ENVDEBUG,
       ENVDCRE, ENVDMAJ, ENVUTIL
  FROM CORPENV
 WHERE ENVID = TO_NUMBER(:param1)~',
       ':param1=envid',
       'ENVID,ENVCORPID,ENVCODE,ENVTYPE,ENVACTIVE,ENVSDESC,ENVLDESC,ENVDBTYPE,ENVIP,ENVPORT,ENVUSER,ENVPASSWORD,ENVSOURCE,ENVDBLINK,ENVDEFAULT,ENVTITLE,ENVTITLECOLOR,ENVDOMAIN,ENVGOLDSCHEMA,ENVSTKDBLINK,ENVDEBUG,ENVDCRE,ENVDMAJ,ENVUTIL',
       0, 0, 0 FROM dual;

INSERT INTO LIBQUERY (QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'SET0000012',
       'Environment - MERGE',
       'Insert/update CORPENV. Body {values:[{...}]}. ENVID empty/0 = new.',
       q'~
MERGE INTO CORPENV tgt
USING (
  SELECT
    CASE WHEN NVL(jt.ENVID, 0) > 0 THEN jt.ENVID
         ELSE (SELECT NVL(MAX(ENVID), 0) + 1 FROM CORPENV) END AS ENVID,
    TO_NUMBER(jt.ENVCORPID) AS ENVCORPID, jt.ENVCODE, TO_NUMBER(jt.ENVTYPE) AS ENVTYPE,
    NVL(TO_NUMBER(jt.ENVACTIVE), 1) AS ENVACTIVE,
    jt.ENVSDESC, jt.ENVLDESC, TO_NUMBER(jt.ENVDBTYPE) AS ENVDBTYPE,
    jt.ENVIP, TO_NUMBER(jt.ENVPORT) AS ENVPORT, jt.ENVUSER, jt.ENVPASSWORD,
    jt.ENVSOURCE, jt.ENVDBLINK, TO_NUMBER(jt.ENVDEFAULT) AS ENVDEFAULT,
    jt.ENVTITLE, jt.ENVTITLECOLOR, TO_NUMBER(jt.ENVDOMAIN) AS ENVDOMAIN,
    jt.ENVGOLDSCHEMA, jt.ENVSTKDBLINK, NVL(TO_NUMBER(jt.ENVDEBUG), 0) AS ENVDEBUG,
    jt.ENVUTIL
  FROM REQUEST_QUERY_BODY rb,
       JSON_TABLE(rb.REQUESTBODY, '$.values[0]'
         COLUMNS (
           ENVID          NUMBER        PATH '$."ENVID"',
           ENVCORPID      VARCHAR2(20)  PATH '$."ENVCORPID"',
           ENVCODE        VARCHAR2(20)  PATH '$."ENVCODE"',
           ENVTYPE        VARCHAR2(20)  PATH '$."ENVTYPE"',
           ENVACTIVE      VARCHAR2(5)   PATH '$."ENVACTIVE"',
           ENVSDESC       VARCHAR2(40)  PATH '$."ENVSDESC"',
           ENVLDESC       VARCHAR2(100) PATH '$."ENVLDESC"',
           ENVDBTYPE      VARCHAR2(20)  PATH '$."ENVDBTYPE"',
           ENVIP          VARCHAR2(100) PATH '$."ENVIP"',
           ENVPORT        VARCHAR2(10)  PATH '$."ENVPORT"',
           ENVUSER        VARCHAR2(100) PATH '$."ENVUSER"',
           ENVPASSWORD    VARCHAR2(100) PATH '$."ENVPASSWORD"',
           ENVSOURCE      VARCHAR2(100) PATH '$."ENVSOURCE"',
           ENVDBLINK      VARCHAR2(100) PATH '$."ENVDBLINK"',
           ENVDEFAULT     VARCHAR2(5)   PATH '$."ENVDEFAULT"',
           ENVTITLE       VARCHAR2(100) PATH '$."ENVTITLE"',
           ENVTITLECOLOR  VARCHAR2(20)  PATH '$."ENVTITLECOLOR"',
           ENVDOMAIN      VARCHAR2(10)  PATH '$."ENVDOMAIN"',
           ENVGOLDSCHEMA  VARCHAR2(10)  PATH '$."ENVGOLDSCHEMA"',
           ENVSTKDBLINK   VARCHAR2(128) PATH '$."ENVSTKDBLINK"',
           ENVDEBUG       VARCHAR2(5)   PATH '$."ENVDEBUG"',
           ENVUTIL        VARCHAR2(20)  PATH '$."ENVUTIL"'
         )
       ) jt
  WHERE rb.REQUESTID = :param1
) src
ON (tgt.ENVID = src.ENVID)
WHEN MATCHED THEN UPDATE SET
  tgt.ENVCORPID = src.ENVCORPID, tgt.ENVCODE = src.ENVCODE, tgt.ENVTYPE = src.ENVTYPE,
  tgt.ENVACTIVE = src.ENVACTIVE, tgt.ENVSDESC = src.ENVSDESC, tgt.ENVLDESC = src.ENVLDESC,
  tgt.ENVDBTYPE = src.ENVDBTYPE, tgt.ENVIP = src.ENVIP, tgt.ENVPORT = src.ENVPORT,
  tgt.ENVUSER = src.ENVUSER, tgt.ENVPASSWORD = src.ENVPASSWORD, tgt.ENVSOURCE = src.ENVSOURCE,
  tgt.ENVDBLINK = src.ENVDBLINK, tgt.ENVDEFAULT = src.ENVDEFAULT, tgt.ENVTITLE = src.ENVTITLE,
  tgt.ENVTITLECOLOR = src.ENVTITLECOLOR, tgt.ENVDOMAIN = src.ENVDOMAIN,
  tgt.ENVGOLDSCHEMA = src.ENVGOLDSCHEMA, tgt.ENVSTKDBLINK = src.ENVSTKDBLINK,
  tgt.ENVDEBUG = src.ENVDEBUG, tgt.ENVDMAJ = SYSDATE, tgt.ENVUTIL = src.ENVUTIL
WHEN NOT MATCHED THEN INSERT (
  ENVID, ENVCORPID, ENVCODE, ENVTYPE, ENVACTIVE, ENVSDESC, ENVLDESC, ENVDBTYPE,
  ENVIP, ENVPORT, ENVUSER, ENVPASSWORD, ENVSOURCE, ENVDBLINK, ENVDEFAULT,
  ENVTITLE, ENVTITLECOLOR, ENVDOMAIN, ENVGOLDSCHEMA, ENVSTKDBLINK, ENVDEBUG,
  ENVDCRE, ENVDMAJ, ENVUTIL, ENVVERSION
) VALUES (
  src.ENVID, src.ENVCORPID, src.ENVCODE, src.ENVTYPE, src.ENVACTIVE, src.ENVSDESC, src.ENVLDESC,
  src.ENVDBTYPE, src.ENVIP, src.ENVPORT, src.ENVUSER, src.ENVPASSWORD, src.ENVSOURCE, src.ENVDBLINK,
  src.ENVDEFAULT, src.ENVTITLE, src.ENVTITLECOLOR, src.ENVDOMAIN, src.ENVGOLDSCHEMA, src.ENVSTKDBLINK,
  src.ENVDEBUG, SYSDATE, SYSDATE, src.ENVUTIL, 1
)~',
       ':param1=REQUESTID',
       '',
       0, 0, 1 FROM dual;

INSERT INTO LIBQUERY (QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'SET0000013',
       'Environment - delete',
       'Delete environment. Body {values:[{ENVID}]}.',
       q'~
DELETE FROM CORPENV
 WHERE ENVID = (
  SELECT TO_NUMBER(jt.ENVID)
    FROM REQUEST_QUERY_BODY rb,
         JSON_TABLE(rb.REQUESTBODY, '$.values[0]' COLUMNS (ENVID VARCHAR2(20) PATH '$."ENVID"')) jt
   WHERE rb.REQUESTID = :param1
)~',
       ':param1=REQUESTID',
       '',
       0, 0, 1 FROM dual;

-- ── USERSROOM ─────────────────────────────────────────────────────────────────

INSERT INTO LIBQUERY (QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'SET0000020',
       'Users - list',
       'List users. :param1=USERCORPID or -1; :param2=USERACTIVE or -1.',
       q'~SELECT u.USERID, u.USERCORPID, c.CORPCODE, u.USERFNAME, u.USERLNAME, u.USEREMAIL,
       u.USERACTIVE, u.USERAPPLI, u.USERPROF, u.USERLANG, NVL(u.USERTYPE, 0) USERTYPE,
       u.USERDMAJ, u.USERUTIL
  FROM USERSROOM u
  LEFT JOIN CORPORATE c ON c.CORPID = u.USERCORPID
 WHERE (:param1 = '-1' OR u.USERCORPID = TO_NUMBER(:param1))
   AND (:param2 = '-1' OR u.USERACTIVE = TO_NUMBER(:param2))
 ORDER BY u.USERID~',
       ':param1=corpid,:param2=active',
       'USERID,USERCORPID,CORPCODE,USERFNAME,USERLNAME,USEREMAIL,USERACTIVE,USERAPPLI,USERPROF,USERLANG,USERTYPE,USERDMAJ,USERUTIL',
       0, 0, 0 FROM dual;

INSERT INTO LIBQUERY (QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'SET0000021',
       'Users - by id',
       'Single user. :param1=USERID; :param2=USERAPPLI.',
       q'~SELECT u.USERID, u.USERCORPID, u.USERPASS, u.USERAUTH, u.USERLANG, u.USERPROF, u.USERAPPLI,
       u.USERFNAME, u.USERLNAME, u.USEREMAIL, u.USERMOBILE, u.USERTEAM, u.USERACTIVE, u.USERMOBEMAIL,
       u.USERDATAINTEGRITY, u.USERIT, u.USERBUYER, u.USERHELPDESK, u.USERWAREHOUSE,
       u.USERSPACEPLANNING, u.USERSTECH, u.USERAIADMIN, u.USERAIDESIGNER,
       NVL(u.USERTYPE, 0) USERTYPE, u.USERDCRE, u.USERDMAJ, u.USERUTIL
  FROM USERSROOM u
 WHERE u.USERID = :param1
   AND u.USERAPPLI = TO_NUMBER(:param2)~',
       ':param1=userid,:param2=userappli',
       'USERID,USERCORPID,USERPASS,USERAUTH,USERLANG,USERPROF,USERAPPLI,USERFNAME,USERLNAME,USEREMAIL,USERMOBILE,USERTEAM,USERACTIVE,USERMOBEMAIL,USERDATAINTEGRITY,USERIT,USERBUYER,USERHELPDESK,USERWAREHOUSE,USERSPACEPLANNING,USERSTECH,USERAIADMIN,USERAIDESIGNER,USERTYPE,USERDCRE,USERDMAJ,USERUTIL',
       0, 0, 0 FROM dual;

INSERT INTO LIBQUERY (QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'SET0000022',
       'Users - MERGE',
       'Insert/update USERSROOM. Body {values:[{...}]}. USERPASS must be Base64 (client encodes plain text). Blank on update keeps existing.',
       TO_CLOB(q'~
MERGE INTO USERSROOM tgt
USING (
SELECT jt.USERID, TO_NUMBER(jt.USERCORPID) USERCORPID, NVL(TO_NUMBER(jt.USERAPPLI),1) USERAPPLI,
  jt.USERPASS, TO_NUMBER(jt.USERAUTH) USERAUTH, jt.USERLANG, TO_NUMBER(jt.USERPROF) USERPROF,
  jt.USERFNAME, jt.USERLNAME, jt.USEREMAIL, jt.USERMOBILE, TO_NUMBER(jt.USERTEAM) USERTEAM,
  NVL(TO_NUMBER(jt.USERACTIVE),1) USERACTIVE, jt.USERMOBEMAIL,
  NVL(TO_NUMBER(jt.USERDATAINTEGRITY),1) USERDATAINTEGRITY,
  NVL(TO_NUMBER(jt.USERIT),1) USERIT, NVL(TO_NUMBER(jt.USERBUYER),1) USERBUYER,
  NVL(TO_NUMBER(jt.USERHELPDESK),1) USERHELPDESK, NVL(TO_NUMBER(jt.USERWAREHOUSE),1) USERWAREHOUSE,
  NVL(TO_NUMBER(jt.USERSPACEPLANNING),1) USERSPACEPLANNING, NVL(TO_NUMBER(jt.USERSTECH),1) USERSTECH,
  NVL(TO_NUMBER(jt.USERAIADMIN),0) USERAIADMIN, NVL(TO_NUMBER(jt.USERAIDESIGNER),0) USERAIDESIGNER,
  NVL(TO_NUMBER(jt.USERTYPE),0) USERTYPE, jt.USERUTIL, jt.UPDATE_PASS
FROM REQUEST_QUERY_BODY rb,
JSON_TABLE(rb.REQUESTBODY,'$.values[0]' COLUMNS (
  USERID VARCHAR2(20) PATH '$."USERID"', USERCORPID VARCHAR2(20) PATH '$."USERCORPID"',
  USERAPPLI VARCHAR2(10) PATH '$."USERAPPLI"', USERPASS VARCHAR2(40) PATH '$."USERPASS"',
  USERAUTH VARCHAR2(10) PATH '$."USERAUTH"', USERLANG VARCHAR2(5) PATH '$."USERLANG"',
  USERPROF VARCHAR2(20) PATH '$."USERPROF"', USERFNAME VARCHAR2(30) PATH '$."USERFNAME"',
  USERLNAME VARCHAR2(50) PATH '$."USERLNAME"', USEREMAIL VARCHAR2(50) PATH '$."USEREMAIL"',
  USERMOBILE VARCHAR2(30) PATH '$."USERMOBILE"', USERTEAM VARCHAR2(20) PATH '$."USERTEAM"',
  USERACTIVE VARCHAR2(5) PATH '$."USERACTIVE"', USERMOBEMAIL VARCHAR2(50) PATH '$."USERMOBEMAIL"',
  USERDATAINTEGRITY VARCHAR2(5) PATH '$."USERDATAINTEGRITY"', USERIT VARCHAR2(5) PATH '$."USERIT"',
  USERBUYER VARCHAR2(5) PATH '$."USERBUYER"', USERHELPDESK VARCHAR2(5) PATH '$."USERHELPDESK"',
  USERWAREHOUSE VARCHAR2(5) PATH '$."USERWAREHOUSE"',
  USERSPACEPLANNING VARCHAR2(5) PATH '$."USERSPACEPLANNING"', USERSTECH VARCHAR2(5) PATH '$."USERSTECH"',
  USERAIADMIN VARCHAR2(5) PATH '$."USERAIADMIN"', USERAIDESIGNER VARCHAR2(5) PATH '$."USERAIDESIGNER"',
  USERTYPE VARCHAR2(5) PATH '$."USERTYPE"', USERUTIL VARCHAR2(20) PATH '$."USERUTIL"',
  UPDATE_PASS VARCHAR2(5) PATH '$."UPDATE_PASS"'
)) jt WHERE rb.REQUESTID = :param1
) src
~') || q'~
ON (tgt.USERID = src.USERID AND tgt.USERAPPLI = src.USERAPPLI)
WHEN MATCHED THEN UPDATE SET
  tgt.USERCORPID=src.USERCORPID,tgt.USERAUTH=src.USERAUTH,tgt.USERLANG=src.USERLANG,
  tgt.USERPROF=src.USERPROF,tgt.USERFNAME=src.USERFNAME,tgt.USERLNAME=src.USERLNAME,
  tgt.USEREMAIL=src.USEREMAIL,tgt.USERMOBILE=src.USERMOBILE,tgt.USERTEAM=src.USERTEAM,
  tgt.USERACTIVE=src.USERACTIVE,tgt.USERMOBEMAIL=src.USERMOBEMAIL,
  tgt.USERDATAINTEGRITY=src.USERDATAINTEGRITY,tgt.USERIT=src.USERIT,tgt.USERBUYER=src.USERBUYER,
  tgt.USERHELPDESK=src.USERHELPDESK,tgt.USERWAREHOUSE=src.USERWAREHOUSE,
  tgt.USERSPACEPLANNING=src.USERSPACEPLANNING,tgt.USERSTECH=src.USERSTECH,
  tgt.USERAIADMIN=src.USERAIADMIN,tgt.USERAIDESIGNER=src.USERAIDESIGNER,tgt.USERTYPE=src.USERTYPE,
  tgt.USERPASS=CASE WHEN src.UPDATE_PASS='1' AND src.USERPASS IS NOT NULL THEN src.USERPASS ELSE tgt.USERPASS END,
  tgt.USERDMAJ=SYSDATE,tgt.USERUTIL=src.USERUTIL
WHEN NOT MATCHED THEN INSERT (
  USERID,USERCORPID,USERPASS,USERAUTH,USERLANG,USERPROF,USERAPPLI,USERFNAME,USERLNAME,USEREMAIL,
  USERMOBILE,USERTEAM,USERACTIVE,USERMOBEMAIL,USERDATAINTEGRITY,USERIT,USERBUYER,USERHELPDESK,
  USERWAREHOUSE,USERSPACEPLANNING,USERSTECH,USERAIADMIN,USERAIDESIGNER,USERTYPE,USERDCRE,USERDMAJ,USERUTIL)
VALUES (
  src.USERID,src.USERCORPID,src.USERPASS,src.USERAUTH,src.USERLANG,src.USERPROF,src.USERAPPLI,
  src.USERFNAME,src.USERLNAME,src.USEREMAIL,src.USERMOBILE,src.USERTEAM,src.USERACTIVE,src.USERMOBEMAIL,
  src.USERDATAINTEGRITY,src.USERIT,src.USERBUYER,src.USERHELPDESK,src.USERWAREHOUSE,
  src.USERSPACEPLANNING,src.USERSTECH,src.USERAIADMIN,src.USERAIDESIGNER,src.USERTYPE,
  SYSDATE,SYSDATE,src.USERUTIL)
~',
       ':param1=REQUESTID',
       '',
       0, 0, 1 FROM dual;

INSERT INTO LIBQUERY (QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'SET0000023',
       'Users - delete',
       'Delete user. Body {values:[{USERID,USERAPPLI}]}.',
       q'~
DELETE FROM USERSROOM
 WHERE USERID = (SELECT jt.USERID FROM REQUEST_QUERY_BODY rb,
       JSON_TABLE(rb.REQUESTBODY, '$.values[0]' COLUMNS (USERID VARCHAR2(20) PATH '$."USERID"')) jt
       WHERE rb.REQUESTID = :param1)
   AND USERAPPLI = (SELECT TO_NUMBER(jt.USERAPPLI) FROM REQUEST_QUERY_BODY rb,
       JSON_TABLE(rb.REQUESTBODY, '$.values[0]' COLUMNS (USERAPPLI VARCHAR2(10) PATH '$."USERAPPLI"')) jt
       WHERE rb.REQUESTID = :param1)
~',
       ':param1=REQUESTID',
       '',
       0, 0, 1 FROM dual;

INSERT INTO LIBQUERY (QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'SET0000024',
       'Users - change own password',
       'Logged-in user changes password. Body {values:[{USERID,USERAPPLI,CURRENT_PASS,NEW_PASS}]}. Passes Base64 (client encodes plain text). CURRENT_PASS must match USERSROOM.USERPASS.',
       TO_CLOB(q'~
DECLARE
  v_userid  VARCHAR2(20);
  v_appli   NUMBER;
  v_cur     VARCHAR2(40);
  v_new     VARCHAR2(40);
  v_cnt     NUMBER;
BEGIN
  SELECT jt.USERID, NVL(TO_NUMBER(jt.USERAPPLI), 1), jt.CURRENT_PASS, jt.NEW_PASS
    INTO v_userid, v_appli, v_cur, v_new
    FROM REQUEST_QUERY_BODY rb,
         JSON_TABLE(rb.REQUESTBODY, '$.values[0]'
           COLUMNS (
             USERID       VARCHAR2(20) PATH '$."USERID"',
             USERAPPLI    VARCHAR2(10) PATH '$."USERAPPLI"',
             CURRENT_PASS VARCHAR2(40) PATH '$."CURRENT_PASS"',
             NEW_PASS     VARCHAR2(40) PATH '$."NEW_PASS"'
           )
         ) jt
   WHERE rb.REQUESTID = :param1;

  IF v_new IS NULL OR TRIM(v_new) IS NULL THEN
    RAISE_APPLICATION_ERROR(-20024, 'New password is required.');
  END IF;

  UPDATE USERSROOM
     SET USERPASS = v_new,
         USERDMAJ = SYSDATE,
         USERUTIL = v_userid
   WHERE USERID = v_userid
     AND USERAPPLI = v_appli
     AND USERPASS = v_cur;

  v_cnt := SQL%ROWCOUNT;
  IF v_cnt = 0 THEN
    RAISE_APPLICATION_ERROR(-20025, 'Current password is incorrect.');
  END IF;
END;
~'),
       ':param1=REQUESTID',
       '',
       1, 0, 1 FROM dual;

-- ── USERSENV ──────────────────────────────────────────────────────────────────

INSERT INTO LIBQUERY (QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'SET0000030',
       'User env - list for user',
       'Assigned environments for user. :param1=USERID; :param2=CONCORPID or -1.',
       q'~SELECT ue.CONUSERID, ue.CONENVID, ue.CONCORPID, ue.CONACTIVE, ue.CONDEFAULT,
       e.ENVCODE, e.ENVSDESC, e.ENVLDESC, c.CORPCODE
  FROM USERSENV ue
  JOIN CORPENV e ON e.ENVID = ue.CONENVID AND e.ENVCORPID = ue.CONCORPID
  LEFT JOIN CORPORATE c ON c.CORPID = ue.CONCORPID
 WHERE ue.CONUSERID = :param1
   AND (:param2 = '-1' OR ue.CONCORPID = TO_NUMBER(:param2))
 ORDER BY c.CORPCODE, e.ENVCODE~',
       ':param1=userid,:param2=corpid',
       'CONUSERID,CONENVID,CONCORPID,CONACTIVE,CONDEFAULT,ENVCODE,ENVSDESC,ENVLDESC,CORPCODE',
       0, 0, 0 FROM dual;

INSERT INTO LIBQUERY (QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'SET0000034',
       'User env - access matrix',
       'All active envs for corp with user flags. :param1=USERID; :param2=CONCORPID.',
       q'~SELECT e.ENVID, e.ENVCORPID, e.ENVCODE, e.ENVSDESC, e.ENVLDESC,
       NVL(ue.CONACTIVE, 0) AS CONACTIVE,
       NVL(ue.CONDEFAULT, 0) AS CONDEFAULT,
       CASE WHEN ue.CONUSERID IS NOT NULL THEN 1 ELSE 0 END AS HAS_ACCESS
  FROM CORPENV e
  LEFT JOIN USERSENV ue
    ON ue.CONENVID = e.ENVID AND ue.CONCORPID = e.ENVCORPID AND ue.CONUSERID = :param1
 WHERE e.ENVCORPID = TO_NUMBER(:param2)
   AND e.ENVACTIVE = 1
 ORDER BY e.ENVCODE~',
       ':param1=userid,:param2=corpid',
       'ENVID,ENVCORPID,ENVCODE,ENVSDESC,ENVLDESC,CONACTIVE,CONDEFAULT,HAS_ACCESS',
       0, 0, 0 FROM dual;

INSERT INTO LIBQUERY (QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'SET0000031',
       'User env - MERGE',
       'Grant/update user environment. Body {values:[{CONUSERID,CONENVID,CONCORPID,...}]}.',
       q'~
MERGE INTO USERSENV tgt
USING (
  SELECT jt.CONUSERID, TO_NUMBER(jt.CONENVID) AS CONENVID, TO_NUMBER(jt.CONCORPID) AS CONCORPID,
         NVL(TO_NUMBER(jt.CONACTIVE), 1) AS CONACTIVE,
         NVL(TO_NUMBER(jt.CONDEFAULT), 0) AS CONDEFAULT,
         jt.CONUTIL
    FROM REQUEST_QUERY_BODY rb,
         JSON_TABLE(rb.REQUESTBODY, '$.values[0]'
           COLUMNS (
             CONUSERID  VARCHAR2(20) PATH '$."CONUSERID"',
             CONENVID   VARCHAR2(20) PATH '$."CONENVID"',
             CONCORPID  VARCHAR2(20) PATH '$."CONCORPID"',
             CONACTIVE  VARCHAR2(5)  PATH '$."CONACTIVE"',
             CONDEFAULT VARCHAR2(5)  PATH '$."CONDEFAULT"',
             CONUTIL    VARCHAR2(20) PATH '$."CONUTIL"'
           )
         ) jt
   WHERE rb.REQUESTID = :param1
) src
ON (tgt.CONUSERID = src.CONUSERID AND tgt.CONENVID = src.CONENVID AND tgt.CONCORPID = src.CONCORPID)
WHEN MATCHED THEN UPDATE SET
  tgt.CONACTIVE = src.CONACTIVE, tgt.CONDEFAULT = src.CONDEFAULT,
  tgt.CONDMAJ = SYSDATE, tgt.CONUTIL = src.CONUTIL
WHEN NOT MATCHED THEN INSERT (
  CONUSERID, CONENVID, CONCORPID, CONACTIVE, CONDEFAULT, CONDCRE, CONDMAJ, CONUTIL
) VALUES (
  src.CONUSERID, src.CONENVID, src.CONCORPID, src.CONACTIVE, src.CONDEFAULT,
  SYSDATE, SYSDATE, src.CONUTIL
)~',
       ':param1=REQUESTID',
       '',
       0, 0, 1 FROM dual;

INSERT INTO LIBQUERY (QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'SET0000032',
       'User env - delete',
       'Revoke environment access. Body {values:[{CONUSERID,CONENVID,CONCORPID}]}.',
       q'~
DELETE FROM USERSENV
 WHERE CONUSERID = (SELECT jt.CONUSERID FROM REQUEST_QUERY_BODY rb,
       JSON_TABLE(rb.REQUESTBODY, '$.values[0]' COLUMNS (CONUSERID VARCHAR2(20) PATH '$."CONUSERID"')) jt WHERE rb.REQUESTID = :param1)
   AND CONENVID = (SELECT TO_NUMBER(jt.CONENVID) FROM REQUEST_QUERY_BODY rb,
       JSON_TABLE(rb.REQUESTBODY, '$.values[0]' COLUMNS (CONENVID VARCHAR2(20) PATH '$."CONENVID"')) jt WHERE rb.REQUESTID = :param1)
   AND CONCORPID = (SELECT TO_NUMBER(jt.CONCORPID) FROM REQUEST_QUERY_BODY rb,
       JSON_TABLE(rb.REQUESTBODY, '$.values[0]' COLUMNS (CONCORPID VARCHAR2(20) PATH '$."CONCORPID"')) jt WHERE rb.REQUESTID = :param1)
~',
       ':param1=REQUESTID',
       '',
       0, 0, 1 FROM dual;

COMMIT;
