-- Menu access catalog, profiles, and effective-menu LIBQUERY (SET0000040–SET0000045)
-- Deploy to ICR app DB after 34_settings_users_corporate_libquery.sql
--
-- First-time: uncomment and run the DDL block below (ICR_MENU_* tables), then run seed + LIBQUERY.
--   ORA-00942 = tables missing — run the commented DDL block once.
--   ORA-00955 on DDL = tables already exist — skip DDL, run seed + LIBQUERY only.
--
-- Pattern: DELETE + INSERT on LIBQUERY (active section at bottom).

/*
-- ── DDL (run once) ───────────────────────────────────────────────────────────

CREATE TABLE ICR_ACCESS_PROFILE (
    PROFILE_ID    NUMBER        NOT NULL,
    PROFILE_CODE  VARCHAR2(40)  NOT NULL,
    PROFILE_NAME  VARCHAR2(100) NOT NULL,
    ACTIVE        NUMBER(1)     DEFAULT 1 NOT NULL,
    CONSTRAINT PK_ICR_ACCESS_PROFILE PRIMARY KEY (PROFILE_ID),
    CONSTRAINT UK_ICR_ACCESS_PROFILE_CODE UNIQUE (PROFILE_CODE)
);

CREATE TABLE ICR_MENU_ENTRY (
    MENU_CODE     VARCHAR2(60)  NOT NULL,
    PARENT_CODE   VARCHAR2(60),
    MENU_TYPE     VARCHAR2(20)  NOT NULL,  -- GROUP | ROUTE | LABEL
    MENU_MODE     VARCHAR2(10)  DEFAULT 'STANDARD' NOT NULL,  -- STANDARD | AI | ADMIN
    ROUTE_PATH    VARCHAR2(200),
    ICON_CLASS    VARCHAR2(80),
    LABEL_TEXT    VARCHAR2(120) NOT NULL,
    SORT_ORDER    NUMBER        DEFAULT 0 NOT NULL,
    EXPAND_KEY    VARCHAR2(40),
    ACTIVE        NUMBER(1)     DEFAULT 1 NOT NULL,
    CONSTRAINT PK_ICR_MENU_ENTRY PRIMARY KEY (MENU_CODE)
);

CREATE TABLE ICR_MENU_ACCESS_RULE (
    MENU_CODE   VARCHAR2(60) NOT NULL,
    FLAG_NAME   VARCHAR2(30) NOT NULL,  -- ALL | BUYER | HELPDESK | IT | DATAINTEGRITY | TECH | WAREHOUSE | SPACE | AIADMIN | AIDESIGNER | ADMIN
    CONSTRAINT PK_ICR_MENU_ACCESS_RULE PRIMARY KEY (MENU_CODE, FLAG_NAME),
    CONSTRAINT FK_ICR_MENU_RULE_ENTRY FOREIGN KEY (MENU_CODE) REFERENCES ICR_MENU_ENTRY (MENU_CODE)
);

CREATE TABLE ICR_PROFILE_MENU (
    PROFILE_ID  NUMBER       NOT NULL,
    MENU_CODE   VARCHAR2(60) NOT NULL,
    GRANTED     NUMBER(1)    DEFAULT 1 NOT NULL,
    CONSTRAINT PK_ICR_PROFILE_MENU PRIMARY KEY (PROFILE_ID, MENU_CODE),
    CONSTRAINT FK_ICR_PROFILE_MENU_PROF FOREIGN KEY (PROFILE_ID) REFERENCES ICR_ACCESS_PROFILE (PROFILE_ID),
    CONSTRAINT FK_ICR_PROFILE_MENU_ENTRY FOREIGN KEY (MENU_CODE) REFERENCES ICR_MENU_ENTRY (MENU_CODE)
);

CREATE INDEX IX_ICR_MENU_PARENT ON ICR_MENU_ENTRY (PARENT_CODE);
CREATE INDEX IX_ICR_MENU_MODE ON ICR_MENU_ENTRY (MENU_MODE);

*/

-- ── Seed data (re-runnable MERGE) ───────────────────────────────────────────

MERGE INTO ICR_ACCESS_PROFILE t
USING (
    SELECT 1 PROFILE_ID, 'FULL_IT' PROFILE_CODE, 'IT full access' PROFILE_NAME FROM dual UNION ALL
    SELECT 2, 'BUYER', 'Buyer' FROM dual UNION ALL
    SELECT 3, 'HELPDESK', 'Helpdesk' FROM dual UNION ALL
    SELECT 4, 'AI_DESIGNER', 'AI designer' FROM dual UNION ALL
    SELECT 5, 'AI_ADMIN', 'AI administrator' FROM dual UNION ALL
    SELECT 6, 'SPACE_PLANNING', 'Space planning team' FROM dual UNION ALL
    SELECT 7, 'TECH_SERVICES', 'Tech Services' FROM dual UNION ALL
    SELECT 8, 'DATA_INTEGRITY', 'Data Integrity' FROM dual
) s ON (t.PROFILE_ID = s.PROFILE_ID)
WHEN NOT MATCHED THEN INSERT (PROFILE_ID, PROFILE_CODE, PROFILE_NAME, ACTIVE)
VALUES (s.PROFILE_ID, s.PROFILE_CODE, s.PROFILE_NAME, 1);

-- Clear and reseed menu catalog + rules (dev-friendly)
DELETE FROM ICR_PROFILE_MENU;
DELETE FROM ICR_MENU_ACCESS_RULE;
DELETE FROM ICR_MENU_ENTRY;

-- Dashboard (always)
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE)
VALUES ('DASHBOARD', NULL, 'ROUTE', 'STANDARD', '/dashboard', 'fas fa-tachometer-alt', 'Dashboard', 10, NULL, 1);

-- Header actions — MENU_TYPE HEADER (SET0000041); not in sidebar tree (SET0000040 excludes HEADER)
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE)
VALUES ('HDR_AI_TOGGLE', NULL, 'HEADER', 'BOTH', NULL, 'fas fa-robot', 'AI mode toggle', 0, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE)
VALUES ('HDR_USER_PROFILE', NULL, 'HEADER', 'BOTH', NULL, 'fa fa-fw fa-user', 'Profile', 10, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE)
VALUES ('HDR_USER_CHANGE_PASSWORD', NULL, 'HEADER', 'BOTH', NULL, 'fa fa-fw fa-key', 'Change password', 20, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE)
VALUES ('HDR_USER_DOCUMENTATION', NULL, 'HEADER', 'BOTH', '/documentation', 'fa fa-fw fa-book', 'Documentation', 25, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE)
VALUES ('HDR_USER_INBOX', NULL, 'HEADER', 'BOTH', NULL, 'fa fa-fw fa-envelope', 'Inbox', 30, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE)
VALUES ('HDR_USER_SETTINGS', NULL, 'HEADER', 'BOTH', NULL, 'fa fa-fw fa-gear', 'Settings', 40, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE)
VALUES ('HDR_USER_SWITCH_MENU', NULL, 'HEADER', 'BOTH', NULL, 'fa fa-fw fa-bars', 'Switch Menu', 50, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE)
VALUES ('HDR_USER_LOGOUT', NULL, 'HEADER', 'BOTH', '/login', 'fa fa-fw fa-power-off', 'Log Out', 60, NULL, 1);

-- ── Standard menu groups ──────────────────────────────────────────────────────
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('GRP_INVENTORY', NULL, 'GROUP', 'STANDARD', NULL, 'fas fa-cubes', 'Inventory', 100, 'inventory', 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_INVENTORY', 'GRP_INVENTORY', 'ROUTE', 'STANDARD', '/inventory', 'fa fa-university', 'Inventory follow-up', 101, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_COUNTING', 'GRP_INVENTORY', 'ROUTE', 'STANDARD', '/counting', 'fa fa-university', 'Third-Party counting', 102, NULL, 1);

INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('GRP_CAO', NULL, 'GROUP', 'STANDARD', NULL, 'fas fa-robot', 'Computer Ordering', 110, 'caoconfig', 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_CAOCONFIG', 'GRP_CAO', 'ROUTE', 'STANDARD', '/caoconfig', 'fas fa-check-double', 'CAO setting', 111, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_CAOMISSING', 'GRP_CAO', 'ROUTE', 'STANDARD', '/caomissing', 'fas fa-frog', 'CAO missing', 112, NULL, 1);

INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('GRP_SCHEDULE', NULL, 'GROUP', 'STANDARD', NULL, 'fa fa-calendar', 'Supplier schedule', 120, 'supplierschedule', 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_HOLIDAY', 'GRP_SCHEDULE', 'ROUTE', 'STANDARD', '/holiday', 'fas fa-sun', 'Holiday schedule', 121, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_SCHEDULE', 'GRP_SCHEDULE', 'ROUTE', 'STANDARD', '/schedule', 'fas fa-calendar', 'Mgt by schedule', 122, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_GENSCHED', 'GRP_SCHEDULE', 'ROUTE', 'STANDARD', '/generateschedule', 'pi pi-slack', 'Generate schedule', 123, NULL, 1);

INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_SEARCH', NULL, 'ROUTE', 'STANDARD', '/search', 'fas fa-search', 'Search', 130, NULL, 1);

INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('GRP_SERVICES', NULL, 'GROUP', 'STANDARD', NULL, 'fas fa-brain', 'Master data', 140, 'masterdata', 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_PPGRETAIL', 'GRP_SERVICES', 'ROUTE', 'STANDARD', '/ppgretail', 'fas fa-money-check-dollar', 'Retail by PPG', 141, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_NEXTPPG', 'GRP_SERVICES', 'ROUTE', 'STANDARD', '/nextppg', 'fas fa-list-ol', 'Next PPG', 142, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_ECOMMDESC', 'GRP_SERVICES', 'ROUTE', 'STANDARD', '/ecommdesc', 'fas fa-film', 'eCommerce desc', 143, NULL, 1);

INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('GRP_SYNDIGO', NULL, 'GROUP', 'STANDARD', NULL, 'fas fa-barcode', 'Syndigo', 150, 'syndigo', 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_SYNDIGOSEARCH', 'GRP_SYNDIGO', 'ROUTE', 'STANDARD', '/syndigosearch', 'fas fa-search', 'Search', 151, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_SYNDIGOCOLLECT', 'GRP_SYNDIGO', 'ROUTE', 'STANDARD', '/syndigocollect', 'fas fa-camera', 'Collect', 152, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_SYNDIGOUPDATE', 'GRP_SYNDIGO', 'ROUTE', 'STANDARD', '/syndigoupdate', 'fas fa-wrench', 'Syndigo to MDM', 153, NULL, 1);

INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('GRP_SPACE', NULL, 'GROUP', 'STANDARD', NULL, 'fas fa-ruler-horizontal', 'Space Planning', 160, 'spaceplanning', 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_ECOMPIC', 'GRP_SPACE', 'ROUTE', 'STANDARD', '/ecommercepicture', 'fas fa-camera', 'E-commerce picture', 161, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_SPACEITEM', 'GRP_SPACE', 'ROUTE', 'STANDARD', '/spaceitemreporting', 'fas fa-timeline', 'Item history', 162, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_SPACEDIM', 'GRP_SPACE', 'ROUTE', 'STANDARD', '/spaceitemdimreporting', 'fas fa-circle-info', 'SKU information', 163, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_ITEMADDR', 'GRP_SPACE', 'ROUTE', 'STANDARD', '/itemaddress', 'fa fa-upload', 'Item address load', 164, NULL, 1);

INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('GRP_FINANCE', NULL, 'GROUP', 'STANDARD', NULL, 'fas fa-file-invoice', 'Account Payable', 170, 'finance', 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_UNARCHIVE', 'GRP_FINANCE', 'ROUTE', 'STANDARD', '/unarchiveinvoice', 'fas fa-cash-register', 'Unarchive', 171, NULL, 1);

INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('GRP_WAREHOUSE', NULL, 'GROUP', 'STANDARD', NULL, 'fas fa-warehouse', 'Warehouse box', 180, 'warehouse', 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_FIXPICK', 'GRP_WAREHOUSE', 'ROUTE', 'STANDARD', '/fixpickingunit', 'fas fa-tools', 'Fix Picking unit', 181, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_RELPLT', 'GRP_WAREHOUSE', 'ROUTE', 'STANDARD', '/releasepallet', 'fas fa-pallet', 'Release pallet', 182, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_PLTLBL', 'GRP_WAREHOUSE', 'ROUTE', 'STANDARD', '/palletlabel', 'fas fa-barcode', 'Pallet label', 183, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_PRODNUM', 'GRP_WAREHOUSE', 'ROUTE', 'STANDARD', '/productionnumber', 'fas fa-hashtag', 'Production number', 184, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_MFG_AGRN', 'GRP_WAREHOUSE', 'ROUTE', 'STANDARD', '/mfgagrn', 'fas fa-industry', 'Manufacturing AGRN', 185, NULL, 1);

INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('GRP_IT', NULL, 'GROUP', 'STANDARD', NULL, 'fas fa-chalkboard-teacher', 'I.T.', 190, 'batchschedule', 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_BATCH', 'GRP_IT', 'ROUTE', 'STANDARD', '/batchschedule', 'fas fa-tools', 'Batch processing', 191, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_VEGA', 'GRP_IT', 'ROUTE', 'STANDARD', '/vega', 'fas fa-lemon', 'Vega journal', 192, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_UNIX', 'GRP_IT', 'ROUTE', 'STANDARD', '/unixrunner', 'fas fa-terminal', 'Job execution', 193, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_QUERYRUN', 'GRP_IT', 'ROUTE', 'STANDARD', '/queryrunner', 'fas fa-database', 'Query execution', 194, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_PRESET', 'GRP_IT', 'ROUTE', 'STANDARD', '/presetquery', 'fas fa-sliders', 'Preset Query report', 195, NULL, 1);

INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('GRP_HELPDESK', NULL, 'GROUP', 'STANDARD', NULL, 'fa fa-desktop', 'Helpdesk', 200, 'robot', 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_ROBOT', 'GRP_HELPDESK', 'ROUTE', 'STANDARD', '/robot', 'fas fa-robot', 'Robot', 201, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_WHSRESTART', 'GRP_HELPDESK', 'ROUTE', 'STANDARD', '/whsrestartservices', 'fas fa-repeat', 'Warehouse all services', 202, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_SVCCENTER', 'GRP_HELPDESK', 'ROUTE', 'STANDARD', '/servicescenter', 'fas fa-repeat', 'Services center', 203, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_ORDERURG', 'GRP_HELPDESK', 'ROUTE', 'STANDARD', '/orderurgent', 'pi pi-slack', 'Order urgency', 204, NULL, 1);

INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('GRP_EDI', NULL, 'GROUP', 'STANDARD', NULL, 'fa fa-wifi', 'EDI', 210, 'edi', 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_EDIASN', 'GRP_EDI', 'ROUTE', 'STANDARD', '/ediasn', 'fas fa-truck-fast', 'Store ASN', 211, NULL, 1);

INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('GRP_HIERARCHY', NULL, 'GROUP', 'STANDARD', NULL, 'fas fa-sitemap', 'Hierarchy', 220, 'hierarchy', 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_AVAILMH', 'GRP_HIERARCHY', 'ROUTE', 'STANDARD', '/availableMH', 'fas fa-code-merge', 'Available node', 221, NULL, 1);

INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('GRP_MASS', NULL, 'GROUP', 'STANDARD', NULL, 'fas fa-chalkboard-teacher', 'Mass-change box', 230, 'massupdate', 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_MASSJOURNAL', 'GRP_MASS', 'ROUTE', 'STANDARD', '/massjournal', 'fas fa-clipboard-check', 'Journal', 231, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_ITEMHIER', 'GRP_MASS', 'ROUTE', 'STANDARD', '/itemhierarchy', 'fas fa-sitemap', 'Item Hierarchy', 232, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_ITEMDESC', 'GRP_MASS', 'ROUTE', 'STANDARD', '/itemdescription', 'fas fa-newspaper', 'Item description', 233, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_ITEMLISTDESC', 'GRP_MASS', 'ROUTE', 'STANDARD', '/itemlistdescription', 'fas fa-clipboard-list', 'Item List desc.', 234, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_CATMGR', 'GRP_MASS', 'ROUTE', 'STANDARD', '/categorymanager', 'fas fa-user', 'Category Mgr', 235, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_ITEMATTR', 'GRP_MASS', 'ROUTE', 'STANDARD', '/itemattribute', 'fas fa-list-ul', 'Item Attribute', 236, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_ITEMATTRDT', 'GRP_MASS', 'ROUTE', 'STANDARD', '/itemattributedated', 'fas fa-calendar', 'Item Attribute dated', 237, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_SVATTR', 'GRP_MASS', 'ROUTE', 'STANDARD', '/svattribute', 'fas fa-list', 'SV Attribute', 238, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_SVINFO', 'GRP_MASS', 'ROUTE', 'STANDARD', '/svinfo', 'fas fa-info', 'SV Info', 239, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_SKUDIM', 'GRP_MASS', 'ROUTE', 'STANDARD', '/skudimension', 'fas fa-ruler-combined', 'SKU dimension', 240, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_ITEMCHAR', 'GRP_MASS', 'ROUTE', 'STANDARD', '/itemcharacteristic', 'fas fa-tags', 'Item characteristic', 241, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_VARWT', 'GRP_MASS', 'ROUTE', 'STANDARD', '/variableweight', 'fas fa-weight', 'Variable weight', 242, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_LOGCODE', 'GRP_MASS', 'ROUTE', 'STANDARD', '/logisticcode', 'fas fa-barcode', 'Logistic code', 243, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_ITEMIMG', 'GRP_MASS', 'ROUTE', 'STANDARD', '/itemimages', 'fas fa-images', 'Item images', 244, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_SUPADDR', 'GRP_MASS', 'ROUTE', 'STANDARD', '/supplieraddress', 'fas fa-truck', 'Supplier address', 245, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_PO', 'GRP_MASS', 'ROUTE', 'STANDARD', '/purchaseorder', 'fas fa-file-invoice', 'Purchase order', 246, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_POPUSH', 'GRP_MASS', 'ROUTE', 'STANDARD', '/purchaseorderpush', 'fas fa-share', 'Push/Breakdown order', 247, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_STOCK', 'GRP_MASS', 'ROUTE', 'STANDARD', '/stocklayer', 'fas fa-layer-group', 'Stock layer', 248, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_ENDUPC', 'GRP_MASS', 'ROUTE', 'STANDARD', '/itemendupc', 'fa fa-trash', 'Papyrus UPC', 249, NULL, 1);

INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('GRP_REPORTING', NULL, 'GROUP', 'STANDARD', NULL, 'fas fa-bar-chart', 'Reporting box', 260, 'reporting', 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_SCORECAO', 'GRP_REPORTING', 'ROUTE', 'STANDARD', '/scorecardcao', 'fas fa-shopping-cart', 'Automatic Order', 261, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_DASHCYCLE', 'GRP_REPORTING', 'ROUTE', 'STANDARD', '/dashboardcycle', 'fas fa-shopping-cart', 'PI adjustment', 262, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_DASHSUPP', 'GRP_REPORTING', 'ROUTE', 'STANDARD', '/dashboardsupplier', 'fas fa-truck', 'Supplier service', 263, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_QUALWHS', 'GRP_REPORTING', 'ROUTE', 'STANDARD', '/qualitywhsreplenishment', 'fas fa-industry', 'Whs Repl.', 264, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_SMARTUBD', 'GRP_REPORTING', 'ROUTE', 'STANDARD', '/smartubd', 'pi pi-clock', 'Smart UBD', 265, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_DASHREC', 'GRP_REPORTING', 'ROUTE', 'STANDARD', '/dashboardreception', 'pi pi-download', 'AP Receiving', 266, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_FILLRATE', 'GRP_REPORTING', 'ROUTE', 'STANDARD', '/fillrate', 'fas fa-glass-water', 'DSD / Warehouse', 267, NULL, 1);

INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('GRP_TOOLS', NULL, 'GROUP', 'STANDARD', NULL, 'fas fa-toolbox', 'Tools', 268, 'tools', 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_BARCODE_GEN', 'GRP_TOOLS', 'ROUTE', 'STANDARD', '/barcodegenerator', 'fas fa-barcode', 'Barcode generator', 269, NULL, 1);

INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('GRP_ALERTS', NULL, 'GROUP', 'STANDARD', NULL, 'fas fa-bell', 'Alerts', 270, 'alertsicr', 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_ALERTJRNL', 'GRP_ALERTS', 'ROUTE', 'STANDARD', '/alerts-journal', 'fas fa-book', 'Journal', 271, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_ALERTWATCH', 'GRP_ALERTS', 'ROUTE', 'STANDARD', '/alerts-watch', 'fas fa-shield-alt', 'Watch dog', 272, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_ALERTMGT', 'GRP_ALERTS', 'ROUTE', 'STANDARD', '/alerts-icr', 'fas fa-bullhorn', 'Alerts management', 273, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_RPTFILTER', 'GRP_ALERTS', 'ROUTE', 'STANDARD', '/reportfilter', 'fas fa-filter', 'Filter config.', 274, NULL, 1);

-- ── Supply Chain AI (AI menu mode) ───────────────────────────────────────────
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('GRP_AI', NULL, 'GROUP', 'AI', NULL, 'fas fa-robot', 'Supply Chain AI', 300, 'supplyChainAI', 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('LBL_AI_PLATFORM', 'GRP_AI', 'LABEL', 'AI', NULL, NULL, 'Platform setup', 301, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_AI_RETAILER', 'GRP_AI', 'ROUTE', 'AI', '/ai/retailer-setup', 'fas fa-plug', 'Retailer & GOLD setup', 302, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_AI_SCHEMA', 'GRP_AI', 'ROUTE', 'AI', '/ai/schema-discovery', 'fas fa-database', 'Schema discovery', 303, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_AI_CONTEXT', 'GRP_AI', 'ROUTE', 'AI', '/ai/context-learning', 'fas fa-graduation-cap', 'Context learning', 304, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('LBL_AI_STUDIO', 'GRP_AI', 'LABEL', 'AI', NULL, NULL, 'Skill studio', 310, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_AI_LIB', 'GRP_AI', 'ROUTE', 'AI', '/ai/skill-studio/library', 'fas fa-layer-group', 'Template skill library', 311, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_AI_BUILDER', 'GRP_AI', 'ROUTE', 'AI', '/ai/skill-studio/builder', 'fas fa-tools', 'Skill builder', 312, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_AI_PENDING', 'GRP_AI', 'ROUTE', 'AI', '/ai/skill-studio/pending-phrasings', 'fas fa-comment-medical', 'Pending phrasings', 313, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_AI_PLAY', 'GRP_AI', 'ROUTE', 'AI', '/ai/skill-studio/playground', 'fas fa-flask', 'Phrasing playground', 314, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('LBL_AI_OPS', 'GRP_AI', 'LABEL', 'AI', NULL, NULL, 'Operations', 320, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_AI_HEALTH', 'GRP_AI', 'ROUTE', 'AI', '/ai/data-health', 'fas fa-heartbeat', 'Data health', 321, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_AI_HEALTHCFG', 'GRP_AI', 'ROUTE', 'AI', '/ai/data-health/config', 'fas fa-sliders-h', 'Health config', 322, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('LBL_AI_INQ', 'GRP_AI', 'LABEL', 'AI', NULL, NULL, 'Inquiry', 330, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_AI_ASST', 'GRP_AI', 'ROUTE', 'AI', '/ai/assistant', 'fas fa-comments', 'AI Assistant', 331, NULL, 1);

-- ── Admin settings (separate admin nav) ───────────────────────────────────────
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('GRP_SETTINGS', NULL, 'GROUP', 'ADMIN', NULL, 'fa fa-cogs', 'General Settings', 400, 'settings', 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_SET_CUST', 'GRP_SETTINGS', 'ROUTE', 'ADMIN', '/settingcustomer', 'fa fa-th-large', 'Retailer & Access', 401, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_SET_USERS', 'GRP_SETTINGS', 'ROUTE', 'ADMIN', '/settingusers', 'fa fa-user', 'Users & Profiles', 402, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_SET_WIDGET', 'GRP_SETTINGS', 'ROUTE', 'ADMIN', '/settingwidget', 'fa fa-chart-bar', 'Widget Library', 403, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_SET_QUERY', 'GRP_SETTINGS', 'ROUTE', 'ADMIN', '/settingquery', 'fa fa-share-square', 'Query Library', 404, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_SET_LABEL', 'GRP_SETTINGS', 'ROUTE', 'ADMIN', '/settinglabel', 'fa fa-flag', 'Dictionary', 405, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_SET_MENU', 'GRP_SETTINGS', 'ROUTE', 'ADMIN', '/settingmenu', 'fa fa-sitemap', 'Menu & access', 406, NULL, 1);
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE) VALUES ('ROUTE_APP_LOGS', 'GRP_SETTINGS', 'ROUTE', 'ADMIN', '/app-logs', 'fas fa-file-alt', 'App logs', 407, NULL, 1);

-- Access rules (OR across flags on same menu; PK = MENU_CODE + FLAG_NAME — no duplicate pairs)
-- Helper: insert only when (MENU_CODE, FLAG_NAME) not already present (safe for partial re-runs)

INSERT INTO ICR_MENU_ACCESS_RULE (MENU_CODE, FLAG_NAME)
SELECT 'DASHBOARD', 'ALL' FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM ICR_MENU_ACCESS_RULE r WHERE r.MENU_CODE = 'DASHBOARD' AND r.FLAG_NAME = 'ALL');

INSERT INTO ICR_MENU_ACCESS_RULE (MENU_CODE, FLAG_NAME)
SELECT 'GRP_TOOLS', 'ALL' FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM ICR_MENU_ACCESS_RULE r WHERE r.MENU_CODE = 'GRP_TOOLS' AND r.FLAG_NAME = 'ALL');
INSERT INTO ICR_MENU_ACCESS_RULE (MENU_CODE, FLAG_NAME)
SELECT 'ROUTE_BARCODE_GEN', 'ALL' FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM ICR_MENU_ACCESS_RULE r WHERE r.MENU_CODE = 'ROUTE_BARCODE_GEN' AND r.FLAG_NAME = 'ALL');

INSERT INTO ICR_MENU_ACCESS_RULE (MENU_CODE, FLAG_NAME)
SELECT 'HDR_AI_TOGGLE', 'AIADMIN' FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM ICR_MENU_ACCESS_RULE r WHERE r.MENU_CODE = 'HDR_AI_TOGGLE' AND r.FLAG_NAME = 'AIADMIN');
INSERT INTO ICR_MENU_ACCESS_RULE (MENU_CODE, FLAG_NAME)
SELECT 'HDR_AI_TOGGLE', 'AIDESIGNER' FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM ICR_MENU_ACCESS_RULE r WHERE r.MENU_CODE = 'HDR_AI_TOGGLE' AND r.FLAG_NAME = 'AIDESIGNER');

-- User profile dropdown (all authenticated users)
INSERT INTO ICR_MENU_ACCESS_RULE (MENU_CODE, FLAG_NAME)
SELECT 'HDR_USER_PROFILE', 'ALL' FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM ICR_MENU_ACCESS_RULE r WHERE r.MENU_CODE = 'HDR_USER_PROFILE' AND r.FLAG_NAME = 'ALL');
INSERT INTO ICR_MENU_ACCESS_RULE (MENU_CODE, FLAG_NAME)
SELECT 'HDR_USER_CHANGE_PASSWORD', 'ALL' FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM ICR_MENU_ACCESS_RULE r WHERE r.MENU_CODE = 'HDR_USER_CHANGE_PASSWORD' AND r.FLAG_NAME = 'ALL');
INSERT INTO ICR_MENU_ACCESS_RULE (MENU_CODE, FLAG_NAME)
SELECT 'HDR_USER_DOCUMENTATION', 'ALL' FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM ICR_MENU_ACCESS_RULE r WHERE r.MENU_CODE = 'HDR_USER_DOCUMENTATION' AND r.FLAG_NAME = 'ALL');
INSERT INTO ICR_MENU_ACCESS_RULE (MENU_CODE, FLAG_NAME)
SELECT 'HDR_USER_INBOX', 'ALL' FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM ICR_MENU_ACCESS_RULE r WHERE r.MENU_CODE = 'HDR_USER_INBOX' AND r.FLAG_NAME = 'ALL');
INSERT INTO ICR_MENU_ACCESS_RULE (MENU_CODE, FLAG_NAME)
SELECT 'HDR_USER_SETTINGS', 'ALL' FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM ICR_MENU_ACCESS_RULE r WHERE r.MENU_CODE = 'HDR_USER_SETTINGS' AND r.FLAG_NAME = 'ALL');
INSERT INTO ICR_MENU_ACCESS_RULE (MENU_CODE, FLAG_NAME)
SELECT 'HDR_USER_SWITCH_MENU', 'ALL' FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM ICR_MENU_ACCESS_RULE r WHERE r.MENU_CODE = 'HDR_USER_SWITCH_MENU' AND r.FLAG_NAME = 'ALL');
INSERT INTO ICR_MENU_ACCESS_RULE (MENU_CODE, FLAG_NAME)
SELECT 'HDR_USER_LOGOUT', 'ALL' FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM ICR_MENU_ACCESS_RULE r WHERE r.MENU_CODE = 'HDR_USER_LOGOUT' AND r.FLAG_NAME = 'ALL');

-- BUYER
INSERT INTO ICR_MENU_ACCESS_RULE (MENU_CODE, FLAG_NAME)
SELECT m.MENU_CODE, 'BUYER'
  FROM ICR_MENU_ENTRY m
 WHERE m.MENU_CODE IN (
   'GRP_INVENTORY','ROUTE_INVENTORY','ROUTE_COUNTING',
   'GRP_CAO','ROUTE_CAOCONFIG','ROUTE_CAOMISSING','ROUTE_SEARCH',
   'GRP_REPORTING','ROUTE_SCORECAO','ROUTE_DASHCYCLE','ROUTE_DASHSUPP','ROUTE_QUALWHS','ROUTE_SMARTUBD','ROUTE_DASHREC','ROUTE_FILLRATE',
   'GRP_ALERTS','ROUTE_ALERTJRNL','ROUTE_ALERTWATCH','ROUTE_ALERTMGT','ROUTE_RPTFILTER'
 )
   AND NOT EXISTS (SELECT 1 FROM ICR_MENU_ACCESS_RULE r WHERE r.MENU_CODE = m.MENU_CODE AND r.FLAG_NAME = 'BUYER');

-- HELPDESK
INSERT INTO ICR_MENU_ACCESS_RULE (MENU_CODE, FLAG_NAME)
SELECT m.MENU_CODE, 'HELPDESK'
  FROM ICR_MENU_ENTRY m
 WHERE m.MENU_CODE IN (
   'GRP_INVENTORY','ROUTE_INVENTORY','ROUTE_COUNTING',
   'GRP_CAO','ROUTE_CAOCONFIG','ROUTE_CAOMISSING',
   'GRP_SCHEDULE','ROUTE_HOLIDAY','ROUTE_SCHEDULE','ROUTE_GENSCHED','ROUTE_SEARCH',
   'GRP_SERVICES','ROUTE_PPGRETAIL','ROUTE_NEXTPPG','ROUTE_ECOMMDESC',
   'GRP_SYNDIGO','ROUTE_SYNDIGOSEARCH','ROUTE_SYNDIGOCOLLECT','ROUTE_SYNDIGOUPDATE',
   'GRP_FINANCE','ROUTE_UNARCHIVE',
   'GRP_WAREHOUSE','ROUTE_FIXPICK','ROUTE_RELPLT','ROUTE_PLTLBL','ROUTE_PRODNUM','ROUTE_MFG_AGRN',
   'GRP_IT','ROUTE_BATCH','ROUTE_VEGA','ROUTE_UNIX','ROUTE_QUERYRUN','ROUTE_PRESET',
   'GRP_HELPDESK','ROUTE_ROBOT','ROUTE_WHSRESTART','ROUTE_SVCCENTER','ROUTE_ORDERURG',
   'GRP_EDI','ROUTE_EDIASN',
   'GRP_REPORTING','ROUTE_SCORECAO','ROUTE_DASHCYCLE','ROUTE_DASHSUPP','ROUTE_QUALWHS','ROUTE_SMARTUBD','ROUTE_DASHREC','ROUTE_FILLRATE',
   'GRP_ALERTS','ROUTE_ALERTJRNL','ROUTE_ALERTWATCH','ROUTE_ALERTMGT','ROUTE_RPTFILTER'
 )
   AND NOT EXISTS (SELECT 1 FROM ICR_MENU_ACCESS_RULE r WHERE r.MENU_CODE = m.MENU_CODE AND r.FLAG_NAME = 'HELPDESK');

-- DATAINTEGRITY (broad + mass-change-only routes)
INSERT INTO ICR_MENU_ACCESS_RULE (MENU_CODE, FLAG_NAME)
SELECT m.MENU_CODE, 'DATAINTEGRITY'
  FROM ICR_MENU_ENTRY m
 WHERE m.MENU_CODE IN (
   'GRP_INVENTORY','ROUTE_INVENTORY','ROUTE_COUNTING',
   'GRP_CAO','ROUTE_CAOCONFIG','ROUTE_CAOMISSING','ROUTE_SEARCH',
   'GRP_SERVICES','ROUTE_PPGRETAIL','ROUTE_NEXTPPG','ROUTE_ECOMMDESC',
   'GRP_SYNDIGO','ROUTE_SYNDIGOSEARCH','ROUTE_SYNDIGOCOLLECT','ROUTE_SYNDIGOUPDATE',
   'GRP_FINANCE','ROUTE_UNARCHIVE',
   'GRP_WAREHOUSE','ROUTE_FIXPICK','ROUTE_RELPLT','ROUTE_PLTLBL','ROUTE_PRODNUM','ROUTE_MFG_AGRN',
   'GRP_IT','ROUTE_BATCH','ROUTE_VEGA','ROUTE_UNIX','ROUTE_QUERYRUN','ROUTE_PRESET',
   'GRP_HIERARCHY','ROUTE_AVAILMH','GRP_MASS','ROUTE_MASSJOURNAL',
   'ROUTE_ITEMHIER','ROUTE_ITEMDESC','ROUTE_ITEMLISTDESC','ROUTE_CATMGR','ROUTE_ITEMATTR','ROUTE_ITEMATTRDT',
   'ROUTE_SVATTR','ROUTE_SVINFO','ROUTE_SKUDIM','ROUTE_ITEMCHAR','ROUTE_VARWT','ROUTE_LOGCODE','ROUTE_ITEMIMG',
   'ROUTE_SUPADDR','ROUTE_PO','ROUTE_POPUSH','ROUTE_STOCK','ROUTE_ENDUPC',
   'GRP_REPORTING','ROUTE_SCORECAO','ROUTE_DASHCYCLE','ROUTE_DASHSUPP','ROUTE_QUALWHS','ROUTE_SMARTUBD','ROUTE_DASHREC','ROUTE_FILLRATE',
   'GRP_ALERTS','ROUTE_ALERTJRNL','ROUTE_ALERTWATCH','ROUTE_ALERTMGT','ROUTE_RPTFILTER'
 )
   AND NOT EXISTS (SELECT 1 FROM ICR_MENU_ACCESS_RULE r WHERE r.MENU_CODE = m.MENU_CODE AND r.FLAG_NAME = 'DATAINTEGRITY');

-- Profile DATA_INTEGRITY (USERPROF = 8) — same menu set as USERDATAINTEGRITY flag
INSERT INTO ICR_PROFILE_MENU (PROFILE_ID, MENU_CODE, GRANTED)
SELECT 8, m.MENU_CODE, 1
  FROM ICR_MENU_ENTRY m
 WHERE m.MENU_CODE IN (
   'DASHBOARD','ROUTE_SEARCH',
   'GRP_INVENTORY','ROUTE_INVENTORY','ROUTE_COUNTING',
   'GRP_CAO','ROUTE_CAOCONFIG','ROUTE_CAOMISSING',
   'GRP_SERVICES','ROUTE_PPGRETAIL','ROUTE_NEXTPPG','ROUTE_ECOMMDESC',
   'GRP_SYNDIGO','ROUTE_SYNDIGOSEARCH','ROUTE_SYNDIGOCOLLECT','ROUTE_SYNDIGOUPDATE',
   'GRP_FINANCE','ROUTE_UNARCHIVE',
   'GRP_WAREHOUSE','ROUTE_FIXPICK','ROUTE_RELPLT','ROUTE_PLTLBL','ROUTE_PRODNUM','ROUTE_MFG_AGRN',
   'GRP_IT','ROUTE_BATCH','ROUTE_VEGA','ROUTE_UNIX','ROUTE_QUERYRUN','ROUTE_PRESET',
   'GRP_HIERARCHY','ROUTE_AVAILMH','GRP_MASS','ROUTE_MASSJOURNAL',
   'ROUTE_ITEMHIER','ROUTE_ITEMDESC','ROUTE_ITEMLISTDESC','ROUTE_CATMGR','ROUTE_ITEMATTR','ROUTE_ITEMATTRDT',
   'ROUTE_SVATTR','ROUTE_SVINFO','ROUTE_SKUDIM','ROUTE_ITEMCHAR','ROUTE_VARWT','ROUTE_LOGCODE','ROUTE_ITEMIMG',
   'ROUTE_SUPADDR','ROUTE_PO','ROUTE_POPUSH','ROUTE_STOCK','ROUTE_ENDUPC',
   'GRP_REPORTING','ROUTE_SCORECAO','ROUTE_DASHCYCLE','ROUTE_DASHSUPP','ROUTE_QUALWHS','ROUTE_SMARTUBD','ROUTE_DASHREC','ROUTE_FILLRATE',
   'GRP_ALERTS','ROUTE_ALERTJRNL','ROUTE_ALERTWATCH','ROUTE_ALERTMGT','ROUTE_RPTFILTER'
 )
   AND NOT EXISTS (
         SELECT 1 FROM ICR_PROFILE_MENU pm
          WHERE pm.PROFILE_ID = 8 AND pm.MENU_CODE = m.MENU_CODE
       );

-- IT
INSERT INTO ICR_MENU_ACCESS_RULE (MENU_CODE, FLAG_NAME)
SELECT m.MENU_CODE, 'IT'
  FROM ICR_MENU_ENTRY m
 WHERE m.MENU_CODE IN (
   'GRP_INVENTORY','ROUTE_INVENTORY','ROUTE_COUNTING',
   'GRP_CAO','ROUTE_CAOCONFIG','ROUTE_CAOMISSING','ROUTE_SEARCH',
   'GRP_SERVICES','ROUTE_PPGRETAIL','ROUTE_NEXTPPG','ROUTE_ECOMMDESC',
   'GRP_SYNDIGO','ROUTE_SYNDIGOSEARCH','ROUTE_SYNDIGOCOLLECT','ROUTE_SYNDIGOUPDATE',
   'GRP_FINANCE','ROUTE_UNARCHIVE',
   'GRP_WAREHOUSE','ROUTE_FIXPICK','ROUTE_RELPLT','ROUTE_PLTLBL','ROUTE_PRODNUM','ROUTE_MFG_AGRN',
   'GRP_IT','ROUTE_BATCH','ROUTE_VEGA','ROUTE_UNIX','ROUTE_QUERYRUN','ROUTE_PRESET',
   'GRP_REPORTING','ROUTE_SCORECAO','ROUTE_DASHCYCLE','ROUTE_DASHSUPP','ROUTE_QUALWHS','ROUTE_SMARTUBD','ROUTE_DASHREC','ROUTE_FILLRATE',
   'GRP_ALERTS','ROUTE_ALERTJRNL','ROUTE_ALERTWATCH','ROUTE_ALERTMGT','ROUTE_RPTFILTER'
 )
   AND NOT EXISTS (SELECT 1 FROM ICR_MENU_ACCESS_RULE r WHERE r.MENU_CODE = m.MENU_CODE AND r.FLAG_NAME = 'IT');

-- TECH (USERSTECH — Tech Services: IT tooling + schedules + reporting)
INSERT INTO ICR_MENU_ACCESS_RULE (MENU_CODE, FLAG_NAME)
SELECT m.MENU_CODE, 'TECH'
  FROM ICR_MENU_ENTRY m
 WHERE m.MENU_CODE IN (
   'ROUTE_SEARCH',
   'GRP_SCHEDULE','ROUTE_HOLIDAY','ROUTE_SCHEDULE','ROUTE_GENSCHED',
   'GRP_IT','ROUTE_BATCH','ROUTE_VEGA','ROUTE_UNIX','ROUTE_QUERYRUN','ROUTE_PRESET',
   'GRP_HIERARCHY','ROUTE_AVAILMH',
   'GRP_REPORTING','ROUTE_SCORECAO','ROUTE_DASHCYCLE','ROUTE_DASHSUPP','ROUTE_QUALWHS','ROUTE_SMARTUBD','ROUTE_DASHREC','ROUTE_FILLRATE',
   'GRP_ALERTS','ROUTE_ALERTJRNL','ROUTE_ALERTWATCH','ROUTE_ALERTMGT','ROUTE_RPTFILTER'
 )
   AND NOT EXISTS (SELECT 1 FROM ICR_MENU_ACCESS_RULE r WHERE r.MENU_CODE = m.MENU_CODE AND r.FLAG_NAME = 'TECH');

-- SPACE (legacy: spaceplanning==1 → Space Planning + Master data + Syndigo + Search)
INSERT INTO ICR_MENU_ACCESS_RULE (MENU_CODE, FLAG_NAME)
SELECT m.MENU_CODE, 'SPACE'
  FROM ICR_MENU_ENTRY m
 WHERE m.MENU_CODE IN (
   'ROUTE_SEARCH',
   'GRP_SERVICES','ROUTE_PPGRETAIL','ROUTE_NEXTPPG','ROUTE_ECOMMDESC',
   'GRP_SYNDIGO','ROUTE_SYNDIGOSEARCH','ROUTE_SYNDIGOCOLLECT','ROUTE_SYNDIGOUPDATE',
   'GRP_SPACE','ROUTE_ECOMPIC','ROUTE_SPACEITEM','ROUTE_SPACEDIM','ROUTE_ITEMADDR'
 )
   AND NOT EXISTS (SELECT 1 FROM ICR_MENU_ACCESS_RULE r WHERE r.MENU_CODE = m.MENU_CODE AND r.FLAG_NAME = 'SPACE');

-- Profile SPACE_PLANNING (USERPROF = 6) — same menu set as USERSPACEPLANNING flag
INSERT INTO ICR_PROFILE_MENU (PROFILE_ID, MENU_CODE, GRANTED)
SELECT 6, m.MENU_CODE, 1
  FROM ICR_MENU_ENTRY m
 WHERE m.MENU_CODE IN (
   'DASHBOARD','ROUTE_SEARCH',
   'GRP_SERVICES','ROUTE_PPGRETAIL','ROUTE_NEXTPPG','ROUTE_ECOMMDESC',
   'GRP_SYNDIGO','ROUTE_SYNDIGOSEARCH','ROUTE_SYNDIGOCOLLECT','ROUTE_SYNDIGOUPDATE',
   'GRP_SPACE','ROUTE_ECOMPIC','ROUTE_SPACEITEM','ROUTE_SPACEDIM','ROUTE_ITEMADDR'
 )
   AND NOT EXISTS (
         SELECT 1 FROM ICR_PROFILE_MENU pm
          WHERE pm.PROFILE_ID = 6 AND pm.MENU_CODE = m.MENU_CODE
       );

-- WAREHOUSE
INSERT INTO ICR_MENU_ACCESS_RULE (MENU_CODE, FLAG_NAME)
SELECT m.MENU_CODE, 'WAREHOUSE'
  FROM ICR_MENU_ENTRY m
 WHERE m.MENU_CODE IN ('GRP_WAREHOUSE','ROUTE_FIXPICK','ROUTE_RELPLT','ROUTE_PLTLBL','ROUTE_PRODNUM','ROUTE_MFG_AGRN','GRP_HIERARCHY','ROUTE_AVAILMH','GRP_MASS','ROUTE_MASSJOURNAL')
   AND NOT EXISTS (SELECT 1 FROM ICR_MENU_ACCESS_RULE r WHERE r.MENU_CODE = m.MENU_CODE AND r.FLAG_NAME = 'WAREHOUSE');

-- AI menus
INSERT INTO ICR_MENU_ACCESS_RULE (MENU_CODE, FLAG_NAME)
SELECT m.MENU_CODE, 'AIADMIN'
  FROM ICR_MENU_ENTRY m
 WHERE m.MENU_MODE = 'AI'
   AND NOT EXISTS (SELECT 1 FROM ICR_MENU_ACCESS_RULE r WHERE r.MENU_CODE = m.MENU_CODE AND r.FLAG_NAME = 'AIADMIN');

INSERT INTO ICR_MENU_ACCESS_RULE (MENU_CODE, FLAG_NAME)
SELECT m.MENU_CODE, 'AIDESIGNER'
  FROM ICR_MENU_ENTRY m
 WHERE m.MENU_MODE = 'AI'
   AND m.MENU_CODE NOT IN ('ROUTE_AI_RETAILER','ROUTE_AI_SCHEMA','ROUTE_AI_CONTEXT','ROUTE_AI_HEALTHCFG')
   AND NOT EXISTS (SELECT 1 FROM ICR_MENU_ACCESS_RULE r WHERE r.MENU_CODE = m.MENU_CODE AND r.FLAG_NAME = 'AIDESIGNER');

-- Admin settings — ADMIN flag (USERTYPE = 1 on USERSROOM, same as legacy sidebar)
INSERT INTO ICR_MENU_ACCESS_RULE (MENU_CODE, FLAG_NAME)
SELECT m.MENU_CODE, 'ADMIN'
  FROM ICR_MENU_ENTRY m
 WHERE m.MENU_MODE = 'ADMIN'
   AND NOT EXISTS (SELECT 1 FROM ICR_MENU_ACCESS_RULE r WHERE r.MENU_CODE = m.MENU_CODE AND r.FLAG_NAME = 'ADMIN');

COMMIT;

-- ── LIBQUERY ──────────────────────────────────────────────────────────────────

DELETE FROM LIBQUERY WHERE QUERYNUM IN (
    'SET0000040','SET0000041','SET0000042','SET0000043','SET0000044','SET0000045'
);

-- SET0000040 — Effective menu for logged-in user (sidebar + route guard)
INSERT INTO LIBQUERY (QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'SET0000040',
       'Menu - effective for user',
       'Granted menu nodes for USERID :param1. Profile grants OR legacy flag rules.',
       q'~
SELECT m.MENU_CODE, m.PARENT_CODE, m.MENU_TYPE, m.MENU_MODE, m.ROUTE_PATH,
       m.ICON_CLASS, m.LABEL_TEXT, m.SORT_ORDER, m.EXPAND_KEY
  FROM ICR_MENU_ENTRY m
  JOIN USERSROOM u ON u.USERID = :param1
 WHERE m.ACTIVE = 1
   AND m.MENU_TYPE <> 'HEADER'
   AND (
         EXISTS (
           SELECT 1 FROM ICR_MENU_ACCESS_RULE r
            WHERE r.MENU_CODE = m.MENU_CODE
              AND (
                    r.FLAG_NAME = 'ALL'
                 OR (r.FLAG_NAME = 'BUYER'          AND NVL(u.USERBUYER, 0) = 1)
                 OR (r.FLAG_NAME = 'HELPDESK'       AND NVL(u.USERHELPDESK, 0) = 1)
                 OR (r.FLAG_NAME = 'IT'             AND NVL(u.USERIT, 0) = 1)
                 OR (r.FLAG_NAME = 'DATAINTEGRITY' AND NVL(u.USERDATAINTEGRITY, 0) = 1)
                 OR (r.FLAG_NAME = 'TECH'            AND NVL(u.USERSTECH, 0) = 1)
                 OR (r.FLAG_NAME = 'WAREHOUSE'      AND NVL(u.USERWAREHOUSE, 0) = 1)
                 OR (r.FLAG_NAME = 'SPACE'          AND NVL(u.USERSPACEPLANNING, 0) = 1)
                 OR (r.FLAG_NAME = 'AIADMIN'        AND NVL(u.USERAIADMIN, 0) = 1)
                 OR (r.FLAG_NAME = 'AIDESIGNER'     AND NVL(u.USERAIDESIGNER, 0) = 1)
                 OR (r.FLAG_NAME = 'ADMIN'          AND NVL(u.USERTYPE, 0) = 1)
              )
         )
         OR (
           u.USERPROF IS NOT NULL
           AND EXISTS (
             SELECT 1 FROM ICR_PROFILE_MENU pm
              WHERE pm.PROFILE_ID = u.USERPROF
                AND pm.MENU_CODE = m.MENU_CODE
                AND pm.GRANTED = 1
           )
         )
       )
 ORDER BY m.SORT_ORDER, m.LABEL_TEXT
~',
       ':param1=user_id',
       'MENU_CODE,PARENT_CODE,MENU_TYPE,MENU_MODE,ROUTE_PATH,ICON_CLASS,LABEL_TEXT,SORT_ORDER,EXPAND_KEY',
       1, 0, 0 FROM dual;

-- SET0000041 — Header actions (AI toggle + user profile dropdown)
INSERT INTO LIBQUERY (QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'SET0000041',
       'Menu - header actions for user',
       'HEADER menu rows for USERID :param1 (toolbar + profile dropdown).',
       q'~
SELECT m.MENU_CODE, m.LABEL_TEXT, m.ICON_CLASS, m.ROUTE_PATH, m.SORT_ORDER
  FROM ICR_MENU_ENTRY m
  JOIN USERSROOM u ON u.USERID = :param1
 WHERE m.ACTIVE = 1
   AND m.MENU_TYPE = 'HEADER'
   AND (
         EXISTS (
           SELECT 1 FROM ICR_MENU_ACCESS_RULE r
            WHERE r.MENU_CODE = m.MENU_CODE
              AND (
                    r.FLAG_NAME = 'ALL'
                 OR (r.FLAG_NAME = 'BUYER'          AND NVL(u.USERBUYER, 0) = 1)
                 OR (r.FLAG_NAME = 'HELPDESK'       AND NVL(u.USERHELPDESK, 0) = 1)
                 OR (r.FLAG_NAME = 'IT'             AND NVL(u.USERIT, 0) = 1)
                 OR (r.FLAG_NAME = 'DATAINTEGRITY' AND NVL(u.USERDATAINTEGRITY, 0) = 1)
                 OR (r.FLAG_NAME = 'TECH'            AND NVL(u.USERSTECH, 0) = 1)
                 OR (r.FLAG_NAME = 'WAREHOUSE'      AND NVL(u.USERWAREHOUSE, 0) = 1)
                 OR (r.FLAG_NAME = 'SPACE'          AND NVL(u.USERSPACEPLANNING, 0) = 1)
                 OR (r.FLAG_NAME = 'AIADMIN'        AND NVL(u.USERAIADMIN, 0) = 1)
                 OR (r.FLAG_NAME = 'AIDESIGNER'     AND NVL(u.USERAIDESIGNER, 0) = 1)
                 OR (r.FLAG_NAME = 'ADMIN'          AND NVL(u.USERTYPE, 0) = 1)
              )
         )
         OR (
           u.USERPROF IS NOT NULL
           AND EXISTS (
             SELECT 1 FROM ICR_PROFILE_MENU pm
              WHERE pm.PROFILE_ID = u.USERPROF
                AND pm.MENU_CODE = m.MENU_CODE
                AND pm.GRANTED = 1
           )
         )
       )
 ORDER BY m.SORT_ORDER, m.LABEL_TEXT
~',
       ':param1=user_id',
       'MENU_CODE,LABEL_TEXT,ICON_CLASS,ROUTE_PATH,SORT_ORDER',
       1, 0, 0 FROM dual;

-- SET0000042 — Access profiles list (dropdown)
INSERT INTO LIBQUERY (QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'SET0000042',
       'Menu - profile list',
       'Active access profiles.',
       q'~SELECT PROFILE_ID, PROFILE_CODE, PROFILE_NAME FROM ICR_ACCESS_PROFILE WHERE ACTIVE = 1 ORDER BY PROFILE_NAME~',
       ':param1=placeholder',
       'PROFILE_ID,PROFILE_CODE,PROFILE_NAME',
       0, 0, 0 FROM dual;

-- SET0000043 — Full menu catalog (admin)
INSERT INTO LIBQUERY (QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'SET0000043',
       'Menu - catalog',
       'All active menu entries.',
       q'~SELECT MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY
  FROM ICR_MENU_ENTRY WHERE ACTIVE = 1 ORDER BY SORT_ORDER~',
       ':param1=placeholder',
       'MENU_CODE,PARENT_CODE,MENU_TYPE,MENU_MODE,ROUTE_PATH,ICON_CLASS,LABEL_TEXT,SORT_ORDER,EXPAND_KEY',
       0, 0, 0 FROM dual;

-- SET0000044 — Profile menu grants
INSERT INTO LIBQUERY (QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'SET0000044',
       'Menu - profile grants',
       'Menu codes granted to profile :param1.',
       q'~SELECT pm.MENU_CODE, pm.GRANTED, m.LABEL_TEXT, m.MENU_MODE
  FROM ICR_PROFILE_MENU pm
  JOIN ICR_MENU_ENTRY m ON m.MENU_CODE = pm.MENU_CODE
 WHERE pm.PROFILE_ID = TO_NUMBER(:param1)
 ORDER BY m.SORT_ORDER~',
       ':param1=profile_id',
       'MENU_CODE,GRANTED,LABEL_TEXT,MENU_MODE',
       0, 0, 0 FROM dual;

-- SET0000045 — MERGE profile menu grant
INSERT INTO LIBQUERY (QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'SET0000045',
       'Menu - profile grant MERGE',
       'Body {values:[{PROFILE_ID,MENU_CODE,GRANTED}]}.',
       q'~
MERGE INTO ICR_PROFILE_MENU tgt
USING (
  SELECT TO_NUMBER(jt.PROFILE_ID) PROFILE_ID, jt.MENU_CODE, NVL(TO_NUMBER(jt.GRANTED), 1) GRANTED
    FROM REQUEST_QUERY_BODY rb,
         JSON_TABLE(rb.REQUESTBODY, '$.values[0]'
           COLUMNS (
             PROFILE_ID VARCHAR2(20) PATH '$."PROFILE_ID"',
             MENU_CODE  VARCHAR2(60) PATH '$."MENU_CODE"',
             GRANTED    VARCHAR2(5)  PATH '$."GRANTED"'
           )
         ) jt
   WHERE rb.REQUESTID = :param1
) src
ON (tgt.PROFILE_ID = src.PROFILE_ID AND tgt.MENU_CODE = src.MENU_CODE)
WHEN MATCHED THEN UPDATE SET tgt.GRANTED = src.GRANTED
WHEN NOT MATCHED THEN INSERT (PROFILE_ID, MENU_CODE, GRANTED)
VALUES (src.PROFILE_ID, src.MENU_CODE, src.GRANTED)
~',
       ':param1=REQUESTID',
       '',
       0, 0, 1 FROM dual;

COMMIT;

-- ── Incremental patch: Space planning (DBs that already ran 35 — no menu DELETE) ─
MERGE INTO ICR_ACCESS_PROFILE t
USING (SELECT 6 PROFILE_ID, 'SPACE_PLANNING' PROFILE_CODE, 'Space planning team' PROFILE_NAME FROM dual) s
ON (t.PROFILE_ID = s.PROFILE_ID)
WHEN NOT MATCHED THEN INSERT (PROFILE_ID, PROFILE_CODE, PROFILE_NAME, ACTIVE)
VALUES (s.PROFILE_ID, s.PROFILE_CODE, s.PROFILE_NAME, 1);

INSERT INTO ICR_MENU_ACCESS_RULE (MENU_CODE, FLAG_NAME)
SELECT m.MENU_CODE, 'SPACE'
  FROM ICR_MENU_ENTRY m
 WHERE m.MENU_CODE IN (
   'ROUTE_SEARCH',
   'GRP_SERVICES','ROUTE_PPGRETAIL','ROUTE_NEXTPPG','ROUTE_ECOMMDESC',
   'GRP_SYNDIGO','ROUTE_SYNDIGOSEARCH','ROUTE_SYNDIGOCOLLECT','ROUTE_SYNDIGOUPDATE',
   'GRP_SPACE','ROUTE_ECOMPIC','ROUTE_SPACEITEM','ROUTE_SPACEDIM','ROUTE_ITEMADDR'
 )
   AND NOT EXISTS (SELECT 1 FROM ICR_MENU_ACCESS_RULE r WHERE r.MENU_CODE = m.MENU_CODE AND r.FLAG_NAME = 'SPACE');

INSERT INTO ICR_PROFILE_MENU (PROFILE_ID, MENU_CODE, GRANTED)
SELECT 6, m.MENU_CODE, 1
  FROM ICR_MENU_ENTRY m
 WHERE m.MENU_CODE IN (
   'DASHBOARD','ROUTE_SEARCH',
   'GRP_SERVICES','ROUTE_PPGRETAIL','ROUTE_NEXTPPG','ROUTE_ECOMMDESC',
   'GRP_SYNDIGO','ROUTE_SYNDIGOSEARCH','ROUTE_SYNDIGOCOLLECT','ROUTE_SYNDIGOUPDATE',
   'GRP_SPACE','ROUTE_ECOMPIC','ROUTE_SPACEITEM','ROUTE_SPACEDIM','ROUTE_ITEMADDR'
 )
   AND NOT EXISTS (
         SELECT 1 FROM ICR_PROFILE_MENU pm
          WHERE pm.PROFILE_ID = 6 AND pm.MENU_CODE = m.MENU_CODE
       );

-- Enable space menus for bkiewel (set flag and/or access profile 6):
-- UPDATE USERSROOM SET USERSPACEPLANNING = 1, USERPROF = 6 WHERE USERID = 'bkiewel';
-- COMMIT;

UPDATE ICR_MENU_ENTRY SET ICON_CLASS = 'fas fa-search' WHERE MENU_CODE = 'ROUTE_SEARCH';

-- TECH_SERVICES + DATA_INTEGRITY profiles (DBs that already ran script 35)
MERGE INTO ICR_ACCESS_PROFILE t
USING (
    SELECT 7 PROFILE_ID, 'TECH_SERVICES' PROFILE_CODE, 'Tech Services' PROFILE_NAME FROM dual UNION ALL
    SELECT 8, 'DATA_INTEGRITY', 'Data Integrity' FROM dual
) s ON (t.PROFILE_ID = s.PROFILE_ID)
WHEN NOT MATCHED THEN INSERT (PROFILE_ID, PROFILE_CODE, PROFILE_NAME, ACTIVE)
VALUES (s.PROFILE_ID, s.PROFILE_CODE, s.PROFILE_NAME, 1);

INSERT INTO ICR_MENU_ACCESS_RULE (MENU_CODE, FLAG_NAME)
SELECT m.MENU_CODE, 'TECH'
  FROM ICR_MENU_ENTRY m
 WHERE m.MENU_CODE IN (
   'ROUTE_SEARCH',
   'GRP_SCHEDULE','ROUTE_HOLIDAY','ROUTE_SCHEDULE','ROUTE_GENSCHED',
   'GRP_IT','ROUTE_BATCH','ROUTE_VEGA','ROUTE_UNIX','ROUTE_QUERYRUN','ROUTE_PRESET',
   'GRP_HIERARCHY','ROUTE_AVAILMH',
   'GRP_REPORTING','ROUTE_SCORECAO','ROUTE_DASHCYCLE','ROUTE_DASHSUPP','ROUTE_QUALWHS','ROUTE_SMARTUBD','ROUTE_DASHREC','ROUTE_FILLRATE',
   'GRP_ALERTS','ROUTE_ALERTJRNL','ROUTE_ALERTWATCH','ROUTE_ALERTMGT','ROUTE_RPTFILTER'
 )
   AND NOT EXISTS (SELECT 1 FROM ICR_MENU_ACCESS_RULE r WHERE r.MENU_CODE = m.MENU_CODE AND r.FLAG_NAME = 'TECH');

INSERT INTO ICR_PROFILE_MENU (PROFILE_ID, MENU_CODE, GRANTED)
SELECT 7, m.MENU_CODE, 1
  FROM ICR_MENU_ENTRY m
 WHERE m.MENU_CODE IN (
   'DASHBOARD','ROUTE_SEARCH',
   'GRP_SCHEDULE','ROUTE_HOLIDAY','ROUTE_SCHEDULE','ROUTE_GENSCHED',
   'GRP_IT','ROUTE_BATCH','ROUTE_VEGA','ROUTE_UNIX','ROUTE_QUERYRUN','ROUTE_PRESET',
   'GRP_HIERARCHY','ROUTE_AVAILMH',
   'GRP_REPORTING','ROUTE_SCORECAO','ROUTE_DASHCYCLE','ROUTE_DASHSUPP','ROUTE_QUALWHS','ROUTE_SMARTUBD','ROUTE_DASHREC','ROUTE_FILLRATE',
   'GRP_ALERTS','ROUTE_ALERTJRNL','ROUTE_ALERTWATCH','ROUTE_ALERTMGT','ROUTE_RPTFILTER'
 )
   AND NOT EXISTS (
         SELECT 1 FROM ICR_PROFILE_MENU pm
          WHERE pm.PROFILE_ID = 7 AND pm.MENU_CODE = m.MENU_CODE
       );

INSERT INTO ICR_PROFILE_MENU (PROFILE_ID, MENU_CODE, GRANTED)
SELECT 8, m.MENU_CODE, 1
  FROM ICR_MENU_ENTRY m
 WHERE m.MENU_CODE IN (
   'DASHBOARD','ROUTE_SEARCH',
   'GRP_INVENTORY','ROUTE_INVENTORY','ROUTE_COUNTING',
   'GRP_CAO','ROUTE_CAOCONFIG','ROUTE_CAOMISSING',
   'GRP_SERVICES','ROUTE_PPGRETAIL','ROUTE_NEXTPPG','ROUTE_ECOMMDESC',
   'GRP_SYNDIGO','ROUTE_SYNDIGOSEARCH','ROUTE_SYNDIGOCOLLECT','ROUTE_SYNDIGOUPDATE',
   'GRP_FINANCE','ROUTE_UNARCHIVE',
   'GRP_WAREHOUSE','ROUTE_FIXPICK','ROUTE_RELPLT','ROUTE_PLTLBL','ROUTE_PRODNUM','ROUTE_MFG_AGRN',
   'GRP_IT','ROUTE_BATCH','ROUTE_VEGA','ROUTE_UNIX','ROUTE_QUERYRUN','ROUTE_PRESET',
   'GRP_HIERARCHY','ROUTE_AVAILMH','GRP_MASS','ROUTE_MASSJOURNAL',
   'ROUTE_ITEMHIER','ROUTE_ITEMDESC','ROUTE_ITEMLISTDESC','ROUTE_CATMGR','ROUTE_ITEMATTR','ROUTE_ITEMATTRDT',
   'ROUTE_SVATTR','ROUTE_SVINFO','ROUTE_SKUDIM','ROUTE_ITEMCHAR','ROUTE_VARWT','ROUTE_LOGCODE','ROUTE_ITEMIMG',
   'ROUTE_SUPADDR','ROUTE_PO','ROUTE_POPUSH','ROUTE_STOCK','ROUTE_ENDUPC',
   'GRP_REPORTING','ROUTE_SCORECAO','ROUTE_DASHCYCLE','ROUTE_DASHSUPP','ROUTE_QUALWHS','ROUTE_SMARTUBD','ROUTE_DASHREC','ROUTE_FILLRATE',
   'GRP_ALERTS','ROUTE_ALERTJRNL','ROUTE_ALERTWATCH','ROUTE_ALERTMGT','ROUTE_RPTFILTER'
 )
   AND NOT EXISTS (
         SELECT 1 FROM ICR_PROFILE_MENU pm
          WHERE pm.PROFILE_ID = 8 AND pm.MENU_CODE = m.MENU_CODE
       );

-- Re-deploy SET0000040 so USERSTECH (TECH flag) is honored on existing DBs
DELETE FROM LIBQUERY WHERE QUERYNUM = 'SET0000040';

INSERT INTO LIBQUERY (QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'SET0000040',
       'Menu - effective for user',
       'Granted menu nodes for USERID :param1. Profile grants OR legacy flag rules.',
       q'~
SELECT m.MENU_CODE, m.PARENT_CODE, m.MENU_TYPE, m.MENU_MODE, m.ROUTE_PATH,
       m.ICON_CLASS, m.LABEL_TEXT, m.SORT_ORDER, m.EXPAND_KEY
  FROM ICR_MENU_ENTRY m
  JOIN USERSROOM u ON u.USERID = :param1
 WHERE m.ACTIVE = 1
   AND m.MENU_TYPE <> 'HEADER'
   AND (
         EXISTS (
           SELECT 1 FROM ICR_MENU_ACCESS_RULE r
            WHERE r.MENU_CODE = m.MENU_CODE
              AND (
                    r.FLAG_NAME = 'ALL'
                 OR (r.FLAG_NAME = 'BUYER'          AND NVL(u.USERBUYER, 0) = 1)
                 OR (r.FLAG_NAME = 'HELPDESK'       AND NVL(u.USERHELPDESK, 0) = 1)
                 OR (r.FLAG_NAME = 'IT'             AND NVL(u.USERIT, 0) = 1)
                 OR (r.FLAG_NAME = 'DATAINTEGRITY' AND NVL(u.USERDATAINTEGRITY, 0) = 1)
                 OR (r.FLAG_NAME = 'TECH'            AND NVL(u.USERSTECH, 0) = 1)
                 OR (r.FLAG_NAME = 'WAREHOUSE'      AND NVL(u.USERWAREHOUSE, 0) = 1)
                 OR (r.FLAG_NAME = 'SPACE'          AND NVL(u.USERSPACEPLANNING, 0) = 1)
                 OR (r.FLAG_NAME = 'AIADMIN'        AND NVL(u.USERAIADMIN, 0) = 1)
                 OR (r.FLAG_NAME = 'AIDESIGNER'     AND NVL(u.USERAIDESIGNER, 0) = 1)
                 OR (r.FLAG_NAME = 'ADMIN'          AND NVL(u.USERTYPE, 0) = 1)
              )
         )
         OR (
           u.USERPROF IS NOT NULL
           AND EXISTS (
             SELECT 1 FROM ICR_PROFILE_MENU pm
              WHERE pm.PROFILE_ID = u.USERPROF
                AND pm.MENU_CODE = m.MENU_CODE
                AND pm.GRANTED = 1
           )
         )
       )
 ORDER BY m.SORT_ORDER, m.LABEL_TEXT
~',
       ':param1=user_id',
       'MENU_CODE,PARENT_CODE,MENU_TYPE,MENU_MODE,ROUTE_PATH,ICON_CLASS,LABEL_TEXT,SORT_ORDER,EXPAND_KEY',
       1, 0, 0 FROM dual;

-- App logs (General Settings) — existing DBs that already ran script 35
MERGE INTO ICR_MENU_ENTRY t
USING (
  SELECT 'ROUTE_APP_LOGS' AS MENU_CODE, 'GRP_SETTINGS' AS PARENT_CODE, 'ROUTE' AS MENU_TYPE,
         'ADMIN' AS MENU_MODE, '/app-logs' AS ROUTE_PATH, 'fas fa-file-alt' AS ICON_CLASS,
         'App logs' AS LABEL_TEXT, 407 AS SORT_ORDER, NULL AS EXPAND_KEY, 1 AS ACTIVE
    FROM dual
) s ON (t.MENU_CODE = s.MENU_CODE)
WHEN MATCHED THEN UPDATE SET
  t.PARENT_CODE = s.PARENT_CODE, t.MENU_TYPE = s.MENU_TYPE, t.MENU_MODE = s.MENU_MODE,
  t.ROUTE_PATH = s.ROUTE_PATH, t.ICON_CLASS = s.ICON_CLASS, t.LABEL_TEXT = s.LABEL_TEXT,
  t.SORT_ORDER = s.SORT_ORDER, t.ACTIVE = s.ACTIVE
WHEN NOT MATCHED THEN INSERT (
  MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE
) VALUES (
  s.MENU_CODE, s.PARENT_CODE, s.MENU_TYPE, s.MENU_MODE, s.ROUTE_PATH,
  s.ICON_CLASS, s.LABEL_TEXT, s.SORT_ORDER, s.EXPAND_KEY, s.ACTIVE
);

INSERT INTO ICR_MENU_ACCESS_RULE (MENU_CODE, FLAG_NAME)
SELECT 'ROUTE_APP_LOGS', 'ADMIN' FROM dual
 WHERE NOT EXISTS (
       SELECT 1 FROM ICR_MENU_ACCESS_RULE r
        WHERE r.MENU_CODE = 'ROUTE_APP_LOGS' AND r.FLAG_NAME = 'ADMIN'
 );

INSERT INTO ICR_MENU_ACCESS_RULE (MENU_CODE, FLAG_NAME)
SELECT 'ROUTE_APP_LOGS', 'IT' FROM dual
 WHERE NOT EXISTS (
       SELECT 1 FROM ICR_MENU_ACCESS_RULE r
        WHERE r.MENU_CODE = 'ROUTE_APP_LOGS' AND r.FLAG_NAME = 'IT'
 );

INSERT INTO ICR_PROFILE_MENU (PROFILE_ID, MENU_CODE, GRANTED)
SELECT 1, 'ROUTE_APP_LOGS', 1 FROM dual
 WHERE NOT EXISTS (
       SELECT 1 FROM ICR_PROFILE_MENU pm
        WHERE pm.PROFILE_ID = 1 AND pm.MENU_CODE = 'ROUTE_APP_LOGS'
 );

COMMIT;
