-- Menu & access admin CRUD — deploy after 35_menu_access_libquery.sql
-- LIBQUERY SET0000046–SET0000054 (reads + DML for ICR menu catalog, rules, profiles)

DELETE FROM LIBQUERY WHERE QUERYNUM IN (
    'SET0000046','SET0000047','SET0000048','SET0000049',
    'SET0000050','SET0000051','SET0000052','SET0000053','SET0000054'
);

-- SET0000046 — Menu catalog (admin; include inactive)
INSERT INTO LIBQUERY (QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'SET0000046',
       'Menu admin - catalog',
       'All menu rows. :param1=ACTIVE filter (-1=all, 0/1).',
       q'~SELECT MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS,
       LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE
  FROM ICR_MENU_ENTRY
 WHERE (:param1 = '-1' OR ACTIVE = TO_NUMBER(:param1))
 ORDER BY SORT_ORDER, MENU_CODE~',
       ':param1=active_filter',
       'MENU_CODE,PARENT_CODE,MENU_TYPE,MENU_MODE,ROUTE_PATH,ICON_CLASS,LABEL_TEXT,SORT_ORDER,EXPAND_KEY,ACTIVE',
       0, 0, 0 FROM dual;

-- SET0000047 — MERGE menu entry
INSERT INTO LIBQUERY (QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'SET0000047',
       'Menu admin - entry MERGE',
       'Body {values:[{MENU_CODE,PARENT_CODE,MENU_TYPE,MENU_MODE,ROUTE_PATH,ICON_CLASS,LABEL_TEXT,SORT_ORDER,EXPAND_KEY,ACTIVE}]}.',
       q'~
MERGE INTO ICR_MENU_ENTRY tgt
USING (
  SELECT jt.MENU_CODE,
         NULLIF(TRIM(jt.PARENT_CODE), '') PARENT_CODE,
         jt.MENU_TYPE, jt.MENU_MODE,
         NULLIF(TRIM(jt.ROUTE_PATH), '') ROUTE_PATH,
         NULLIF(TRIM(jt.ICON_CLASS), '') ICON_CLASS,
         jt.LABEL_TEXT,
         NVL(TO_NUMBER(jt.SORT_ORDER), 0) SORT_ORDER,
         NULLIF(TRIM(jt.EXPAND_KEY), '') EXPAND_KEY,
         NVL(TO_NUMBER(jt.ACTIVE), 1) ACTIVE
    FROM REQUEST_QUERY_BODY rb,
         JSON_TABLE(rb.REQUESTBODY, '$.values[0]'
           COLUMNS (
             MENU_CODE   VARCHAR2(60)  PATH '$."MENU_CODE"',
             PARENT_CODE VARCHAR2(60)  PATH '$."PARENT_CODE"',
             MENU_TYPE   VARCHAR2(20)  PATH '$."MENU_TYPE"',
             MENU_MODE   VARCHAR2(10)  PATH '$."MENU_MODE"',
             ROUTE_PATH  VARCHAR2(200) PATH '$."ROUTE_PATH"',
             ICON_CLASS  VARCHAR2(80)  PATH '$."ICON_CLASS"',
             LABEL_TEXT  VARCHAR2(120) PATH '$."LABEL_TEXT"',
             SORT_ORDER  VARCHAR2(10)  PATH '$."SORT_ORDER"',
             EXPAND_KEY  VARCHAR2(40)  PATH '$."EXPAND_KEY"',
             ACTIVE      VARCHAR2(5)   PATH '$."ACTIVE"'
           )
         ) jt
   WHERE rb.REQUESTID = :param1
) src
ON (tgt.MENU_CODE = src.MENU_CODE)
WHEN MATCHED THEN UPDATE SET
  tgt.PARENT_CODE = src.PARENT_CODE, tgt.MENU_TYPE = src.MENU_TYPE, tgt.MENU_MODE = src.MENU_MODE,
  tgt.ROUTE_PATH = src.ROUTE_PATH, tgt.ICON_CLASS = src.ICON_CLASS, tgt.LABEL_TEXT = src.LABEL_TEXT,
  tgt.SORT_ORDER = src.SORT_ORDER, tgt.EXPAND_KEY = src.EXPAND_KEY, tgt.ACTIVE = src.ACTIVE
WHEN NOT MATCHED THEN INSERT (
  MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE)
VALUES (src.MENU_CODE, src.PARENT_CODE, src.MENU_TYPE, src.MENU_MODE, src.ROUTE_PATH, src.ICON_CLASS,
        src.LABEL_TEXT, src.SORT_ORDER, src.EXPAND_KEY, src.ACTIVE)
~',
       ':param1=REQUESTID',
       '',
       0, 0, 1 FROM dual;

-- SET0000048 — Deactivate menu entry (soft delete)
INSERT INTO LIBQUERY (QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'SET0000048',
       'Menu admin - entry deactivate',
       'Body {values:[{MENU_CODE}]}. Sets ACTIVE=0.',
       q'~
UPDATE ICR_MENU_ENTRY
   SET ACTIVE = 0
 WHERE MENU_CODE = (
       SELECT jt.MENU_CODE
         FROM REQUEST_QUERY_BODY rb,
              JSON_TABLE(rb.REQUESTBODY, '$.values[0]'
                COLUMNS (MENU_CODE VARCHAR2(60) PATH '$."MENU_CODE"')) jt
        WHERE rb.REQUESTID = :param1
       )
~',
       ':param1=REQUESTID',
       '',
       0, 0, 1 FROM dual;

-- SET0000049 — List access rules
INSERT INTO LIBQUERY (QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'SET0000049',
       'Menu admin - access rules list',
       'All menu/flag rules.',
       q'~SELECT r.MENU_CODE, r.FLAG_NAME, m.LABEL_TEXT, m.MENU_MODE, m.MENU_TYPE
  FROM ICR_MENU_ACCESS_RULE r
  JOIN ICR_MENU_ENTRY m ON m.MENU_CODE = r.MENU_CODE
 ORDER BY r.FLAG_NAME, m.SORT_ORDER, r.MENU_CODE~',
       ':param1=placeholder',
       'MENU_CODE,FLAG_NAME,LABEL_TEXT,MENU_MODE,MENU_TYPE',
       0, 0, 0 FROM dual;

-- SET0000050 — Insert access rule
INSERT INTO LIBQUERY (QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'SET0000050',
       'Menu admin - access rule insert',
       'Body {values:[{MENU_CODE,FLAG_NAME}]}.',
       q'~
INSERT INTO ICR_MENU_ACCESS_RULE (MENU_CODE, FLAG_NAME)
SELECT jt.MENU_CODE, jt.FLAG_NAME
  FROM REQUEST_QUERY_BODY rb,
       JSON_TABLE(rb.REQUESTBODY, '$.values[0]'
         COLUMNS (
           MENU_CODE VARCHAR2(60) PATH '$."MENU_CODE"',
           FLAG_NAME VARCHAR2(30) PATH '$."FLAG_NAME"'
         )
       ) jt
 WHERE rb.REQUESTID = :param1
   AND NOT EXISTS (
         SELECT 1 FROM ICR_MENU_ACCESS_RULE r
          WHERE r.MENU_CODE = jt.MENU_CODE AND r.FLAG_NAME = jt.FLAG_NAME
       )
~',
       ':param1=REQUESTID',
       '',
       0, 0, 1 FROM dual;

-- SET0000051 — Delete access rule
INSERT INTO LIBQUERY (QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'SET0000051',
       'Menu admin - access rule delete',
       'Body {values:[{MENU_CODE,FLAG_NAME}]}.',
       q'~
DELETE FROM ICR_MENU_ACCESS_RULE r
 WHERE EXISTS (
       SELECT 1
         FROM REQUEST_QUERY_BODY rb,
              JSON_TABLE(rb.REQUESTBODY, '$.values[0]'
                COLUMNS (
                  MENU_CODE VARCHAR2(60) PATH '$."MENU_CODE"',
                  FLAG_NAME VARCHAR2(30) PATH '$."FLAG_NAME"'
                )
              ) jt
        WHERE rb.REQUESTID = :param1
          AND r.MENU_CODE = jt.MENU_CODE
          AND r.FLAG_NAME = jt.FLAG_NAME
       )
~',
       ':param1=REQUESTID',
       '',
       0, 0, 1 FROM dual;

-- SET0000052 — MERGE access profile
INSERT INTO LIBQUERY (QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'SET0000052',
       'Menu admin - profile MERGE',
       'Body {values:[{PROFILE_ID,PROFILE_CODE,PROFILE_NAME,ACTIVE}]}.',
       q'~
MERGE INTO ICR_ACCESS_PROFILE tgt
USING (
  SELECT TO_NUMBER(jt.PROFILE_ID) PROFILE_ID, jt.PROFILE_CODE, jt.PROFILE_NAME,
         NVL(TO_NUMBER(jt.ACTIVE), 1) ACTIVE
    FROM REQUEST_QUERY_BODY rb,
         JSON_TABLE(rb.REQUESTBODY, '$.values[0]'
           COLUMNS (
             PROFILE_ID   VARCHAR2(20)  PATH '$."PROFILE_ID"',
             PROFILE_CODE VARCHAR2(40)  PATH '$."PROFILE_CODE"',
             PROFILE_NAME VARCHAR2(100) PATH '$."PROFILE_NAME"',
             ACTIVE       VARCHAR2(5)   PATH '$."ACTIVE"'
           )
         ) jt
   WHERE rb.REQUESTID = :param1
) src
ON (tgt.PROFILE_ID = src.PROFILE_ID)
WHEN MATCHED THEN UPDATE SET
  tgt.PROFILE_CODE = src.PROFILE_CODE, tgt.PROFILE_NAME = src.PROFILE_NAME, tgt.ACTIVE = src.ACTIVE
WHEN NOT MATCHED THEN INSERT (PROFILE_ID, PROFILE_CODE, PROFILE_NAME, ACTIVE)
VALUES (src.PROFILE_ID, src.PROFILE_CODE, src.PROFILE_NAME, src.ACTIVE)
~',
       ':param1=REQUESTID',
       '',
       0, 0, 1 FROM dual;

-- SET0000053 — Next profile id
INSERT INTO LIBQUERY (QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'SET0000053',
       'Menu admin - next profile id',
       'MAX(PROFILE_ID)+1 for new profiles.',
       q'~SELECT NVL(MAX(PROFILE_ID), 0) + 1 AS NEXT_PROFILE_ID FROM ICR_ACCESS_PROFILE~',
       ':param1=placeholder',
       'NEXT_PROFILE_ID',
       0, 0, 0 FROM dual;

-- SET0000054 — Replace all grants for a profile (bulk save)
INSERT INTO LIBQUERY (QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'SET0000054',
       'Menu admin - profile menus replace',
       'Body {values:[{PROFILE_ID,MENU_CODES}]}. MENU_CODES = comma-separated MENU_CODE list (granted).',
       q'~
DECLARE
  v_prof NUMBER;
  v_codes VARCHAR2(4000);
BEGIN
  SELECT TO_NUMBER(jt.PROFILE_ID), jt.MENU_CODES
    INTO v_prof, v_codes
    FROM REQUEST_QUERY_BODY rb,
         JSON_TABLE(rb.REQUESTBODY, '$.values[0]'
           COLUMNS (
             PROFILE_ID VARCHAR2(20)  PATH '$."PROFILE_ID"',
             MENU_CODES VARCHAR2(4000) PATH '$."MENU_CODES"'
           )
         ) jt
   WHERE rb.REQUESTID = :param1;

  DELETE FROM ICR_PROFILE_MENU WHERE PROFILE_ID = v_prof;

  IF v_codes IS NOT NULL AND TRIM(v_codes) IS NOT NULL THEN
    INSERT INTO ICR_PROFILE_MENU (PROFILE_ID, MENU_CODE, GRANTED)
    SELECT v_prof, TRIM(REGEXP_SUBSTR(v_codes, '[^,]+', 1, LEVEL)), 1
      FROM dual
     CONNECT BY REGEXP_SUBSTR(v_codes, '[^,]+', 1, LEVEL) IS NOT NULL;
  END IF;
END;
~',
       ':param1=REQUESTID',
       '',
       0, 0, 1 FROM dual;

COMMIT;

-- Admin screen route (General Settings submenu)
INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE)
SELECT 'ROUTE_SET_MENU', 'GRP_SETTINGS', 'ROUTE', 'ADMIN', '/settingmenu', 'fa fa-sitemap', 'Menu & access', 406, NULL, 1
  FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM ICR_MENU_ENTRY e WHERE e.MENU_CODE = 'ROUTE_SET_MENU');

INSERT INTO ICR_MENU_ACCESS_RULE (MENU_CODE, FLAG_NAME)
SELECT 'ROUTE_SET_MENU', 'ADMIN' FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM ICR_MENU_ACCESS_RULE r WHERE r.MENU_CODE = 'ROUTE_SET_MENU' AND r.FLAG_NAME = 'ADMIN');

INSERT INTO ICR_PROFILE_MENU (PROFILE_ID, MENU_CODE, GRANTED)
SELECT 1, 'ROUTE_SET_MENU', 1 FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM ICR_PROFILE_MENU pm WHERE pm.PROFILE_ID = 1 AND pm.MENU_CODE = 'ROUTE_SET_MENU');

INSERT INTO ICR_MENU_ENTRY (MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE)
SELECT 'ROUTE_APP_LOGS', 'GRP_SETTINGS', 'ROUTE', 'ADMIN', '/app-logs', 'fas fa-file-alt', 'App logs', 407, NULL, 1
  FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM ICR_MENU_ENTRY e WHERE e.MENU_CODE = 'ROUTE_APP_LOGS');

INSERT INTO ICR_MENU_ACCESS_RULE (MENU_CODE, FLAG_NAME)
SELECT 'ROUTE_APP_LOGS', 'ADMIN' FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM ICR_MENU_ACCESS_RULE r WHERE r.MENU_CODE = 'ROUTE_APP_LOGS' AND r.FLAG_NAME = 'ADMIN');

INSERT INTO ICR_MENU_ACCESS_RULE (MENU_CODE, FLAG_NAME)
SELECT 'ROUTE_APP_LOGS', 'IT' FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM ICR_MENU_ACCESS_RULE r WHERE r.MENU_CODE = 'ROUTE_APP_LOGS' AND r.FLAG_NAME = 'IT');

INSERT INTO ICR_PROFILE_MENU (PROFILE_ID, MENU_CODE, GRANTED)
SELECT 1, 'ROUTE_APP_LOGS', 1 FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM ICR_PROFILE_MENU pm WHERE pm.PROFILE_ID = 1 AND pm.MENU_CODE = 'ROUTE_APP_LOGS');

COMMIT;
