-- =============================================================================
-- 49_data_health_resolution_upgrade.sql
-- Data Health — resolution / fix configuration on AI_DATA_CHECK_DEF
-- Deploy after: 29_data_health_libquery.sql (tables + base LIBQUERY must exist)
-- Re-runnable: ADD COLUMN ignores ORA-01430; LIBQUERY uses DELETE+INSERT.
-- =============================================================================

-- ── DDL: optional resolution LIBQUERY + param map + fixable row filter ───────
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE AI_DATA_CHECK_DEF ADD (RESOLUTION_QUERY_NUM VARCHAR2(20))';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE AI_DATA_CHECK_DEF ADD (RESOLUTION_PARAM_MAP VARCHAR2(500))';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE AI_DATA_CHECK_DEF ADD (FIXABLE_STATUS_COLUMN VARCHAR2(100))';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE AI_DATA_CHECK_DEF ADD (FIXABLE_STATUS_VALUE VARCHAR2(200))';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

COMMENT ON COLUMN AI_DATA_CHECK_DEF.RESOLUTION_QUERY_NUM IS
  'LIBQUERY id (QUERYUPDATE=1) executed on Fix; binds from row via RESOLUTION_PARAM_MAP → POST body keys.';
COMMENT ON COLUMN AI_DATA_CHECK_DEF.RESOLUTION_PARAM_MAP IS
  'Comma-separated detail-query column names → :param order in resolution LIBQUERY JSON_TABLE (e.g. STORE,UPC,TRANSFER DATE).';
COMMENT ON COLUMN AI_DATA_CHECK_DEF.FIXABLE_STATUS_COLUMN IS
  'Optional detail column name; when set with FIXABLE_STATUS_VALUE, only matching rows show Fix.';
COMMENT ON COLUMN AI_DATA_CHECK_DEF.FIXABLE_STATUS_VALUE IS
  'Optional value for FIXABLE_STATUS_COLUMN (e.g. Not processed). Case-insensitive trim match.';

-- ── Refresh LIBQUERY reads/writes that touch AI_DATA_CHECK_DEF ───────────────
DELETE FROM LIBQUERY WHERE QUERYNUM IN ('AI0000080', 'AI0000085', 'AI0000086', 'AI0000087');

-- AI0000080 — checks with latest result (add resolution columns)
INSERT INTO LIBQUERY (
    QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE
)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'AI0000080',
       'S24 — checks with latest result',
       'Active check definitions joined to most-recent AI_DATA_CHECK_RESULT. :param1=retailer_id, :param2=tier or ALL.',
       q'~
SELECT
  d.CHECK_ID,
  d.CHECK_CODE,
  d.CHECK_NAME,
  d.CHECK_DESCRIPTION,
  d.QUERY_NUM,
  d.TIER,
  d.SEVERITY,
  d.ENABLED,
  d.SKILL_CODE,
  d.ENTITY_KEY,
  d.DISPLAY_ORDER,
  d.RESOLUTION_QUERY_NUM,
  d.RESOLUTION_PARAM_MAP,
  d.FIXABLE_STATUS_COLUMN,
  d.FIXABLE_STATUS_VALUE,
  r.ISSUE_COUNT,
  r.RUN_AT     AS LAST_RUN_AT,
  r.STATUS,
  r.TREND
FROM AI_DATA_CHECK_DEF d
LEFT JOIN (
  SELECT r1.*
  FROM AI_DATA_CHECK_RESULT r1
  WHERE r1.RUN_AT = (
    SELECT MAX(r2.RUN_AT)
    FROM AI_DATA_CHECK_RESULT r2
    WHERE r2.CHECK_ID    = r1.CHECK_ID
      AND r2.RETAILER_ID = r1.RETAILER_ID
  )
) r ON r.CHECK_ID = d.CHECK_ID AND r.RETAILER_ID = :param1
WHERE d.RETAILER_ID = :param1
  AND (:param2 = 'ALL' OR d.TIER = :param2)
ORDER BY d.DISPLAY_ORDER, d.CHECK_CODE
~',
       ':param1=retailer_id, :param2=tier (ALL|REALTIME|HOURLY|NIGHTLY)',
       'CHECK_ID,CHECK_CODE,CHECK_NAME,CHECK_DESCRIPTION,QUERY_NUM,TIER,SEVERITY,ENABLED,SKILL_CODE,ENTITY_KEY,DISPLAY_ORDER,RESOLUTION_QUERY_NUM,RESOLUTION_PARAM_MAP,FIXABLE_STATUS_COLUMN,FIXABLE_STATUS_VALUE,ISSUE_COUNT,LAST_RUN_AT,STATUS,TREND',
       1, 0, 0
  FROM dual;

-- AI0000085 — list definitions for retailer
INSERT INTO LIBQUERY (
    QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE
)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'AI0000085',
       'S25 — check definitions for retailer',
       'All AI_DATA_CHECK_DEF rows for the given retailer (includes disabled). :param1=retailer_id.',
       q'~
SELECT
  CHECK_ID,
  CHECK_CODE,
  CHECK_NAME,
  CHECK_DESCRIPTION,
  QUERY_NUM,
  TIER,
  SEVERITY,
  ENABLED,
  RETAILER_ID,
  SKILL_CODE,
  ENTITY_KEY,
  DISPLAY_ORDER,
  RESOLUTION_QUERY_NUM,
  RESOLUTION_PARAM_MAP,
  FIXABLE_STATUS_COLUMN,
  FIXABLE_STATUS_VALUE,
  CREATED_AT,
  UPDATED_AT
FROM AI_DATA_CHECK_DEF
WHERE RETAILER_ID = :param1
ORDER BY DISPLAY_ORDER, CHECK_CODE
~',
       ':param1=retailer_id',
       'CHECK_ID,CHECK_CODE,CHECK_NAME,CHECK_DESCRIPTION,QUERY_NUM,TIER,SEVERITY,ENABLED,RETAILER_ID,SKILL_CODE,ENTITY_KEY,DISPLAY_ORDER,RESOLUTION_QUERY_NUM,RESOLUTION_PARAM_MAP,FIXABLE_STATUS_COLUMN,FIXABLE_STATUS_VALUE,CREATED_AT,UPDATED_AT',
       1, 0, 0
  FROM dual;

-- AI0000086 — single definition by CHECK_ID
INSERT INTO LIBQUERY (
    QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE
)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'AI0000086',
       'S25 — check definition by id',
       'Single AI_DATA_CHECK_DEF row. :param1=check_id.',
       q'~
SELECT
  CHECK_ID, CHECK_CODE, CHECK_NAME, CHECK_DESCRIPTION,
  QUERY_NUM, TIER, SEVERITY, ENABLED,
  RETAILER_ID, SKILL_CODE, ENTITY_KEY, DISPLAY_ORDER,
  RESOLUTION_QUERY_NUM, RESOLUTION_PARAM_MAP,
  FIXABLE_STATUS_COLUMN, FIXABLE_STATUS_VALUE
FROM AI_DATA_CHECK_DEF
WHERE CHECK_ID = :param1
~',
       ':param1=check_id',
       'CHECK_ID,CHECK_CODE,CHECK_NAME,CHECK_DESCRIPTION,QUERY_NUM,TIER,SEVERITY,ENABLED,RETAILER_ID,SKILL_CODE,ENTITY_KEY,DISPLAY_ORDER,RESOLUTION_QUERY_NUM,RESOLUTION_PARAM_MAP,FIXABLE_STATUS_COLUMN,FIXABLE_STATUS_VALUE',
       1, 0, 0
  FROM dual;

-- AI0000087 — upsert check definition (includes resolution fields)
INSERT INTO LIBQUERY (
    QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE
)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'AI0000087',
       'S25 — upsert check definition',
       'MERGE into AI_DATA_CHECK_DEF on CHECK_CODE+RETAILER_ID. Body: {values:[{CHECK_CODE,...}]}.',
       q'~
MERGE INTO AI_DATA_CHECK_DEF tgt
USING (
  SELECT
    jt.CHECK_CODE,
    jt.CHECK_NAME,
    jt.CHECK_DESCRIPTION,
    jt.QUERY_NUM,
    jt.TIER,
    jt.SEVERITY,
    jt.ENABLED,
    jt.RETAILER_ID,
    jt.SKILL_CODE,
    jt.ENTITY_KEY,
    jt.DISPLAY_ORDER,
    jt.RESOLUTION_QUERY_NUM,
    jt.RESOLUTION_PARAM_MAP,
    jt.FIXABLE_STATUS_COLUMN,
    jt.FIXABLE_STATUS_VALUE
  FROM REQUEST_QUERY_BODY rb,
       JSON_TABLE(rb.REQUESTBODY, '$.values[0]'
         COLUMNS (
           CHECK_CODE              VARCHAR2(50)   PATH '$."CHECK_CODE"',
           CHECK_NAME              VARCHAR2(200)  PATH '$."CHECK_NAME"',
           CHECK_DESCRIPTION       VARCHAR2(500)  PATH '$."CHECK_DESCRIPTION"',
           QUERY_NUM               VARCHAR2(20)   PATH '$."QUERY_NUM"',
           TIER                    VARCHAR2(20)   PATH '$."TIER"',
           SEVERITY                VARCHAR2(20)   PATH '$."SEVERITY"',
           ENABLED                 NUMBER         PATH '$."ENABLED"',
           RETAILER_ID             VARCHAR2(50)   PATH '$."RETAILER_ID"',
           SKILL_CODE              VARCHAR2(100)  PATH '$."SKILL_CODE"',
           ENTITY_KEY              VARCHAR2(100)  PATH '$."ENTITY_KEY"',
           DISPLAY_ORDER           NUMBER         PATH '$."DISPLAY_ORDER"',
           RESOLUTION_QUERY_NUM    VARCHAR2(20)   PATH '$."RESOLUTION_QUERY_NUM"',
           RESOLUTION_PARAM_MAP    VARCHAR2(500)  PATH '$."RESOLUTION_PARAM_MAP"',
           FIXABLE_STATUS_COLUMN   VARCHAR2(100)  PATH '$."FIXABLE_STATUS_COLUMN"',
           FIXABLE_STATUS_VALUE    VARCHAR2(200)  PATH '$."FIXABLE_STATUS_VALUE"'
         )
       ) jt
  WHERE rb.REQUESTID = :param1
) src
ON (tgt.CHECK_CODE = src.CHECK_CODE AND tgt.RETAILER_ID = src.RETAILER_ID)
WHEN MATCHED THEN UPDATE SET
  tgt.CHECK_NAME              = src.CHECK_NAME,
  tgt.CHECK_DESCRIPTION       = src.CHECK_DESCRIPTION,
  tgt.QUERY_NUM               = src.QUERY_NUM,
  tgt.TIER                    = src.TIER,
  tgt.SEVERITY                = src.SEVERITY,
  tgt.ENABLED                 = src.ENABLED,
  tgt.SKILL_CODE              = src.SKILL_CODE,
  tgt.ENTITY_KEY              = src.ENTITY_KEY,
  tgt.DISPLAY_ORDER           = src.DISPLAY_ORDER,
  tgt.RESOLUTION_QUERY_NUM    = src.RESOLUTION_QUERY_NUM,
  tgt.RESOLUTION_PARAM_MAP    = src.RESOLUTION_PARAM_MAP,
  tgt.FIXABLE_STATUS_COLUMN   = src.FIXABLE_STATUS_COLUMN,
  tgt.FIXABLE_STATUS_VALUE    = src.FIXABLE_STATUS_VALUE,
  tgt.UPDATED_AT              = SYSDATE
WHEN NOT MATCHED THEN INSERT (
  CHECK_ID, CHECK_CODE, CHECK_NAME, CHECK_DESCRIPTION,
  QUERY_NUM, TIER, SEVERITY, ENABLED,
  RETAILER_ID, SKILL_CODE, ENTITY_KEY, DISPLAY_ORDER,
  RESOLUTION_QUERY_NUM, RESOLUTION_PARAM_MAP,
  FIXABLE_STATUS_COLUMN, FIXABLE_STATUS_VALUE,
  CREATED_AT, UPDATED_AT
) VALUES (
  SYS_GUID(),
  src.CHECK_CODE, src.CHECK_NAME, src.CHECK_DESCRIPTION,
  src.QUERY_NUM, src.TIER, src.SEVERITY, src.ENABLED,
  src.RETAILER_ID, src.SKILL_CODE, src.ENTITY_KEY, src.DISPLAY_ORDER,
  src.RESOLUTION_QUERY_NUM, src.RESOLUTION_PARAM_MAP,
  src.FIXABLE_STATUS_COLUMN, src.FIXABLE_STATUS_VALUE,
  SYSDATE, SYSDATE
)
~',
       ':param1=REQUESTID (auto-bound by CALLQUERY)',
       '',
       1, 0, 1
  FROM dual;

COMMIT;

-- =============================================================================
-- Example resolution LIBQUERY (author separately — not inserted here)
-- Inter-department rejection: mark row processed. Adjust table/columns for GOLD.
--
-- DELETE FROM LIBQUERY WHERE QUERYNUM = 'DH0000001';
-- INSERT INTO LIBQUERY (...) SELECT ..., 'DH0000001', ...,
--   q'~
--   UPDATE your_staging_table t
--      SET t.status = 'Processed'
--    WHERE t.store_id = (SELECT jt.STORE FROM REQUEST_QUERY_BODY rb,
--          JSON_TABLE(rb.REQUESTBODY, '$.values[0]' COLUMNS (
--            STORE VARCHAR2(20) PATH '$."STORE"',
--            UPC   VARCHAR2(30) PATH '$."UPC"'
--          )) jt WHERE rb.REQUESTID = :param1)
--      AND t.upc = (SELECT jt.UPC FROM ... same jt ...)
--   ~',
--   ...
-- Config on check: RESOLUTION_QUERY_NUM=DH0000001
--   RESOLUTION_PARAM_MAP=STORE,UPC
--   FIXABLE_STATUS_COLUMN=STATUS
--   FIXABLE_STATUS_VALUE=Not processed
-- =============================================================================
