-- =============================================================================
-- 51_data_health_resolution_script_upgrade.sql
-- Data Health — resolution mode SCRIPT | SCRIPT_JOB (GOLD batch via executeScript)
-- Deploy after: 29_data_health_libquery.sql (minimum). Also applies 49/50 DDL if skipped.
-- Re-runnable: ADD COLUMN ignores ORA-01430; LIBQUERY DELETE+INSERT.
-- AI0000087 QUERYSQL uses TO_CLOB(...) || q'~...~' (MERGE > 4000 chars — ORA-01704).
-- =============================================================================

-- ── DDL from 49/50 when those scripts were not run yet ─────────────────────
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE AI_DATA_CHECK_DEF ADD (RESOLUTION_QUERY_NUM VARCHAR2(20))';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-1430, -2261) THEN RAISE; END IF;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE AI_DATA_CHECK_DEF ADD (RESOLUTION_PARAM_MAP VARCHAR2(500))';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-1430, -2261) THEN RAISE; END IF;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE AI_DATA_CHECK_DEF ADD (FIXABLE_STATUS_COLUMN VARCHAR2(100))';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-1430, -2261) THEN RAISE; END IF;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE AI_DATA_CHECK_DEF ADD (FIXABLE_STATUS_VALUE VARCHAR2(200))';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-1430, -2261) THEN RAISE; END IF;
END;
/
BEGIN
    EXECUTE IMMEDIATE q'[
        ALTER TABLE AI_DATA_CHECK_DEF ADD (
            RESOLUTION_MODE     VARCHAR2(20) DEFAULT 'NONE',
            RESOLUTION_JOB_NAME VARCHAR2(128)
        )
    ]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-1430, -2261) THEN RAISE; END IF;
END;
/

-- ── Script 51 columns ───────────────────────────────────────────────────────
BEGIN
    EXECUTE IMMEDIATE q'[
        ALTER TABLE AI_DATA_CHECK_DEF ADD (
            RESOLUTION_SCRIPT_TEMPLATE   VARCHAR2(500),
            RESOLUTION_SCRIPT_PARAM_MAP  VARCHAR2(500)
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-1430, -2261) THEN RAISE; END IF;
END;
/

UPDATE AI_DATA_CHECK_DEF
   SET RESOLUTION_MODE = 'LIBQUERY'
 WHERE RESOLUTION_QUERY_NUM IS NOT NULL
   AND TRIM(RESOLUTION_QUERY_NUM) IS NOT NULL
   AND (RESOLUTION_MODE IS NULL OR RESOLUTION_MODE = 'NONE');

COMMIT;

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE AI_DATA_CHECK_DEF DROP CONSTRAINT CK_AI_RESOLUTION_MODE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-2443) THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE q'[
        ALTER TABLE AI_DATA_CHECK_DEF ADD CONSTRAINT CK_AI_RESOLUTION_MODE
        CHECK (RESOLUTION_MODE IN ('NONE','LIBQUERY','JOB','LIBQUERY_JOB','SCRIPT','SCRIPT_JOB'))
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-2264, -2275, -2261) THEN RAISE; END IF;
END;
/

COMMENT ON COLUMN AI_DATA_CHECK_DEF.RESOLUTION_SCRIPT_TEMPLATE IS
  'GOLD command template for SCRIPT / SCRIPT_JOB (e.g. pssti20p pssti20p $USERID :transferNumber HN). $USERID is expanded on the remote host.';
COMMENT ON COLUMN AI_DATA_CHECK_DEF.RESOLUTION_SCRIPT_PARAM_MAP IS
  'Comma-separated placeholder=column pairs for :placeholders in RESOLUTION_SCRIPT_TEMPLATE (e.g. transferNumber=TRANSFER NUMBER).';

-- ── AI0000091 — allow SCRIPT_JOB as well as LIBQUERY_JOB ─────────────────────
DELETE FROM LIBQUERY WHERE QUERYNUM = 'AI0000091';

INSERT INTO LIBQUERY (
    QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE
)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'AI0000091',
       'S24 — run data health resolution job',
       'Runs RESOLUTION_JOB_NAME when RESOLUTION_MODE is JOB, LIBQUERY_JOB, or SCRIPT_JOB. Body: {values:[{CHECK_ID,RETAILER_ID}]}.',
       q'~
DECLARE
  v_check_id    VARCHAR2(36);
  v_retailer_id VARCHAR2(50);
  v_mode        VARCHAR2(20);
  v_job_name    VARCHAR2(128);
  v_enabled     NUMBER;
BEGIN
  SELECT jt.CHECK_ID, jt.RETAILER_ID
    INTO v_check_id, v_retailer_id
    FROM REQUEST_QUERY_BODY rb,
         JSON_TABLE(rb.REQUESTBODY, '$.values[0]'
           COLUMNS (
             CHECK_ID    VARCHAR2(36) PATH '$."CHECK_ID"',
             RETAILER_ID VARCHAR2(50) PATH '$."RETAILER_ID"'
           )
         ) jt
   WHERE rb.REQUESTID = :param1;

  SELECT RESOLUTION_MODE, RESOLUTION_JOB_NAME, ENABLED
    INTO v_mode, v_job_name, v_enabled
    FROM AI_DATA_CHECK_DEF
   WHERE CHECK_ID = v_check_id
     AND RETAILER_ID = v_retailer_id;

  IF NVL(v_enabled, 0) != 1 THEN
    RAISE_APPLICATION_ERROR(-20091, 'Data health check is disabled.');
  END IF;

  IF v_mode NOT IN ('JOB', 'LIBQUERY_JOB', 'SCRIPT_JOB') THEN
    RAISE_APPLICATION_ERROR(-20092, 'Check is not configured for a resolution job (mode=' || NVL(v_mode, 'NULL') || ').');
  END IF;

  IF v_job_name IS NULL OR TRIM(v_job_name) IS NULL THEN
    RAISE_APPLICATION_ERROR(-20093, 'RESOLUTION_JOB_NAME is not set on this check.');
  END IF;

  DBMS_SCHEDULER.RUN_JOB(
    job_name            => TRIM(v_job_name),
    use_current_session => FALSE
  );
  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
END;
~',
       ':param1=REQUESTID (auto-bound by CALLQUERY)',
       '',
       1, 0, 1
  FROM dual;

-- ── Refresh LIBQUERY that project AI_DATA_CHECK_DEF ─────────────────────────
DELETE FROM LIBQUERY WHERE QUERYNUM IN ('AI0000080', 'AI0000085', 'AI0000086', 'AI0000087');

INSERT INTO LIBQUERY (
    QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE
)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'AI0000080',
       'S24 — checks with latest result',
       'Active check definitions joined to most-recent AI_DATA_CHECK_RESULT. :param1=retailer_id, :param2=tier or ALL.',
       q'~
SELECT
  d.CHECK_ID,
  d.CHECK_CODE,
  d.CHECK_NAME,
  d.CHECK_DESCRIPTION,
  d.QUERY_NUM,
  d.TIER,
  d.SEVERITY,
  d.ENABLED,
  d.SKILL_CODE,
  d.ENTITY_KEY,
  d.DISPLAY_ORDER,
  NVL(d.RESOLUTION_MODE, 'NONE') AS RESOLUTION_MODE,
  d.RESOLUTION_QUERY_NUM,
  d.RESOLUTION_PARAM_MAP,
  d.RESOLUTION_JOB_NAME,
  d.RESOLUTION_SCRIPT_TEMPLATE,
  d.RESOLUTION_SCRIPT_PARAM_MAP,
  d.FIXABLE_STATUS_COLUMN,
  d.FIXABLE_STATUS_VALUE,
  r.ISSUE_COUNT,
  r.RUN_AT     AS LAST_RUN_AT,
  r.STATUS,
  r.TREND
FROM AI_DATA_CHECK_DEF d
LEFT JOIN (
  SELECT r1.*
  FROM AI_DATA_CHECK_RESULT r1
  WHERE r1.RUN_AT = (
    SELECT MAX(r2.RUN_AT)
    FROM AI_DATA_CHECK_RESULT r2
    WHERE r2.CHECK_ID    = r1.CHECK_ID
      AND r2.RETAILER_ID = r1.RETAILER_ID
  )
) r ON r.CHECK_ID = d.CHECK_ID AND r.RETAILER_ID = :param1
WHERE d.RETAILER_ID = :param1
  AND (:param2 = 'ALL' OR d.TIER = :param2)
ORDER BY d.DISPLAY_ORDER, d.CHECK_CODE
~',
       ':param1=retailer_id, :param2=tier (ALL|REALTIME|HOURLY|NIGHTLY)',
       'CHECK_ID,CHECK_CODE,CHECK_NAME,CHECK_DESCRIPTION,QUERY_NUM,TIER,SEVERITY,ENABLED,SKILL_CODE,ENTITY_KEY,DISPLAY_ORDER,RESOLUTION_MODE,RESOLUTION_QUERY_NUM,RESOLUTION_PARAM_MAP,RESOLUTION_JOB_NAME,RESOLUTION_SCRIPT_TEMPLATE,RESOLUTION_SCRIPT_PARAM_MAP,FIXABLE_STATUS_COLUMN,FIXABLE_STATUS_VALUE,ISSUE_COUNT,LAST_RUN_AT,STATUS,TREND',
       1, 0, 0
  FROM dual;

INSERT INTO LIBQUERY (
    QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE
)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'AI0000085',
       'S25 — check definitions for retailer',
       'All AI_DATA_CHECK_DEF rows for the given retailer (includes disabled). :param1=retailer_id.',
       q'~
SELECT
  CHECK_ID,
  CHECK_CODE,
  CHECK_NAME,
  CHECK_DESCRIPTION,
  QUERY_NUM,
  TIER,
  SEVERITY,
  ENABLED,
  RETAILER_ID,
  SKILL_CODE,
  ENTITY_KEY,
  DISPLAY_ORDER,
  NVL(RESOLUTION_MODE, 'NONE') AS RESOLUTION_MODE,
  RESOLUTION_QUERY_NUM,
  RESOLUTION_PARAM_MAP,
  RESOLUTION_JOB_NAME,
  RESOLUTION_SCRIPT_TEMPLATE,
  RESOLUTION_SCRIPT_PARAM_MAP,
  FIXABLE_STATUS_COLUMN,
  FIXABLE_STATUS_VALUE,
  CREATED_AT,
  UPDATED_AT
FROM AI_DATA_CHECK_DEF
WHERE RETAILER_ID = :param1
ORDER BY DISPLAY_ORDER, CHECK_CODE
~',
       ':param1=retailer_id',
       'CHECK_ID,CHECK_CODE,CHECK_NAME,CHECK_DESCRIPTION,QUERY_NUM,TIER,SEVERITY,ENABLED,RETAILER_ID,SKILL_CODE,ENTITY_KEY,DISPLAY_ORDER,RESOLUTION_MODE,RESOLUTION_QUERY_NUM,RESOLUTION_PARAM_MAP,RESOLUTION_JOB_NAME,RESOLUTION_SCRIPT_TEMPLATE,RESOLUTION_SCRIPT_PARAM_MAP,FIXABLE_STATUS_COLUMN,FIXABLE_STATUS_VALUE,CREATED_AT,UPDATED_AT',
       1, 0, 0
  FROM dual;

INSERT INTO LIBQUERY (
    QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE
)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'AI0000086',
       'S25 — check definition by id',
       'Single AI_DATA_CHECK_DEF row. :param1=check_id.',
       q'~
SELECT
  CHECK_ID, CHECK_CODE, CHECK_NAME, CHECK_DESCRIPTION,
  QUERY_NUM, TIER, SEVERITY, ENABLED,
  RETAILER_ID, SKILL_CODE, ENTITY_KEY, DISPLAY_ORDER,
  NVL(RESOLUTION_MODE, 'NONE') AS RESOLUTION_MODE,
  RESOLUTION_QUERY_NUM, RESOLUTION_PARAM_MAP, RESOLUTION_JOB_NAME,
  RESOLUTION_SCRIPT_TEMPLATE, RESOLUTION_SCRIPT_PARAM_MAP,
  FIXABLE_STATUS_COLUMN, FIXABLE_STATUS_VALUE
FROM AI_DATA_CHECK_DEF
WHERE CHECK_ID = :param1
~',
       ':param1=check_id',
       'CHECK_ID,CHECK_CODE,CHECK_NAME,CHECK_DESCRIPTION,QUERY_NUM,TIER,SEVERITY,ENABLED,RETAILER_ID,SKILL_CODE,ENTITY_KEY,DISPLAY_ORDER,RESOLUTION_MODE,RESOLUTION_QUERY_NUM,RESOLUTION_PARAM_MAP,RESOLUTION_JOB_NAME,RESOLUTION_SCRIPT_TEMPLATE,RESOLUTION_SCRIPT_PARAM_MAP,FIXABLE_STATUS_COLUMN,FIXABLE_STATUS_VALUE',
       1, 0, 0
  FROM dual;

INSERT INTO LIBQUERY (
    QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE
)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'AI0000087',
       'S25 — upsert check definition',
       'MERGE into AI_DATA_CHECK_DEF on CHECK_CODE+RETAILER_ID. Body: {values:[{CHECK_CODE,...}]}.',
       TO_CLOB(q'~
MERGE INTO AI_DATA_CHECK_DEF tgt
USING (
  SELECT
    jt.CHECK_CODE,
    jt.CHECK_NAME,
    jt.CHECK_DESCRIPTION,
    jt.QUERY_NUM,
    jt.TIER,
    jt.SEVERITY,
    jt.ENABLED,
    jt.RETAILER_ID,
    jt.SKILL_CODE,
    jt.ENTITY_KEY,
    jt.DISPLAY_ORDER,
    NVL(jt.RESOLUTION_MODE, 'NONE') AS RESOLUTION_MODE,
    jt.RESOLUTION_QUERY_NUM,
    jt.RESOLUTION_PARAM_MAP,
    jt.RESOLUTION_JOB_NAME,
    jt.RESOLUTION_SCRIPT_TEMPLATE,
    jt.RESOLUTION_SCRIPT_PARAM_MAP,
    jt.FIXABLE_STATUS_COLUMN,
    jt.FIXABLE_STATUS_VALUE
  FROM REQUEST_QUERY_BODY rb,
       JSON_TABLE(rb.REQUESTBODY, '$.values[0]'
         COLUMNS (
           CHECK_CODE                   VARCHAR2(50)   PATH '$."CHECK_CODE"',
           CHECK_NAME                   VARCHAR2(200)  PATH '$."CHECK_NAME"',
           CHECK_DESCRIPTION            VARCHAR2(500)  PATH '$."CHECK_DESCRIPTION"',
           QUERY_NUM                    VARCHAR2(20)   PATH '$."QUERY_NUM"',
           TIER                         VARCHAR2(20)   PATH '$."TIER"',
           SEVERITY                     VARCHAR2(20)   PATH '$."SEVERITY"',
           ENABLED                      NUMBER         PATH '$."ENABLED"',
           RETAILER_ID                  VARCHAR2(50)   PATH '$."RETAILER_ID"',
           SKILL_CODE                   VARCHAR2(100)  PATH '$."SKILL_CODE"',
           ENTITY_KEY                   VARCHAR2(100)  PATH '$."ENTITY_KEY"',
           DISPLAY_ORDER                NUMBER         PATH '$."DISPLAY_ORDER"',
           RESOLUTION_MODE              VARCHAR2(20)   PATH '$."RESOLUTION_MODE"',
           RESOLUTION_QUERY_NUM         VARCHAR2(20)   PATH '$."RESOLUTION_QUERY_NUM"',
           RESOLUTION_PARAM_MAP         VARCHAR2(500)  PATH '$."RESOLUTION_PARAM_MAP"',
           RESOLUTION_JOB_NAME          VARCHAR2(128)  PATH '$."RESOLUTION_JOB_NAME"',
           RESOLUTION_SCRIPT_TEMPLATE   VARCHAR2(500)  PATH '$."RESOLUTION_SCRIPT_TEMPLATE"',
           RESOLUTION_SCRIPT_PARAM_MAP  VARCHAR2(500)  PATH '$."RESOLUTION_SCRIPT_PARAM_MAP"',
           FIXABLE_STATUS_COLUMN        VARCHAR2(100)  PATH '$."FIXABLE_STATUS_COLUMN"',
           FIXABLE_STATUS_VALUE         VARCHAR2(200)  PATH '$."FIXABLE_STATUS_VALUE"'
         )
       ) jt
  WHERE rb.REQUESTID = :param1
) src
~') || q'~
ON (tgt.CHECK_CODE = src.CHECK_CODE AND tgt.RETAILER_ID = src.RETAILER_ID)
WHEN MATCHED THEN UPDATE SET
  tgt.CHECK_NAME                   = src.CHECK_NAME,
  tgt.CHECK_DESCRIPTION            = src.CHECK_DESCRIPTION,
  tgt.QUERY_NUM                    = src.QUERY_NUM,
  tgt.TIER                         = src.TIER,
  tgt.SEVERITY                     = src.SEVERITY,
  tgt.ENABLED                      = src.ENABLED,
  tgt.SKILL_CODE                   = src.SKILL_CODE,
  tgt.ENTITY_KEY                   = src.ENTITY_KEY,
  tgt.DISPLAY_ORDER                = src.DISPLAY_ORDER,
  tgt.RESOLUTION_MODE              = src.RESOLUTION_MODE,
  tgt.RESOLUTION_QUERY_NUM         = src.RESOLUTION_QUERY_NUM,
  tgt.RESOLUTION_PARAM_MAP         = src.RESOLUTION_PARAM_MAP,
  tgt.RESOLUTION_JOB_NAME          = src.RESOLUTION_JOB_NAME,
  tgt.RESOLUTION_SCRIPT_TEMPLATE   = src.RESOLUTION_SCRIPT_TEMPLATE,
  tgt.RESOLUTION_SCRIPT_PARAM_MAP  = src.RESOLUTION_SCRIPT_PARAM_MAP,
  tgt.FIXABLE_STATUS_COLUMN        = src.FIXABLE_STATUS_COLUMN,
  tgt.FIXABLE_STATUS_VALUE         = src.FIXABLE_STATUS_VALUE,
  tgt.UPDATED_AT                   = SYSDATE
WHEN NOT MATCHED THEN INSERT (
  CHECK_ID, CHECK_CODE, CHECK_NAME, CHECK_DESCRIPTION,
  QUERY_NUM, TIER, SEVERITY, ENABLED,
  RETAILER_ID, SKILL_CODE, ENTITY_KEY, DISPLAY_ORDER,
  RESOLUTION_MODE, RESOLUTION_QUERY_NUM, RESOLUTION_PARAM_MAP, RESOLUTION_JOB_NAME,
  RESOLUTION_SCRIPT_TEMPLATE, RESOLUTION_SCRIPT_PARAM_MAP,
  FIXABLE_STATUS_COLUMN, FIXABLE_STATUS_VALUE,
  CREATED_AT, UPDATED_AT
) VALUES (
  SYS_GUID(),
  src.CHECK_CODE, src.CHECK_NAME, src.CHECK_DESCRIPTION,
  src.QUERY_NUM, src.TIER, src.SEVERITY, src.ENABLED,
  src.RETAILER_ID, src.SKILL_CODE, src.ENTITY_KEY, src.DISPLAY_ORDER,
  src.RESOLUTION_MODE, src.RESOLUTION_QUERY_NUM, src.RESOLUTION_PARAM_MAP, src.RESOLUTION_JOB_NAME,
  src.RESOLUTION_SCRIPT_TEMPLATE, src.RESOLUTION_SCRIPT_PARAM_MAP,
  src.FIXABLE_STATUS_COLUMN, src.FIXABLE_STATUS_VALUE,
  SYSDATE, SYSDATE
)
~',
       ':param1=REQUESTID (auto-bound by CALLQUERY)',
       '',
       1, 0, 1
  FROM dual;

COMMIT;

-- =============================================================================
-- Example — Inter-department item rejection (configure in S25 after deploy)
--
-- RESOLUTION_MODE          = SCRIPT
-- RESOLUTION_SCRIPT_TEMPLATE   = pssti20p pssti20p $USERID :transferNumber HN
-- RESOLUTION_SCRIPT_PARAM_MAP  = transferNumber=TRANSFER NUMBER
--   (use the exact header from your detail LIBQUERY; add sirnump / transfer id column if needed)
-- FIXABLE_STATUS_COLUMN    = STATUS
-- FIXABLE_STATUS_VALUE     = Not processed
-- =============================================================================
