-- USERSROOM.USERTYPE in Users & Profiles (SET0000020–SET0000022)
-- Deploy on DBs that already have 34_settings_users_corporate_libquery.sql without USERTYPE.
-- Idempotent: DELETE + INSERT. Full bundle: re-run 34_settings_users_corporate_libquery.sql instead.

DELETE FROM LIBQUERY WHERE QUERYNUM IN ('SET0000020', 'SET0000021', 'SET0000022');

INSERT INTO LIBQUERY (QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'SET0000020',
       'Users - list',
       'List users. :param1=USERCORPID or -1; :param2=USERACTIVE or -1.',
       q'~SELECT u.USERID, u.USERCORPID, c.CORPCODE, u.USERFNAME, u.USERLNAME, u.USEREMAIL,
       u.USERACTIVE, u.USERAPPLI, u.USERPROF, u.USERLANG, NVL(u.USERTYPE, 0) USERTYPE,
       u.USERDMAJ, u.USERUTIL
  FROM USERSROOM u
  LEFT JOIN CORPORATE c ON c.CORPID = u.USERCORPID
 WHERE (:param1 = '-1' OR u.USERCORPID = TO_NUMBER(:param1))
   AND (:param2 = '-1' OR u.USERACTIVE = TO_NUMBER(:param2))
 ORDER BY u.USERID~',
       ':param1=corpid,:param2=active',
       'USERID,USERCORPID,CORPCODE,USERFNAME,USERLNAME,USEREMAIL,USERACTIVE,USERAPPLI,USERPROF,USERLANG,USERTYPE,USERDMAJ,USERUTIL',
       0, 0, 0 FROM dual;

INSERT INTO LIBQUERY (QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'SET0000021',
       'Users - by id',
       'Single user. :param1=USERID; :param2=USERAPPLI.',
       q'~SELECT u.USERID, u.USERCORPID, u.USERPASS, u.USERAUTH, u.USERLANG, u.USERPROF, u.USERAPPLI,
       u.USERFNAME, u.USERLNAME, u.USEREMAIL, u.USERMOBILE, u.USERTEAM, u.USERACTIVE, u.USERMOBEMAIL,
       u.USERDATAINTEGRITY, u.USERIT, u.USERBUYER, u.USERHELPDESK, u.USERWAREHOUSE,
       u.USERSPACEPLANNING, u.USERSTECH, u.USERAIADMIN, u.USERAIDESIGNER,
       NVL(u.USERTYPE, 0) USERTYPE, u.USERDCRE, u.USERDMAJ, u.USERUTIL
  FROM USERSROOM u
 WHERE u.USERID = :param1
   AND u.USERAPPLI = TO_NUMBER(:param2)~',
       ':param1=userid,:param2=userappli',
       'USERID,USERCORPID,USERPASS,USERAUTH,USERLANG,USERPROF,USERAPPLI,USERFNAME,USERLNAME,USEREMAIL,USERMOBILE,USERTEAM,USERACTIVE,USERMOBEMAIL,USERDATAINTEGRITY,USERIT,USERBUYER,USERHELPDESK,USERWAREHOUSE,USERSPACEPLANNING,USERSTECH,USERAIADMIN,USERAIDESIGNER,USERTYPE,USERDCRE,USERDMAJ,USERUTIL',
       0, 0, 0 FROM dual;

INSERT INTO LIBQUERY (QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'SET0000022',
       'Users - MERGE',
       'Insert/update USERSROOM. Body {values:[{...}]}. USERPASS Base64. USERTYPE 0=standard 1=ICR admin.',
       TO_CLOB(q'~
MERGE INTO USERSROOM tgt
USING (
SELECT jt.USERID, TO_NUMBER(jt.USERCORPID) USERCORPID, NVL(TO_NUMBER(jt.USERAPPLI),1) USERAPPLI,
  jt.USERPASS, TO_NUMBER(jt.USERAUTH) USERAUTH, jt.USERLANG, TO_NUMBER(jt.USERPROF) USERPROF,
  jt.USERFNAME, jt.USERLNAME, jt.USEREMAIL, jt.USERMOBILE, TO_NUMBER(jt.USERTEAM) USERTEAM,
  NVL(TO_NUMBER(jt.USERACTIVE),1) USERACTIVE, jt.USERMOBEMAIL,
  NVL(TO_NUMBER(jt.USERDATAINTEGRITY),1) USERDATAINTEGRITY,
  NVL(TO_NUMBER(jt.USERIT),1) USERIT, NVL(TO_NUMBER(jt.USERBUYER),1) USERBUYER,
  NVL(TO_NUMBER(jt.USERHELPDESK),1) USERHELPDESK, NVL(TO_NUMBER(jt.USERWAREHOUSE),1) USERWAREHOUSE,
  NVL(TO_NUMBER(jt.USERSPACEPLANNING),1) USERSPACEPLANNING, NVL(TO_NUMBER(jt.USERSTECH),1) USERSTECH,
  NVL(TO_NUMBER(jt.USERAIADMIN),0) USERAIADMIN, NVL(TO_NUMBER(jt.USERAIDESIGNER),0) USERAIDESIGNER,
  NVL(TO_NUMBER(jt.USERTYPE),0) USERTYPE, jt.USERUTIL, jt.UPDATE_PASS
FROM REQUEST_QUERY_BODY rb,
JSON_TABLE(rb.REQUESTBODY,'$.values[0]' COLUMNS (
  USERID VARCHAR2(20) PATH '$."USERID"', USERCORPID VARCHAR2(20) PATH '$."USERCORPID"',
  USERAPPLI VARCHAR2(10) PATH '$."USERAPPLI"', USERPASS VARCHAR2(40) PATH '$."USERPASS"',
  USERAUTH VARCHAR2(10) PATH '$."USERAUTH"', USERLANG VARCHAR2(5) PATH '$."USERLANG"',
  USERPROF VARCHAR2(20) PATH '$."USERPROF"', USERFNAME VARCHAR2(30) PATH '$."USERFNAME"',
  USERLNAME VARCHAR2(50) PATH '$."USERLNAME"', USEREMAIL VARCHAR2(50) PATH '$."USEREMAIL"',
  USERMOBILE VARCHAR2(30) PATH '$."USERMOBILE"', USERTEAM VARCHAR2(20) PATH '$."USERTEAM"',
  USERACTIVE VARCHAR2(5) PATH '$."USERACTIVE"', USERMOBEMAIL VARCHAR2(50) PATH '$."USERMOBEMAIL"',
  USERDATAINTEGRITY VARCHAR2(5) PATH '$."USERDATAINTEGRITY"', USERIT VARCHAR2(5) PATH '$."USERIT"',
  USERBUYER VARCHAR2(5) PATH '$."USERBUYER"', USERHELPDESK VARCHAR2(5) PATH '$."USERHELPDESK"',
  USERWAREHOUSE VARCHAR2(5) PATH '$."USERWAREHOUSE"',
  USERSPACEPLANNING VARCHAR2(5) PATH '$."USERSPACEPLANNING"', USERSTECH VARCHAR2(5) PATH '$."USERSTECH"',
  USERAIADMIN VARCHAR2(5) PATH '$."USERAIADMIN"', USERAIDESIGNER VARCHAR2(5) PATH '$."USERAIDESIGNER"',
  USERTYPE VARCHAR2(5) PATH '$."USERTYPE"', USERUTIL VARCHAR2(20) PATH '$."USERUTIL"',
  UPDATE_PASS VARCHAR2(5) PATH '$."UPDATE_PASS"'
)) jt WHERE rb.REQUESTID = :param1
) src
~') || q'~
ON (tgt.USERID = src.USERID AND tgt.USERAPPLI = src.USERAPPLI)
WHEN MATCHED THEN UPDATE SET
  tgt.USERCORPID=src.USERCORPID,tgt.USERAUTH=src.USERAUTH,tgt.USERLANG=src.USERLANG,
  tgt.USERPROF=src.USERPROF,tgt.USERFNAME=src.USERFNAME,tgt.USERLNAME=src.USERLNAME,
  tgt.USEREMAIL=src.USEREMAIL,tgt.USERMOBILE=src.USERMOBILE,tgt.USERTEAM=src.USERTEAM,
  tgt.USERACTIVE=src.USERACTIVE,tgt.USERMOBEMAIL=src.USERMOBEMAIL,
  tgt.USERDATAINTEGRITY=src.USERDATAINTEGRITY,tgt.USERIT=src.USERIT,tgt.USERBUYER=src.USERBUYER,
  tgt.USERHELPDESK=src.USERHELPDESK,tgt.USERWAREHOUSE=src.USERWAREHOUSE,
  tgt.USERSPACEPLANNING=src.USERSPACEPLANNING,tgt.USERSTECH=src.USERSTECH,
  tgt.USERAIADMIN=src.USERAIADMIN,tgt.USERAIDESIGNER=src.USERAIDESIGNER,tgt.USERTYPE=src.USERTYPE,
  tgt.USERPASS=CASE WHEN src.UPDATE_PASS='1' AND src.USERPASS IS NOT NULL THEN src.USERPASS ELSE tgt.USERPASS END,
  tgt.USERDMAJ=SYSDATE,tgt.USERUTIL=src.USERUTIL
WHEN NOT MATCHED THEN INSERT (
  USERID,USERCORPID,USERPASS,USERAUTH,USERLANG,USERPROF,USERAPPLI,USERFNAME,USERLNAME,USEREMAIL,
  USERMOBILE,USERTEAM,USERACTIVE,USERMOBEMAIL,USERDATAINTEGRITY,USERIT,USERBUYER,USERHELPDESK,
  USERWAREHOUSE,USERSPACEPLANNING,USERSTECH,USERAIADMIN,USERAIDESIGNER,USERTYPE,USERDCRE,USERDMAJ,USERUTIL)
VALUES (
  src.USERID,src.USERCORPID,src.USERPASS,src.USERAUTH,src.USERLANG,src.USERPROF,src.USERAPPLI,
  src.USERFNAME,src.USERLNAME,src.USEREMAIL,src.USERMOBILE,src.USERTEAM,src.USERACTIVE,src.USERMOBEMAIL,
  src.USERDATAINTEGRITY,src.USERIT,src.USERBUYER,src.USERHELPDESK,src.USERWAREHOUSE,
  src.USERSPACEPLANNING,src.USERSTECH,src.USERAIADMIN,src.USERAIDESIGNER,src.USERTYPE,
  SYSDATE,SYSDATE,src.USERUTIL)
~',
       ':param1=REQUESTID',
       '',
       0, 0, 1 FROM dual;

COMMIT;
