-- User profile dropdown — ICR_MENU_ENTRY (HEADER) + SET0000041 upgrade
-- Manage labels/order/access via General Settings → Menu & access (MENU_TYPE = HEADER).
-- Re-runnable incremental patch (does not wipe full menu catalog).

-- ── Catalog rows ────────────────────────────────────────────────────────────
MERGE INTO ICR_MENU_ENTRY t
USING (
  SELECT 'HDR_USER_PROFILE' MENU_CODE, NULL PARENT_CODE, 'HEADER' MENU_TYPE, 'BOTH' MENU_MODE,
         NULL ROUTE_PATH, 'fa fa-fw fa-user' ICON_CLASS, 'Profile' LABEL_TEXT, 10 SORT_ORDER, NULL EXPAND_KEY, 1 ACTIVE FROM dual UNION ALL
  SELECT 'HDR_USER_CHANGE_PASSWORD', NULL, 'HEADER', 'BOTH', NULL, 'fa fa-fw fa-key', 'Change password', 20, NULL, 1 FROM dual UNION ALL
  SELECT 'HDR_USER_DOCUMENTATION', NULL, 'HEADER', 'BOTH', '/documentation', 'fa fa-fw fa-book', 'Documentation', 25, NULL, 1 FROM dual UNION ALL
  SELECT 'HDR_USER_INBOX', NULL, 'HEADER', 'BOTH', NULL, 'fa fa-fw fa-envelope', 'Inbox', 30, NULL, 1 FROM dual UNION ALL
  SELECT 'HDR_USER_SETTINGS', NULL, 'HEADER', 'BOTH', NULL, 'fa fa-fw fa-gear', 'Settings', 40, NULL, 1 FROM dual UNION ALL
  SELECT 'HDR_USER_SWITCH_MENU', NULL, 'HEADER', 'BOTH', NULL, 'fa fa-fw fa-bars', 'Switch Menu', 50, NULL, 1 FROM dual UNION ALL
  SELECT 'HDR_USER_LOGOUT', NULL, 'HEADER', 'BOTH', '/login', 'fa fa-fw fa-power-off', 'Log Out', 60, NULL, 1 FROM dual
) s ON (t.MENU_CODE = s.MENU_CODE)
WHEN MATCHED THEN UPDATE SET
  t.PARENT_CODE = s.PARENT_CODE, t.MENU_TYPE = s.MENU_TYPE, t.MENU_MODE = s.MENU_MODE,
  t.ROUTE_PATH = s.ROUTE_PATH, t.ICON_CLASS = s.ICON_CLASS, t.LABEL_TEXT = s.LABEL_TEXT,
  t.SORT_ORDER = s.SORT_ORDER, t.ACTIVE = s.ACTIVE
WHEN NOT MATCHED THEN INSERT (
  MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE)
VALUES (
  s.MENU_CODE, s.PARENT_CODE, s.MENU_TYPE, s.MENU_MODE, s.ROUTE_PATH, s.ICON_CLASS, s.LABEL_TEXT, s.SORT_ORDER, s.EXPAND_KEY, s.ACTIVE);

INSERT INTO ICR_MENU_ACCESS_RULE (MENU_CODE, FLAG_NAME)
SELECT 'HDR_USER_PROFILE', 'ALL' FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM ICR_MENU_ACCESS_RULE r WHERE r.MENU_CODE = 'HDR_USER_PROFILE' AND r.FLAG_NAME = 'ALL');
INSERT INTO ICR_MENU_ACCESS_RULE (MENU_CODE, FLAG_NAME)
SELECT 'HDR_USER_CHANGE_PASSWORD', 'ALL' FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM ICR_MENU_ACCESS_RULE r WHERE r.MENU_CODE = 'HDR_USER_CHANGE_PASSWORD' AND r.FLAG_NAME = 'ALL');
INSERT INTO ICR_MENU_ACCESS_RULE (MENU_CODE, FLAG_NAME)
SELECT 'HDR_USER_DOCUMENTATION', 'ALL' FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM ICR_MENU_ACCESS_RULE r WHERE r.MENU_CODE = 'HDR_USER_DOCUMENTATION' AND r.FLAG_NAME = 'ALL');
INSERT INTO ICR_MENU_ACCESS_RULE (MENU_CODE, FLAG_NAME)
SELECT 'HDR_USER_INBOX', 'ALL' FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM ICR_MENU_ACCESS_RULE r WHERE r.MENU_CODE = 'HDR_USER_INBOX' AND r.FLAG_NAME = 'ALL');
INSERT INTO ICR_MENU_ACCESS_RULE (MENU_CODE, FLAG_NAME)
SELECT 'HDR_USER_SETTINGS', 'ALL' FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM ICR_MENU_ACCESS_RULE r WHERE r.MENU_CODE = 'HDR_USER_SETTINGS' AND r.FLAG_NAME = 'ALL');
INSERT INTO ICR_MENU_ACCESS_RULE (MENU_CODE, FLAG_NAME)
SELECT 'HDR_USER_SWITCH_MENU', 'ALL' FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM ICR_MENU_ACCESS_RULE r WHERE r.MENU_CODE = 'HDR_USER_SWITCH_MENU' AND r.FLAG_NAME = 'ALL');
INSERT INTO ICR_MENU_ACCESS_RULE (MENU_CODE, FLAG_NAME)
SELECT 'HDR_USER_LOGOUT', 'ALL' FROM dual
 WHERE NOT EXISTS (SELECT 1 FROM ICR_MENU_ACCESS_RULE r WHERE r.MENU_CODE = 'HDR_USER_LOGOUT' AND r.FLAG_NAME = 'ALL');

-- ── SET0000041 — return ROUTE_PATH + SORT_ORDER; same grants as sidebar ─────
DELETE FROM LIBQUERY WHERE QUERYNUM = 'SET0000041';

INSERT INTO LIBQUERY (QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'SET0000041',
       'Menu - header actions for user',
       'HEADER menu rows for USERID :param1 (toolbar + profile dropdown).',
       q'~
SELECT m.MENU_CODE, m.LABEL_TEXT, m.ICON_CLASS, m.ROUTE_PATH, m.SORT_ORDER
  FROM ICR_MENU_ENTRY m
  JOIN USERSROOM u ON u.USERID = :param1
 WHERE m.ACTIVE = 1
   AND m.MENU_TYPE = 'HEADER'
   AND (
         EXISTS (
           SELECT 1 FROM ICR_MENU_ACCESS_RULE r
            WHERE r.MENU_CODE = m.MENU_CODE
              AND (
                    r.FLAG_NAME = 'ALL'
                 OR (r.FLAG_NAME = 'BUYER'          AND NVL(u.USERBUYER, 0) = 1)
                 OR (r.FLAG_NAME = 'HELPDESK'       AND NVL(u.USERHELPDESK, 0) = 1)
                 OR (r.FLAG_NAME = 'IT'             AND NVL(u.USERIT, 0) = 1)
                 OR (r.FLAG_NAME = 'DATAINTEGRITY' AND NVL(u.USERDATAINTEGRITY, 0) = 1)
                 OR (r.FLAG_NAME = 'TECH'            AND NVL(u.USERSTECH, 0) = 1)
                 OR (r.FLAG_NAME = 'WAREHOUSE'      AND NVL(u.USERWAREHOUSE, 0) = 1)
                 OR (r.FLAG_NAME = 'SPACE'          AND NVL(u.USERSPACEPLANNING, 0) = 1)
                 OR (r.FLAG_NAME = 'AIADMIN'        AND NVL(u.USERAIADMIN, 0) = 1)
                 OR (r.FLAG_NAME = 'AIDESIGNER'     AND NVL(u.USERAIDESIGNER, 0) = 1)
                 OR (r.FLAG_NAME = 'ADMIN'          AND NVL(u.USERTYPE, 0) = 1)
              )
         )
         OR (
           u.USERPROF IS NOT NULL
           AND EXISTS (
             SELECT 1 FROM ICR_PROFILE_MENU pm
              WHERE pm.PROFILE_ID = u.USERPROF
                AND pm.MENU_CODE = m.MENU_CODE
                AND pm.GRANTED = 1
           )
         )
       )
 ORDER BY m.SORT_ORDER, m.LABEL_TEXT
~',
       ':param1=user_id',
       'MENU_CODE,LABEL_TEXT,ICON_CLASS,ROUTE_PATH,SORT_ORDER',
       1, 0, 0 FROM dual;

COMMIT;
