-- TRA_TECHOBJ - Supply Chain AI screens + Critical Alert Watchdog (info overlay on hover)
-- Deploy to ICR app DB. Idempotent MERGE per TOBID + TOBLANGUE.
-- Screen IDs must match Angular screenID on each app-page-header (SCR0000000052-0063).
-- HTML uses class bbs-keywords (same as dashboard SCR0000000001).
--
-- SQL*Plus / SQL Developer: disable & substitution (HTML has &amp;, TOBCAT has "Retailer & GOLD").
SET DEFINE OFF;

-- Watchdog: was SCR0000000020 (conflicted with Helpdesk / Restart services) -> SCR0000000052

MERGE INTO TRA_TECHOBJ t
USING (
  SELECT 'SCR0000000052' AS TOBID, 'us_US' AS TOBLANGUE FROM DUAL
) s ON (t.TOBID = s.TOBID AND t.TOBLANGUE = s.TOBLANGUE)
WHEN MATCHED THEN UPDATE SET
  TOBCAT = 'Critical Alert Watchdog',
  TOBDESC = q'[<div><i class="bbs-keywords">What is it : </i>This screen protects <b>critical alerts</b> from silent failure. Each <b>watch contract</b> defines an expected <code>ALERTLOG</code> signature (alert id, optional param pattern, cron, grace). A background scanner verifies that the log row arrived on time.</div><div><i class="bbs-keywords">How it works : </i><li><b>ALERTWATCH</b> - contracts you maintain here (schedule + recovery shell).</li><li><b>ALERTSCHEDULE</b> - primary job that fires the alert (separate from the watch).</li><li>On a miss, the watchdog runs <b>AWTSHELL</b> (typically curl to <code>/api/notification/</code>), logs to <code>ALERTWATCHLOG</code>, and notifies admins.</li></div>]',
  TOBDESC2 = q'[<div><i class="bbs-keywords">Day-to-day : </i><li><b>CREATE</b> - pick Alert (LALTID), optional <b>LALTPARAM LIKE</b> for fan-out instances, cron + grace, recovery shell.</li><li><b>RUN NOW</b> - force an immediate scan (24 h lookback).</li><li><b>Last recovery</b> - RECOVERED / FAILED / never; history icon opens <code>ALERTWATCHLOG</code>.</li><li><b>FAILED</b> is not auto-retried - delete the log row to retry after fixing root cause.</li></div><div><i class="bbs-keywords">When to use : </i>After adding evening/morning alert schedules, for fan-out store alerts (<code>CNT_*</code>, etc.), or when operations must be paged if a scheduled alert did not land in <code>ALERTLOG</code>.</div>]',
  TOBDMAJ = SYSDATE, TOBUTIL = 'admin'
WHEN NOT MATCHED THEN INSERT (TOBID, TOBCAT, TOBDESC, TOBDESC2, TOBLANGUE, TOBDCRE, TOBDMAJ, TOBUTIL)
VALUES ('SCR0000000052', 'Critical Alert Watchdog',
  q'[<div><i class="bbs-keywords">What is it : </i>This screen protects <b>critical alerts</b> from silent failure. Each <b>watch contract</b> defines an expected <code>ALERTLOG</code> signature (alert id, optional param pattern, cron, grace). A background scanner verifies that the log row arrived on time.</div><div><i class="bbs-keywords">How it works : </i><li><b>ALERTWATCH</b> - contracts you maintain here (schedule + recovery shell).</li><li><b>ALERTSCHEDULE</b> - primary job that fires the alert (separate from the watch).</li><li>On a miss, the watchdog runs <b>AWTSHELL</b> (typically curl to <code>/api/notification/</code>), logs to <code>ALERTWATCHLOG</code>, and notifies admins.</li></div>]',
  q'[<div><i class="bbs-keywords">Day-to-day : </i><li><b>CREATE</b> - pick Alert (LALTID), optional <b>LALTPARAM LIKE</b> for fan-out instances, cron + grace, recovery shell.</li><li><b>RUN NOW</b> - force an immediate scan (24 h lookback).</li><li><b>Last recovery</b> - RECOVERED / FAILED / never; history icon opens <code>ALERTWATCHLOG</code>.</li><li><b>FAILED</b> is not auto-retried - delete the log row to retry after fixing root cause.</li></div><div><i class="bbs-keywords">When to use : </i>After adding evening/morning alert schedules, for fan-out store alerts (<code>CNT_*</code>, etc.), or when operations must be paged if a scheduled alert did not land in <code>ALERTLOG</code>.</div>]',
  'us_US', SYSDATE, SYSDATE, 'admin');

MERGE INTO TRA_TECHOBJ t USING (SELECT 'SCR0000000053' TOBID, 'us_US' TOBLANGUE FROM DUAL) s
ON (t.TOBID = s.TOBID AND t.TOBLANGUE = s.TOBLANGUE)
WHEN MATCHED THEN UPDATE SET TOBCAT='Retailer & GOLD Setup', TOBDESC=q'[<div><i class="bbs-keywords">What is it : </i>Onboarding wizard for <b>Supply Chain AI</b>: links a retailer to a <b>CORPENV</b> GOLD connection, tests the database link, and registers <code>AI_RETAILER_CONFIG</code>.</div><div><i class="bbs-keywords">Workflow : </i><li>Select corporate environment (ENVIP, ENVDBLINK, ENVGOLDSCHEMA).</li><li>Enter retailer id, code, and display name.</li><li><b>Test connection</b> - pings GOLD via <code>/api/ai/retailer/ping-dblink</code>.</li><li><b>Save</b> - persists retailer row for all AI modules.</li></div>]', TOBDESC2=q'[<div><i class="bbs-keywords">When to use : </i>First-time AI setup per environment (preprod/prod), or when CORPENV / DB link / schema prefix changes. Required before Schema Discovery and Context Learning.</div>]', TOBDMAJ=SYSDATE, TOBUTIL='admin'
WHEN NOT MATCHED THEN INSERT (TOBID,TOBCAT,TOBDESC,TOBDESC2,TOBLANGUE,TOBDCRE,TOBDMAJ,TOBUTIL) VALUES ('SCR0000000053','Retailer & GOLD Setup',q'[<div><i class="bbs-keywords">What is it : </i>Onboarding wizard for <b>Supply Chain AI</b>: links a retailer to a <b>CORPENV</b> GOLD connection, tests the database link, and registers <code>AI_RETAILER_CONFIG</code>.</div><div><i class="bbs-keywords">Workflow : </i><li>Select corporate environment (ENVIP, ENVDBLINK, ENVGOLDSCHEMA).</li><li>Enter retailer id, code, and display name.</li><li><b>Test connection</b> - pings GOLD via <code>/api/ai/retailer/ping-dblink</code>.</li><li><b>Save</b> - persists retailer row for all AI modules.</li></div>]',q'[<div><i class="bbs-keywords">When to use : </i>First-time AI setup per environment (preprod/prod), or when CORPENV / DB link / schema prefix changes. Required before Schema Discovery and Context Learning.</div>]','us_US',SYSDATE,SYSDATE,'admin');

MERGE INTO TRA_TECHOBJ t USING (SELECT 'SCR0000000054' TOBID, 'us_US' TOBLANGUE FROM DUAL) s
ON (t.TOBID = s.TOBID AND t.TOBLANGUE = s.TOBLANGUE)
WHEN MATCHED THEN UPDATE SET TOBCAT='Schema Discovery (S02)', TOBDESC=q'[<div><i class="bbs-keywords">What is it : </i>Scans the retailer GOLD database (via DB link) and catalogs tables, columns, comments, and samples into ICR <code>AI_SCHEMA_*</code> tables for designers and the AI engine.</div><div><i class="bbs-keywords">Workflow : </i><li>Pick retailer -> <b>Run scan</b> (POST <code>/api/ai/schema/scan</code>).</li><li>Review progress and dictionary tags (S02 LIBQUERY reads).</li><li>Re-run after GOLD upgrades or new modules.</li></div>]', TOBDESC2=q'[<div><i class="bbs-keywords">When to use : </i>Before authoring skills or SQL templates, when validating table names for a new retailer, or after GOLD schema changes.</div>]', TOBDMAJ=SYSDATE, TOBUTIL='admin'
WHEN NOT MATCHED THEN INSERT (TOBID,TOBCAT,TOBDESC,TOBDESC2,TOBLANGUE,TOBDCRE,TOBDMAJ,TOBUTIL) VALUES ('SCR0000000054','Schema Discovery (S02)',q'[<div><i class="bbs-keywords">What is it : </i>Scans the retailer GOLD database (via DB link) and catalogs tables, columns, comments, and samples into ICR <code>AI_SCHEMA_*</code> tables for designers and the AI engine.</div><div><i class="bbs-keywords">Workflow : </i><li>Pick retailer -> <b>Run scan</b> (POST <code>/api/ai/schema/scan</code>).</li><li>Review progress and dictionary tags (S02 LIBQUERY reads).</li><li>Re-run after GOLD upgrades or new modules.</li></div>]',q'[<div><i class="bbs-keywords">When to use : </i>Before authoring skills or SQL templates, when validating table names for a new retailer, or after GOLD schema changes.</div>]','us_US',SYSDATE,SYSDATE,'admin');

MERGE INTO TRA_TECHOBJ t USING (SELECT 'SCR0000000055' TOBID, 'us_US' TOBLANGUE FROM DUAL) s
ON (t.TOBID = s.TOBID AND t.TOBLANGUE = s.TOBLANGUE)
WHEN MATCHED THEN UPDATE SET TOBCAT='Context Learning (S03)', TOBDESC=q'[<div><i class="bbs-keywords">What is it : </i>Guided Q and A to learn retailer-specific GOLD business rules for the <b>15 knowledge catalog</b> items (active item, stock, promotions, DSD, etc.). Locked answers drive generated Oracle views such as <code>V_GOLD_ACTIVE_ITEM_{retailer}</code>.</div><div><i class="bbs-keywords">Workflow : </i><li>Start session -> answer prompts per catalog item.</li><li>Propose / validate SQL conditions -> lock at high confidence.</li><li>Item Active lock can trigger view generation procedure.</li></div>]', TOBDESC2=q'[<div><i class="bbs-keywords">When to use : </i>After retailer setup and schema discovery; required before reliable item/vendor skills and operational views for that retailer.</div>]', TOBDMAJ=SYSDATE, TOBUTIL='admin'
WHEN NOT MATCHED THEN INSERT (TOBID,TOBCAT,TOBDESC,TOBDESC2,TOBLANGUE,TOBDCRE,TOBDMAJ,TOBUTIL) VALUES ('SCR0000000055','Context Learning (S03)',q'[<div><i class="bbs-keywords">What is it : </i>Guided Q and A to learn retailer-specific GOLD business rules for the <b>15 knowledge catalog</b> items (active item, stock, promotions, DSD, etc.). Locked answers drive generated Oracle views such as <code>V_GOLD_ACTIVE_ITEM_{retailer}</code>.</div><div><i class="bbs-keywords">Workflow : </i><li>Start session -> answer prompts per catalog item.</li><li>Propose / validate SQL conditions -> lock at high confidence.</li><li>Item Active lock can trigger view generation procedure.</li></div>]',q'[<div><i class="bbs-keywords">When to use : </i>After retailer setup and schema discovery; required before reliable item/vendor skills and operational views for that retailer.</div>]','us_US',SYSDATE,SYSDATE,'admin');

MERGE INTO TRA_TECHOBJ t USING (SELECT 'SCR0000000056' TOBID, 'us_US' TOBLANGUE FROM DUAL) s
ON (t.TOBID = s.TOBID AND t.TOBLANGUE = s.TOBLANGUE)
WHEN MATCHED THEN UPDATE SET TOBCAT='Skill Studio - Library', TOBDESC=q'[<div><i class="bbs-keywords">What is it : </i>Catalog of <b>AI skills</b> (business capabilities) and starter templates. Each skill bundles vocabulary, playbook hints, and SQL templates used by the engine router and executor.</div><div><i class="bbs-keywords">Workflow : </i><li>Browse / filter skills by domain.</li><li>Open a skill in <b>Skill Builder</b> or create from template.</li><li>Enable/disable skills per retailer deployment.</li></div>]', TOBDESC2=q'[<div><i class="bbs-keywords">When to use : </i>Design-time - expanding what questions the AI Assistant can answer (DSD vendor, item master, diagnostics, etc.).</div>]', TOBDMAJ=SYSDATE, TOBUTIL='admin'
WHEN NOT MATCHED THEN INSERT (TOBID,TOBCAT,TOBDESC,TOBDESC2,TOBLANGUE,TOBDCRE,TOBDMAJ,TOBUTIL) VALUES ('SCR0000000056','Skill Studio - Library',q'[<div><i class="bbs-keywords">What is it : </i>Catalog of <b>AI skills</b> (business capabilities) and starter templates. Each skill bundles vocabulary, playbook hints, and SQL templates used by the engine router and executor.</div><div><i class="bbs-keywords">Workflow : </i><li>Browse / filter skills by domain.</li><li>Open a skill in <b>Skill Builder</b> or create from template.</li><li>Enable/disable skills per retailer deployment.</li></div>]',q'[<div><i class="bbs-keywords">When to use : </i>Design-time - expanding what questions the AI Assistant can answer (DSD vendor, item master, diagnostics, etc.).</div>]','us_US',SYSDATE,SYSDATE,'admin');

MERGE INTO TRA_TECHOBJ t USING (SELECT 'SCR0000000057' TOBID, 'us_US' TOBLANGUE FROM DUAL) s
ON (t.TOBID = s.TOBID AND t.TOBLANGUE = s.TOBLANGUE)
WHEN MATCHED THEN UPDATE SET TOBCAT='Skill Studio - Builder', TOBDESC=q'[<div><i class="bbs-keywords">What is it : </i>Authoring workspace for one skill: <b>vocabulary</b> (INTENT_PHRASE, BIND_HINT, jargon), <b>playbook</b>, and <b>SQL templates</b> with <code>parameters_json</code> bind definitions - stored via LIBQUERY bundle posts.</div><div><i class="bbs-keywords">Tabs : </i><li><b>General</b> - skill metadata.</li><li><b>Vocabulary / Playbook / SQL templates</b> - engine-facing content.</li><li><b>Diagnostic steps</b> - optional rule-based chains (when deployed).</li></div>]', TOBDESC2=q'[<div><i class="bbs-keywords">When to use : </i>Creating or tuning a skill after playground/phrasing tests; keep template SQL on GOLD objects discovered in S02.</div>]', TOBDMAJ=SYSDATE, TOBUTIL='admin'
WHEN NOT MATCHED THEN INSERT (TOBID,TOBCAT,TOBDESC,TOBDESC2,TOBLANGUE,TOBDCRE,TOBDMAJ,TOBUTIL) VALUES ('SCR0000000057','Skill Studio - Builder',q'[<div><i class="bbs-keywords">What is it : </i>Authoring workspace for one skill: <b>vocabulary</b> (INTENT_PHRASE, BIND_HINT, jargon), <b>playbook</b>, and <b>SQL templates</b> with <code>parameters_json</code> bind definitions - stored via LIBQUERY bundle posts.</div><div><i class="bbs-keywords">Tabs : </i><li><b>General</b> - skill metadata.</li><li><b>Vocabulary / Playbook / SQL templates</b> - engine-facing content.</li><li><b>Diagnostic steps</b> - optional rule-based chains (when deployed).</li></div>]',q'[<div><i class="bbs-keywords">When to use : </i>Creating or tuning a skill after playground/phrasing tests; keep template SQL on GOLD objects discovered in S02.</div>]','us_US',SYSDATE,SYSDATE,'admin');

MERGE INTO TRA_TECHOBJ t USING (SELECT 'SCR0000000058' TOBID, 'us_US' TOBLANGUE FROM DUAL) s
ON (t.TOBID = s.TOBID AND t.TOBLANGUE = s.TOBLANGUE)
WHEN MATCHED THEN UPDATE SET TOBCAT='Pending phrasings (S22)', TOBDESC=q'[<div><i class="bbs-keywords">What is it : </i>Admin <b>curation queue</b> for questions the engine could not route confidently (<code>AI_ENGINE_UNRESOLVED</code>): thumbs-down, low-confidence routes, and user overrides from the Assistant.</div><div><i class="bbs-keywords">Workflow : </i><li>Review pending phrasing -> promote to skill vocabulary or dismiss.</li><li><b>Auto-promote eligible</b> - bulk MERGE after repeat USER_OVERRIDE patterns.</li></div>]', TOBDESC2=q'[<div><i class="bbs-keywords">When to use : </i>Weekly designer hygiene so analyst language in the Assistant improves without Node deploys.</div>]', TOBDMAJ=SYSDATE, TOBUTIL='admin'
WHEN NOT MATCHED THEN INSERT (TOBID,TOBCAT,TOBDESC,TOBDESC2,TOBLANGUE,TOBDCRE,TOBDMAJ,TOBUTIL) VALUES ('SCR0000000058','Pending phrasings (S22)',q'[<div><i class="bbs-keywords">What is it : </i>Admin <b>curation queue</b> for questions the engine could not route confidently (<code>AI_ENGINE_UNRESOLVED</code>): thumbs-down, low-confidence routes, and user overrides from the Assistant.</div><div><i class="bbs-keywords">Workflow : </i><li>Review pending phrasing -> promote to skill vocabulary or dismiss.</li><li><b>Auto-promote eligible</b> - bulk MERGE after repeat USER_OVERRIDE patterns.</li></div>]',q'[<div><i class="bbs-keywords">When to use : </i>Weekly designer hygiene so analyst language in the Assistant improves without Node deploys.</div>]','us_US',SYSDATE,SYSDATE,'admin');

MERGE INTO TRA_TECHOBJ t USING (SELECT 'SCR0000000059' TOBID, 'us_US' TOBLANGUE FROM DUAL) s
ON (t.TOBID = s.TOBID AND t.TOBLANGUE = s.TOBLANGUE)
WHEN MATCHED THEN UPDATE SET TOBCAT='Phrasing Playground (S23)', TOBDESC=q'[<div><i class="bbs-keywords">What is it : </i>Designer sandbox for <code>POST /api/ai/engine/diagnose</code> - shows skill scores, vocabulary hits, lexical pipeline, bind feasibility, and dampened INTENT_PHRASEs <em>without</em> running SQL or writing to the DB.</div><div><i class="bbs-keywords">Workflow : </i><li>Enter natural-language question + retailer.</li><li>Inspect top skills and why the router won or lost.</li><li>Adjust vocabulary in Skill Builder based on results.</li></div>]', TOBDESC2=q'[<div><i class="bbs-keywords">When to use : </i>Debugging misroutes (e.g. item vs vendor skills) before changing production vocabulary packs.</div>]', TOBDMAJ=SYSDATE, TOBUTIL='admin'
WHEN NOT MATCHED THEN INSERT (TOBID,TOBCAT,TOBDESC,TOBDESC2,TOBLANGUE,TOBDCRE,TOBDMAJ,TOBUTIL) VALUES ('SCR0000000059','Phrasing Playground (S23)',q'[<div><i class="bbs-keywords">What is it : </i>Designer sandbox for <code>POST /api/ai/engine/diagnose</code> - shows skill scores, vocabulary hits, lexical pipeline, bind feasibility, and dampened INTENT_PHRASEs <em>without</em> running SQL or writing to the DB.</div><div><i class="bbs-keywords">Workflow : </i><li>Enter natural-language question + retailer.</li><li>Inspect top skills and why the router won or lost.</li><li>Adjust vocabulary in Skill Builder based on results.</li></div>]',q'[<div><i class="bbs-keywords">When to use : </i>Debugging misroutes (e.g. item vs vendor skills) before changing production vocabulary packs.</div>]','us_US',SYSDATE,SYSDATE,'admin');

MERGE INTO TRA_TECHOBJ t USING (SELECT 'SCR0000000060' TOBID, 'us_US' TOBLANGUE FROM DUAL) s
ON (t.TOBID = s.TOBID AND t.TOBLANGUE = s.TOBLANGUE)
WHEN MATCHED THEN UPDATE SET TOBCAT='Supply Chain Assistant (S14)', TOBDESC=q'[<div><i class="bbs-keywords">What is it : </i>Analyst <b>natural-language</b> interface: routes the question to a skill, resolves binds (vendor, store, item), runs GOLD SQL templates, and returns a summarized answer with optional result tables.</div><div><i class="bbs-keywords">Workflow : </i><li>Ask in plain language -> review confidence and clarification chips if low.</li><li>Execute -> human summary + evidence + export.</li><li>Thumbs feedback feeds the phrasing curation queue.</li></div>]', TOBDESC2=q'[<div><i class="bbs-keywords">Tips : </i><li>Item card follow-ups (add retail, EAN) work on the same LU after an item header result.</li><li>Admins see engine diagnostics; analysts see chat + inline results only.</li></div>]', TOBDMAJ=SYSDATE, TOBUTIL='admin'
WHEN NOT MATCHED THEN INSERT (TOBID,TOBCAT,TOBDESC,TOBDESC2,TOBLANGUE,TOBDCRE,TOBDMAJ,TOBUTIL) VALUES ('SCR0000000060','Supply Chain Assistant (S14)',q'[<div><i class="bbs-keywords">What is it : </i>Analyst <b>natural-language</b> interface: routes the question to a skill, resolves binds (vendor, store, item), runs GOLD SQL templates, and returns a summarized answer with optional result tables.</div><div><i class="bbs-keywords">Workflow : </i><li>Ask in plain language -> review confidence and clarification chips if low.</li><li>Execute -> human summary + evidence + export.</li><li>Thumbs feedback feeds the phrasing curation queue.</li></div>]',q'[<div><i class="bbs-keywords">Tips : </i><li>Item card follow-ups (add retail, EAN) work on the same LU after an item header result.</li><li>Admins see engine diagnostics; analysts see chat + inline results only.</li></div>]','us_US',SYSDATE,SYSDATE,'admin');

MERGE INTO TRA_TECHOBJ t USING (SELECT 'SCR0000000061' TOBID, 'us_US' TOBLANGUE FROM DUAL) s
ON (t.TOBID = s.TOBID AND t.TOBLANGUE = s.TOBLANGUE)
WHEN MATCHED THEN UPDATE SET TOBCAT='AI Data Health (S24)', TOBDESC=q'[<div><i class="bbs-keywords">What is it : </i>Operational <b>data pipeline monitor</b> - card grid of checks (item, ranging, orders, receipts, stock, sales) with severity, trend, and last-run status from <code>AI_DATA_CHECK_RESULT</code>.</div><div><i class="bbs-keywords">Workflow : </i><li>Filter by retailer and schedule tier (realtime / hourly / nightly).</li><li><b>Run now</b> triggers <code>AI_RUN_DATA_CHECKS</code> for a tier.</li><li><b>History</b> -> drill-down rows; <b>Investigate</b> opens Assistant with context.</li></div>]', TOBDESC2=q'[<div><i class="bbs-keywords">When to use : </i>Morning operational review before replenishment/blocker analysis - catches silent feed failures (POS, receipts) and master-data gaps.</div>]', TOBDMAJ=SYSDATE, TOBUTIL='admin'
WHEN NOT MATCHED THEN INSERT (TOBID,TOBCAT,TOBDESC,TOBDESC2,TOBLANGUE,TOBDCRE,TOBDMAJ,TOBUTIL) VALUES ('SCR0000000061','AI Data Health (S24)',q'[<div><i class="bbs-keywords">What is it : </i>Operational <b>data pipeline monitor</b> - card grid of checks (item, ranging, orders, receipts, stock, sales) with severity, trend, and last-run status from <code>AI_DATA_CHECK_RESULT</code>.</div><div><i class="bbs-keywords">Workflow : </i><li>Filter by retailer and schedule tier (realtime / hourly / nightly).</li><li><b>Run now</b> triggers <code>AI_RUN_DATA_CHECKS</code> for a tier.</li><li><b>History</b> -> drill-down rows; <b>Investigate</b> opens Assistant with context.</li></div>]',q'[<div><i class="bbs-keywords">When to use : </i>Morning operational review before replenishment/blocker analysis - catches silent feed failures (POS, receipts) and master-data gaps.</div>]','us_US',SYSDATE,SYSDATE,'admin');

MERGE INTO TRA_TECHOBJ t USING (SELECT 'SCR0000000062' TOBID, 'us_US' TOBLANGUE FROM DUAL) s
ON (t.TOBID = s.TOBID AND t.TOBLANGUE = s.TOBLANGUE)
WHEN MATCHED THEN UPDATE SET TOBCAT='Data Health Configuration (S25)', TOBDESC=q'[<div><i class="bbs-keywords">What is it : </i>Admin CRUD for <code>AI_DATA_CHECK_DEF</code>: check code, category, severity, schedule tier, LIBQUERY count/detail ids, optional drill skill, enable flag.</div><div><i class="bbs-keywords">Workflow : </i><li><b>Verify</b> runs the COUNT LIBQUERY before save.</li><li><b>Test</b> runs one check via <code>AI_RUN_DATA_CHECKS</code>.</li><li>Toggle active without deleting definition.</li></div>]', TOBDESC2=q'[<div><i class="bbs-keywords">When to use : </i>Adding a new pipeline check without a DB deployment - SQL body lives in LIBQUERY; this screen only registers the catalog row.</div>]', TOBDMAJ=SYSDATE, TOBUTIL='admin'
WHEN NOT MATCHED THEN INSERT (TOBID,TOBCAT,TOBDESC,TOBDESC2,TOBLANGUE,TOBDCRE,TOBDMAJ,TOBUTIL) VALUES ('SCR0000000062','Data Health Configuration (S25)',q'[<div><i class="bbs-keywords">What is it : </i>Admin CRUD for <code>AI_DATA_CHECK_DEF</code>: check code, category, severity, schedule tier, LIBQUERY count/detail ids, optional drill skill, enable flag.</div><div><i class="bbs-keywords">Workflow : </i><li><b>Verify</b> runs the COUNT LIBQUERY before save.</li><li><b>Test</b> runs one check via <code>AI_RUN_DATA_CHECKS</code>.</li><li>Toggle active without deleting definition.</li></div>]',q'[<div><i class="bbs-keywords">When to use : </i>Adding a new pipeline check without a DB deployment - SQL body lives in LIBQUERY; this screen only registers the catalog row.</div>]','us_US',SYSDATE,SYSDATE,'admin');

MERGE INTO TRA_TECHOBJ t USING (SELECT 'SCR0000000063' TOBID, 'us_US' TOBLANGUE FROM DUAL) s
ON (t.TOBID = s.TOBID AND t.TOBLANGUE = s.TOBLANGUE)
WHEN MATCHED THEN UPDATE SET TOBCAT='Alerts journal', TOBDESC=q'[<div><i class="bbs-keywords">What is it : </i>Run history for ICR <b>scheduled and on-demand alerts</b>. Each row in <code>ALERTLOG</code> is one execution: alert id, request id, status, phase, duration, row count, and error text.</div><div><i class="bbs-keywords">Views : </i><li><b>Live</b> - recent runs with auto-refresh.</li><li><b>Weekly / Monthly</b> - duration trends and execution volume charts.</li><li><b>Detail</b> - full log fields for a selected run.</li></div>]', TOBDESC2=q'[<div><i class="bbs-keywords">When to use : </i>Troubleshooting failed or timeout alerts, confirming a cron job fired (pair with <b>Critical Alert Watchdog</b>), or reviewing row counts before changing alert SQL on Alerts management.</div>]', TOBDMAJ=SYSDATE, TOBUTIL='admin'
WHEN NOT MATCHED THEN INSERT (TOBID,TOBCAT,TOBDESC,TOBDESC2,TOBLANGUE,TOBDCRE,TOBDMAJ,TOBUTIL) VALUES ('SCR0000000063','Alerts journal',q'[<div><i class="bbs-keywords">What is it : </i>Run history for ICR <b>scheduled and on-demand alerts</b>. Each row in <code>ALERTLOG</code> is one execution: alert id, request id, status, phase, duration, row count, and error text.</div><div><i class="bbs-keywords">Views : </i><li><b>Live</b> - recent runs with auto-refresh.</li><li><b>Weekly / Monthly</b> - duration trends and execution volume charts.</li><li><b>Detail</b> - full log fields for a selected run.</li></div>]',q'[<div><i class="bbs-keywords">When to use : </i>Troubleshooting failed or timeout alerts, confirming a cron job fired (pair with <b>Critical Alert Watchdog</b>), or reviewing row counts before changing alert SQL on Alerts management.</div>]','us_US',SYSDATE,SYSDATE,'admin');

COMMIT;

SET DEFINE ON;
