-- TRA_TECHOBJ - General Settings admin screens (info overlay on hover)
-- Deploy to ICR app DB after 56_tra_techobj_supply_chain_ai_watchdog.sql (or standalone).
-- Screen IDs must match Angular screenID on each app-page-header (SCR0000000064-0069).
-- ASCII punctuation only (no em dash) for WE8MSWIN / Latin-1 client compatibility.

SET DEFINE OFF;

MERGE INTO TRA_TECHOBJ t USING (SELECT 'SCR0000000064' TOBID, 'us_US' TOBLANGUE FROM DUAL) s
ON (t.TOBID = s.TOBID AND t.TOBLANGUE = s.TOBLANGUE)
WHEN MATCHED THEN UPDATE SET TOBCAT='Retailer and Access', TOBDESC=q'[<div><i class="bbs-keywords">What is it : </i>Admin setup for <b>corporates</b> (<code>CORPORATE</code>) and their <b>GOLD environments</b> (<code>CORPENV</code>: connection, DB link, schema prefix).</div><div><i class="bbs-keywords">Tabs : </i><li><b>Corporate</b> - retailer code, descriptions, active flag.</li><li><b>Environment</b> - IP, port, SID, DB link name, GOLD schema per corporate.</li></div>]', TOBDESC2=q'[<div><i class="bbs-keywords">When to use : </i>Onboarding a new retailer, adding preprod/prod GOLD links, or fixing connection metadata before Supply Chain AI retailer setup or alerts.</div>]', TOBDMAJ=SYSDATE, TOBUTIL='admin'
WHEN NOT MATCHED THEN INSERT (TOBID,TOBCAT,TOBDESC,TOBDESC2,TOBLANGUE,TOBDCRE,TOBDMAJ,TOBUTIL) VALUES ('SCR0000000064','Retailer and Access',q'[<div><i class="bbs-keywords">What is it : </i>Admin setup for <b>corporates</b> (<code>CORPORATE</code>) and their <b>GOLD environments</b> (<code>CORPENV</code>: connection, DB link, schema prefix).</div><div><i class="bbs-keywords">Tabs : </i><li><b>Corporate</b> - retailer code, descriptions, active flag.</li><li><b>Environment</b> - IP, port, SID, DB link name, GOLD schema per corporate.</li></div>]',q'[<div><i class="bbs-keywords">When to use : </i>Onboarding a new retailer, adding preprod/prod GOLD links, or fixing connection metadata before Supply Chain AI retailer setup or alerts.</div>]','us_US',SYSDATE,SYSDATE,'admin');

MERGE INTO TRA_TECHOBJ t USING (SELECT 'SCR0000000065' TOBID, 'us_US' TOBLANGUE FROM DUAL) s
ON (t.TOBID = s.TOBID AND t.TOBLANGUE = s.TOBLANGUE)
WHEN MATCHED THEN UPDATE SET TOBCAT='Users and Profiles', TOBDESC=q'[<div><i class="bbs-keywords">What is it : </i>ICR login accounts in <code>USERSROOM</code>: corporate assignment (<code>USERCORPID</code>), capability flags (buyer, IT, AI admin, etc.), optional <b>access profile</b> (<code>USERPROF</code>), and password (Base64 in DB).</div><div><i class="bbs-keywords">Tabs : </i><li><b>Users</b> - search, add, duplicate, edit, delete.</li><li><b>Environment access</b> - matrix of which user may use which <code>CORPENV</code>.</li></div>]', TOBDESC2=q'[<div><i class="bbs-keywords">When to use : </i>New hire access, promoting AI designer/admin, or pairing with <b>Menu and access</b> profiles. Users must log out and back in after flag or profile changes.</div>]', TOBDMAJ=SYSDATE, TOBUTIL='admin'
WHEN NOT MATCHED THEN INSERT (TOBID,TOBCAT,TOBDESC,TOBDESC2,TOBLANGUE,TOBDCRE,TOBDMAJ,TOBUTIL) VALUES ('SCR0000000065','Users and Profiles',q'[<div><i class="bbs-keywords">What is it : </i>ICR login accounts in <code>USERSROOM</code>: corporate assignment (<code>USERCORPID</code>), capability flags (buyer, IT, AI admin, etc.), optional <b>access profile</b> (<code>USERPROF</code>), and password (Base64 in DB).</div><div><i class="bbs-keywords">Tabs : </i><li><b>Users</b> - search, add, duplicate, edit, delete.</li><li><b>Environment access</b> - matrix of which user may use which <code>CORPENV</code>.</li></div>]',q'[<div><i class="bbs-keywords">When to use : </i>New hire access, promoting AI designer/admin, or pairing with <b>Menu and access</b> profiles. Users must log out and back in after flag or profile changes.</div>]','us_US',SYSDATE,SYSDATE,'admin');

MERGE INTO TRA_TECHOBJ t USING (SELECT 'SCR0000000066' TOBID, 'us_US' TOBLANGUE FROM DUAL) s
ON (t.TOBID = s.TOBID AND t.TOBLANGUE = s.TOBLANGUE)
WHEN MATCHED THEN UPDATE SET TOBCAT='Menu and access', TOBDESC=q'[<div><i class="bbs-keywords">What is it : </i>Data-driven navigation: <code>ICR_MENU_ENTRY</code> catalog, <code>ICR_MENU_ACCESS_RULE</code> (flag-based), <code>ICR_ACCESS_PROFILE</code> + <code>ICR_PROFILE_MENU</code> (curated bundles). Replaces hard-coded sidebar for Heinens ICR.</div><div><i class="bbs-keywords">Tabs : </i><li><b>Menu catalog</b> - routes, icons, active flag.</li><li><b>Flag rules</b> - which <code>USERSROOM</code> flag unlocks a menu code.</li><li><b>Profiles / Profile menus</b> - bulk grants per profile.</li></div>]', TOBDESC2=q'[<div><i class="bbs-keywords">When to use : </i>Adding a new screen to the sidebar, gating Supply Chain AI or admin tools, or onboarding a team via profile instead of many checkboxes.</div>]', TOBDMAJ=SYSDATE, TOBUTIL='admin'
WHEN NOT MATCHED THEN INSERT (TOBID,TOBCAT,TOBDESC,TOBDESC2,TOBLANGUE,TOBDCRE,TOBDMAJ,TOBUTIL) VALUES ('SCR0000000066','Menu and access',q'[<div><i class="bbs-keywords">What is it : </i>Data-driven navigation: <code>ICR_MENU_ENTRY</code> catalog, <code>ICR_MENU_ACCESS_RULE</code> (flag-based), <code>ICR_ACCESS_PROFILE</code> + <code>ICR_PROFILE_MENU</code> (curated bundles). Replaces hard-coded sidebar for Heinens ICR.</div><div><i class="bbs-keywords">Tabs : </i><li><b>Menu catalog</b> - routes, icons, active flag.</li><li><b>Flag rules</b> - which <code>USERSROOM</code> flag unlocks a menu code.</li><li><b>Profiles / Profile menus</b> - bulk grants per profile.</li></div>]',q'[<div><i class="bbs-keywords">When to use : </i>Adding a new screen to the sidebar, gating Supply Chain AI or admin tools, or onboarding a team via profile instead of many checkboxes.</div>]','us_US',SYSDATE,SYSDATE,'admin');

MERGE INTO TRA_TECHOBJ t USING (SELECT 'SCR0000000067' TOBID, 'us_US' TOBLANGUE FROM DUAL) s
ON (t.TOBID = s.TOBID AND t.TOBLANGUE = s.TOBLANGUE)
WHEN MATCHED THEN UPDATE SET TOBCAT='Query Library', TOBDESC=q'[<div><i class="bbs-keywords">What is it : </i>Central store for all ICR SQL: <code>LIBQUERY</code> rows (<code>QUERYNUM</code>, <code>QUERYSQL</code>, params, access). Every Angular read/write and most batch jobs call these ids via <code>QueryService</code> - no inline SQL in the client.</div><div><i class="bbs-keywords">Workflow : </i><li>Search by query number, title, or description.</li><li>Add/edit SQL, <code>QUERYTYPE</code> (0=SQL text, 1=package), <code>QUERYUPDATE</code> (read vs DML).</li><li><b>Test</b> - run with sample params before save.</li></div>]', TOBDESC2=q'[<div><i class="bbs-keywords">When to use : </i>Shipping a new feature LIBQUERY (AI, settings, alerts), fixing bind placeholders (<code>:param1</code>), or promoting SQL from dev to prod.</div>]', TOBDMAJ=SYSDATE, TOBUTIL='admin'
WHEN NOT MATCHED THEN INSERT (TOBID,TOBCAT,TOBDESC,TOBDESC2,TOBLANGUE,TOBDCRE,TOBDMAJ,TOBUTIL) VALUES ('SCR0000000067','Query Library',q'[<div><i class="bbs-keywords">What is it : </i>Central store for all ICR SQL: <code>LIBQUERY</code> rows (<code>QUERYNUM</code>, <code>QUERYSQL</code>, params, access). Every Angular read/write and most batch jobs call these ids via <code>QueryService</code> - no inline SQL in the client.</div><div><i class="bbs-keywords">Workflow : </i><li>Search by query number, title, or description.</li><li>Add/edit SQL, <code>QUERYTYPE</code> (0=SQL text, 1=package), <code>QUERYUPDATE</code> (read vs DML).</li><li><b>Test</b> - run with sample params before save.</li></div>]',q'[<div><i class="bbs-keywords">When to use : </i>Shipping a new feature LIBQUERY (AI, settings, alerts), fixing bind placeholders (<code>:param1</code>), or promoting SQL from dev to prod.</div>]','us_US',SYSDATE,SYSDATE,'admin');

MERGE INTO TRA_TECHOBJ t USING (SELECT 'SCR0000000068' TOBID, 'us_US' TOBLANGUE FROM DUAL) s
ON (t.TOBID = s.TOBID AND t.TOBLANGUE = s.TOBLANGUE)
WHEN MATCHED THEN UPDATE SET TOBCAT='Dictionary', TOBDESC=q'[<div><i class="bbs-keywords">What is it : </i>Translation and metadata maintenance for the UI: <code>TRA_TECHOBJ</code> (screen help HTML), <code>TRA_LABELS</code> (menu/field text), <code>TRA_PARAMETERS</code> + <code>TRA_ENTRIES</code> (dropdown values).</div><div><i class="bbs-keywords">Tabs : </i><li><b>Technical Objects</b> - screen ids and info overlay content (this help system).</li><li><b>Labels / Parameters / Entries</b> - localized strings and lists.</li></div>]', TOBDESC2=q'[<div><i class="bbs-keywords">When to use : </i>Adding or editing screen info for a new route, fixing label typos, or extending parameter lists without a code deploy.</div>]', TOBDMAJ=SYSDATE, TOBUTIL='admin'
WHEN NOT MATCHED THEN INSERT (TOBID,TOBCAT,TOBDESC,TOBDESC2,TOBLANGUE,TOBDCRE,TOBDMAJ,TOBUTIL) VALUES ('SCR0000000068','Dictionary',q'[<div><i class="bbs-keywords">What is it : </i>Translation and metadata maintenance for the UI: <code>TRA_TECHOBJ</code> (screen help HTML), <code>TRA_LABELS</code> (menu/field text), <code>TRA_PARAMETERS</code> + <code>TRA_ENTRIES</code> (dropdown values).</div><div><i class="bbs-keywords">Tabs : </i><li><b>Technical Objects</b> - screen ids and info overlay content (this help system).</li><li><b>Labels / Parameters / Entries</b> - localized strings and lists.</li></div>]',q'[<div><i class="bbs-keywords">When to use : </i>Adding or editing screen info for a new route, fixing label typos, or extending parameter lists without a code deploy.</div>]','us_US',SYSDATE,SYSDATE,'admin');

MERGE INTO TRA_TECHOBJ t USING (SELECT 'SCR0000000069' TOBID, 'us_US' TOBLANGUE FROM DUAL) s
ON (t.TOBID = s.TOBID AND t.TOBLANGUE = s.TOBLANGUE)
WHEN MATCHED THEN UPDATE SET TOBCAT='Widget Library', TOBDESC=q'[<div><i class="bbs-keywords">What is it : </i>Catalog of <b>dashboard widgets</b> (<code>PKWIDGET</code>): layout (grid x/y/width/height), behavior (table, chart, message), and linked <code>LIBQUERY</code> (often <code>QUERYTYPE=2</code> widget queries).</div><div><i class="bbs-keywords">Workflow : </i><li>Define widget id, title, and display type.</li><li>Attach query numbers for data and chart axes.</li><li>Users enable widgets on the <b>Dashboard</b> home screen.</li></div>]', TOBDESC2=q'[<div><i class="bbs-keywords">When to use : </i>Adding operational KPI tiles to the ICR home page. Pair with Query Library for the underlying SQL. (Route <code>/settingwidget</code> must be registered in the Angular app when this admin UI is deployed.)</div>]', TOBDMAJ=SYSDATE, TOBUTIL='admin'
WHEN NOT MATCHED THEN INSERT (TOBID,TOBCAT,TOBDESC,TOBDESC2,TOBLANGUE,TOBDCRE,TOBDMAJ,TOBUTIL) VALUES ('SCR0000000069','Widget Library',q'[<div><i class="bbs-keywords">What is it : </i>Catalog of <b>dashboard widgets</b> (<code>PKWIDGET</code>): layout (grid x/y/width/height), behavior (table, chart, message), and linked <code>LIBQUERY</code> (often <code>QUERYTYPE=2</code> widget queries).</div><div><i class="bbs-keywords">Workflow : </i><li>Define widget id, title, and display type.</li><li>Attach query numbers for data and chart axes.</li><li>Users enable widgets on the <b>Dashboard</b> home screen.</li></div>]',q'[<div><i class="bbs-keywords">When to use : </i>Adding operational KPI tiles to the ICR home page. Pair with Query Library for the underlying SQL. (Route <code>/settingwidget</code> must be registered in the Angular app when this admin UI is deployed.)</div>]','us_US',SYSDATE,SYSDATE,'admin');

COMMIT;

SET DEFINE ON;
