-- Alerts management LIBQUERY (ICR app DB)
-- Exported from CENPRDPDB 2026-05-22 — canonical DELETE+INSERT bundle for repo deploy.
--
-- GET reads (ALT0000001–0003): QUERYTYPE=1 → PKQUERYMANAGER.GETQUERY_ALT* (package must exist).
-- POST DML (ALT0000010, 0012, 0020, 0022, 0030, 0032): QUERYTYPE=0, JSON_TABLE on REQUEST_QUERY_BODY.
--
-- Re-export: @58_export_alerts_libquery.sql

SET DEFINE OFF;

DELETE FROM LIBQUERY WHERE QUERYNUM IN (
  'ALT0000001', 'ALT0000002', 'ALT0000003',
  'ALT0000010', 'ALT0000012',
  'ALT0000020', 'ALT0000022',
  'ALT0000030', 'ALT0000032'
);

-- ALT0000001 — Alert information (GET, package)
INSERT INTO LIBQUERY (
  QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL,
  QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE
)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'ALT0000001',
       'Alert information',
       'Request for the alerts info lookup',
       q'~
PKQUERYMANAGER.GETQUERY_ALT0000001
~',
       '{:USERID, :DATABASE_SID,:LISTE_PARAM,:LANGUAGE}',
       '',
       1,
       1,
       0
  FROM dual;

-- ALT0000002 — Alert distribution information (GET, package)
INSERT INTO LIBQUERY (
  QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL,
  QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE
)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'ALT0000002',
       'Alert distribution information',
       'Request for the alerts distribution info lookup',
       q'~
PKQUERYMANAGER.GETQUERY_ALT0000002
~',
       '{:USERID, :DATABASE_SID,:LISTE_PARAM,:LANGUAGE}',
       '',
       1,
       1,
       0
  FROM dual;

-- ALT0000003 — Alert schedule information (GET, package)
INSERT INTO LIBQUERY (
  QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL,
  QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE
)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'ALT0000003',
       'Alert schedule information',
       'Request for the alerts schedule info lookup',
       q'~
PKQUERYMANAGER.GETQUERY_ALT0000003
~',
       '{:USERID, :DATABASE_SID,:LISTE_PARAM,:LANGUAGE}',
       '',
       1,
       1,
       0
  FROM dual;

-- ALT0000010 — Merge Alert (POST DML)
INSERT INTO LIBQUERY (
  QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL,
  QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE
)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'ALT0000010',
       'Merge Alert',
       'Merge alert (insert or update)',
       q'~
MERGE INTO ALERTS t
USING (
    SELECT *
    FROM json_table((SELECT REQUESTBODY
                     FROM REQUEST_QUERY_BODY
                     WHERE REQUESTID = :param1),
            '$.values[*]' COLUMNS(
                ALTID PATH '$."ALTID"',
                ALTQUERY PATH '$."ALTQUERY"',
                ALTSUBJECT PATH '$."ALTSUBJECT"',
                ALTCONTENT PATH '$."ALTCONTENT"',
                ALTUTIL PATH '$."ALTUTIL"',
                ALTFILE PATH '$."ALTFILE"',
                ALTREALTIME NUMBER PATH '$."ALTREALTIME"',
                ALTSMSCONTENT PATH '$."ALTSMSCONTENT"',
                ALTORIENTATION PATH '$."ALTORIENTATION"',
                ALTPRINTAREA PATH '$."ALTPRINTAREA"',
                ALTMARGIN PATH '$."ALTMARGIN"',
                ALTFITPAGE NUMBER PATH '$."ALTFITPAGE"',
                ALTFITHEIGHT NUMBER PATH '$."ALTFITHEIGHT"',
                ALTFITWIDTH NUMBER PATH '$."ALTFITWIDTH"',
                ALTTITLEREPEAT PATH '$."ALTTITLEREPEAT"',
                ALTFOOTER PATH '$."ALTFOOTER"',
                ALTFORMAT PATH '$."ALTFORMAT"',
                ALTFORMATXLS PATH '$."ALTFORMATXLS"',
                ALTCONTENTHTML PATH '$."ALTCONTENTHTML"',
                ALTXLSBREAK PATH '$."ALTXLSBREAK"',
                ALTSCALE NUMBER PATH '$."ALTSCALE"',
                ALTCOLMOVE PATH '$."ALTCOLMOVE"',
                ALTNBPARAM NUMBER PATH '$."ALTNBPARAM"',
                ALTPARAMDESC PATH '$."ALTPARAMDESC"',
                ALTBORDER NUMBER PATH '$."ALTBORDER"',
                ALTTITLEXLS PATH '$."ALTTITLEXLS"',
                ALTTITLEXLSCOLOR PATH '$."ALTTITLEXLSCOLOR"',
                ALTFREEZEHEADER NUMBER PATH '$."ALTFREEZEHEADER"',
                ALTFREEZECOLUMN NUMBER PATH '$."ALTFREEZECOLUMN"',
                ALTFORMATTAB2XLS PATH '$."ALTFORMATTAB2XLS"',
                ALTNOHTML NUMBER PATH '$."ALTNOHTML"',
                ALTSQL CLOB PATH '$."ALTSQL"'
            ))
) s
ON (t.ALTID = s.ALTID)
WHEN MATCHED THEN
    UPDATE SET
        t.ALTQUERY = s.ALTQUERY, t.ALTSUBJECT = s.ALTSUBJECT, t.ALTCONTENT = s.ALTCONTENT,
        t.ALTDMAJ = SYSDATE, t.ALTUTIL = s.ALTUTIL, t.ALTFILE = s.ALTFILE,
        t.ALTREALTIME = s.ALTREALTIME, t.ALTSMSCONTENT = s.ALTSMSCONTENT,
        t.ALTORIENTATION = s.ALTORIENTATION, t.ALTPRINTAREA = s.ALTPRINTAREA,
        t.ALTMARGIN = s.ALTMARGIN, t.ALTFITPAGE = s.ALTFITPAGE,
        t.ALTFITHEIGHT = s.ALTFITHEIGHT, t.ALTFITWIDTH = s.ALTFITWIDTH,
        t.ALTTITLEREPEAT = s.ALTTITLEREPEAT, t.ALTFOOTER = s.ALTFOOTER,
        t.ALTFORMAT = s.ALTFORMAT, t.ALTFORMATXLS = s.ALTFORMATXLS,
        t.ALTCONTENTHTML = s.ALTCONTENTHTML, t.ALTXLSBREAK = s.ALTXLSBREAK,
        t.ALTSCALE = s.ALTSCALE, t.ALTCOLMOVE = s.ALTCOLMOVE,
        t.ALTNBPARAM = s.ALTNBPARAM, t.ALTPARAMDESC = s.ALTPARAMDESC,
        t.ALTBORDER = s.ALTBORDER, t.ALTTITLEXLS = s.ALTTITLEXLS,
        t.ALTTITLEXLSCOLOR = s.ALTTITLEXLSCOLOR, t.ALTFREEZEHEADER = s.ALTFREEZEHEADER,
        t.ALTFREEZECOLUMN = s.ALTFREEZECOLUMN, t.ALTFORMATTAB2XLS = s.ALTFORMATTAB2XLS,
        t.ALTNOHTML = s.ALTNOHTML, t.ALTSQL = s.ALTSQL
WHEN NOT MATCHED THEN
    INSERT (ALTID, ALTQUERY, ALTSUBJECT, ALTCONTENT, ALTDCRE, ALTDMAJ, ALTUTIL,
            ALTFILE, ALTREALTIME, ALTSMSCONTENT, ALTORIENTATION, ALTPRINTAREA,
            ALTMARGIN, ALTFITPAGE, ALTFITHEIGHT, ALTFITWIDTH, ALTTITLEREPEAT,
            ALTFOOTER, ALTFORMAT, ALTFORMATXLS, ALTCONTENTHTML, ALTXLSBREAK,
            ALTSCALE, ALTCOLMOVE, ALTNBPARAM, ALTPARAMDESC, ALTBORDER,
            ALTTITLEXLS, ALTTITLEXLSCOLOR, ALTFREEZEHEADER, ALTFREEZECOLUMN,
            ALTFORMATTAB2XLS, ALTNOHTML, ALTSQL)
    VALUES (s.ALTID, s.ALTQUERY, s.ALTSUBJECT, s.ALTCONTENT, SYSDATE, SYSDATE, s.ALTUTIL,
            s.ALTFILE, s.ALTREALTIME, s.ALTSMSCONTENT, s.ALTORIENTATION, s.ALTPRINTAREA,
            s.ALTMARGIN, s.ALTFITPAGE, s.ALTFITHEIGHT, s.ALTFITWIDTH, s.ALTTITLEREPEAT,
            s.ALTFOOTER, s.ALTFORMAT, s.ALTFORMATXLS, s.ALTCONTENTHTML, s.ALTXLSBREAK,
            s.ALTSCALE, s.ALTCOLMOVE, s.ALTNBPARAM, s.ALTPARAMDESC, s.ALTBORDER,
            s.ALTTITLEXLS, s.ALTTITLEXLSCOLOR, s.ALTFREEZEHEADER, s.ALTFREEZECOLUMN,
            s.ALTFORMATTAB2XLS, s.ALTNOHTML, s.ALTSQL)
~',
       '{:USERID, :DATABASE_SID,:LISTE_PARAM,:LANGUAGE}',
       '',
       1,
       0,
       1
  FROM dual;

-- ALT0000012 — Delete Alert (POST DML)
INSERT INTO LIBQUERY (
  QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL,
  QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE
)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'ALT0000012',
       'Delete Alert',
       'Delete alert by ID',
       q'~
DELETE FROM ALERTS
WHERE ALTID IN (
    SELECT ALTID
    FROM json_table((SELECT REQUESTBODY
                     FROM REQUEST_QUERY_BODY
                     WHERE REQUESTID = :param1),
            '$.values[*]' COLUMNS(ALTID PATH '$."ALTID"')))
~',
       '{:USERID, :DATABASE_SID,:LISTE_PARAM,:LANGUAGE}',
       '',
       1,
       0,
       1
  FROM dual;

-- ALT0000020 — Merge Alert Distribution (POST DML)
INSERT INTO LIBQUERY (
  QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL,
  QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE
)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'ALT0000020',
       'Merge Alert Distribution',
       'Merge alert distribution (insert or update)',
       q'~
MERGE INTO ALERTDIST t
USING (
    SELECT *
    FROM json_table((SELECT REQUESTBODY
                     FROM REQUEST_QUERY_BODY
                     WHERE REQUESTID = :param1),
            '$.values[*]' COLUMNS(
                DALTID PATH '$."DALTID"',
                DALTUSERID PATH '$."DALTUSERID"',
                DALTTYPE NUMBER PATH '$."DALTTYPE"',
                DALTREPEAT NUMBER PATH '$."DALTREPEAT"',
                DALTUTIL PATH '$."DALTUTIL"',
                DALTEMAIL PATH '$."DALTEMAIL"',
                DALTSMS NUMBER PATH '$."DALTSMS"',
                DALTEMAILCC PATH '$."DALTEMAILCC"',
                DALTEMAILBCC PATH '$."DALTEMAILBCC"'
            ))
) s
ON (t.DALTID = s.DALTID)
WHEN MATCHED THEN
    UPDATE SET
        t.DALTUSERID = s.DALTUSERID, t.DALTTYPE = s.DALTTYPE, t.DALTREPEAT = s.DALTREPEAT,
        t.DALTDMAJ = SYSDATE, t.DALTUTIL = s.DALTUTIL, t.DALTEMAIL = s.DALTEMAIL,
        t.DALTSMS = s.DALTSMS, t.DALTEMAILCC = s.DALTEMAILCC, t.DALTEMAILBCC = s.DALTEMAILBCC
WHEN NOT MATCHED THEN
    INSERT (DALTID, DALTUSERID, DALTTYPE, DALTREPEAT, DALTDCRE, DALTDMAJ,
            DALTUTIL, DALTEMAIL, DALTSMS, DALTEMAILCC, DALTEMAILBCC)
    VALUES (s.DALTID, s.DALTUSERID, s.DALTTYPE, s.DALTREPEAT, SYSDATE, SYSDATE,
            s.DALTUTIL, s.DALTEMAIL, s.DALTSMS, s.DALTEMAILCC, s.DALTEMAILBCC)
~',
       '{:USERID, :DATABASE_SID,:LISTE_PARAM,:LANGUAGE}',
       '',
       1,
       0,
       1
  FROM dual;

-- ALT0000022 — Delete Alert Distribution (POST DML)
INSERT INTO LIBQUERY (
  QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL,
  QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE
)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'ALT0000022',
       'Delete Alert Distribution',
       'Delete alert distribution by ID',
       q'~
DELETE FROM ALERTDIST
WHERE DALTID IN (
    SELECT DALTID
    FROM json_table((SELECT REQUESTBODY
                     FROM REQUEST_QUERY_BODY
                     WHERE REQUESTID = :param1),
            '$.values[*]' COLUMNS(DALTID PATH '$."DALTID"')))
~',
       '{:USERID, :DATABASE_SID,:LISTE_PARAM,:LANGUAGE}',
       '',
       1,
       0,
       1
  FROM dual;

-- ALT0000030 — Merge Alert Schedule (POST DML)
INSERT INTO LIBQUERY (
  QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL,
  QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE
)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'ALT0000030',
       'Merge Alert Schedule',
       'Merge alert schedule (insert or update)',
       q'~
MERGE INTO ALERTSCHEDULE t
USING (
    SELECT *
    FROM json_table((SELECT REQUESTBODY
                     FROM REQUEST_QUERY_BODY
                     WHERE REQUESTID = :param1),
            '$.values[*]' COLUMNS(
                SALTID PATH '$."SALTID"',
                SALTDESC PATH '$."SALTDESC"',
                SALTCRON PATH '$."SALTCRON"',
                SALTTYPE NUMBER PATH '$."SALTTYPE"',
                SALTQUERYNUM PATH '$."SALTQUERYNUM"',
                SALTQUERYPARAM PATH '$."SALTQUERYPARAM"',
                SALTJOB PATH '$."SALTJOB"',
                SALTACTIVE PATH '$."SALTACTIVE"',
                SALTUTIL PATH '$."SALTUTIL"',
                SALTCATCHUP NUMBER PATH '$."SALTCATCHUP"',
                SALTREFALTID PATH '$."SALTREFALTID"',
                SALTCOMMENT PATH '$."SALTCOMMENT"',
                SALTSHELL CLOB PATH '$."SALTSHELL"'
            ))
) s
ON (t.SALTID = s.SALTID)
WHEN MATCHED THEN
    UPDATE SET
        t.SALTDESC = s.SALTDESC, t.SALTCRON = s.SALTCRON, t.SALTTYPE = s.SALTTYPE,
        t.SALTQUERYNUM = s.SALTQUERYNUM, t.SALTQUERYPARAM = s.SALTQUERYPARAM,
        t.SALTJOB = s.SALTJOB,
        t.SALTACTIVE = TO_DATE(SUBSTR(s.SALTACTIVE, 1, 19), 'YYYY-MM-DD"T"HH24:MI:SS'),
        t.SALTDMAJ = SYSDATE, t.SALTUTIL = s.SALTUTIL, t.SALTCATCHUP = s.SALTCATCHUP,
        t.SALTREFALTID = s.SALTREFALTID, t.SALTCOMMENT = s.SALTCOMMENT, t.SALTSHELL = s.SALTSHELL
WHEN NOT MATCHED THEN
    INSERT (SALTID, SALTDESC, SALTCRON, SALTTYPE, SALTQUERYNUM, SALTQUERYPARAM,
            SALTJOB, SALTACTIVE, SALTDCRE, SALTDMAJ, SALTUTIL, SALTCATCHUP,
            SALTREFALTID, SALTCOMMENT, SALTSHELL)
    VALUES (s.SALTID, s.SALTDESC, s.SALTCRON, s.SALTTYPE, s.SALTQUERYNUM, s.SALTQUERYPARAM,
            s.SALTJOB, TO_DATE(SUBSTR(s.SALTACTIVE, 1, 19), 'YYYY-MM-DD"T"HH24:MI:SS'),
            SYSDATE, SYSDATE, s.SALTUTIL, s.SALTCATCHUP, s.SALTREFALTID, s.SALTCOMMENT, s.SALTSHELL)
~',
       '{:USERID, :DATABASE_SID,:LISTE_PARAM,:LANGUAGE}',
       '',
       1,
       0,
       1
  FROM dual;

-- ALT0000032 — Delete Alert Schedule (POST DML)
INSERT INTO LIBQUERY (
  QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL,
  QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE
)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'ALT0000032',
       'Delete Alert Schedule',
       'Delete alert schedule by ID',
       q'~
DELETE FROM ALERTSCHEDULE
WHERE SALTID IN (
    SELECT SALTID
    FROM json_table((SELECT REQUESTBODY
                     FROM REQUEST_QUERY_BODY
                     WHERE REQUESTID = :param1),
            '$.values[*]' COLUMNS(SALTID PATH '$."SALTID"')))
~',
       '{:USERID, :DATABASE_SID,:LISTE_PARAM,:LANGUAGE}',
       '',
       1,
       0,
       1
  FROM dual;

COMMIT;

SET DEFINE ON;
