-- Widget Library (General Settings) — CRUD for dashboard widgets
--
-- Tables:
--  - WIDGET         (widget definition)
--  - TRA_WIDGETS    (TWLAID + TWLADESC per language; WIDGET.WIDNAME/WIDDESC hold TWLAID refs)
--  - WIDGETRESULT   (result columns metadata)
--  - WIDGETLINK     (main ↔ controlled widget links)
--
-- All access via LIBQUERY (QueryService pattern).
-- GET uses bind params :param1.. in order.
-- POST uses :param1 = REQUESTID and JSON_TABLE on REQUEST_QUERY_BODY.requestbody.
--
-- Query range reserved: WDG0000100–WDG0000110

SET DEFINE OFF;

DELETE FROM LIBQUERY WHERE QUERYNUM IN (
  'WDG0000100','WDG0000101','WDG0000102','WDG0000103','WDG0000110',
  'WDG0000104','WDG0000105','WDG0000106',
  'WDG0000107','WDG0000108','WDG0000109'
);

-- WDG0000100 — Widget list (name/desc text via TRA_WIDGETS on WIDNAME/WIDDESC ids)
INSERT INTO LIBQUERY (QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'WDG0000100',
       'Widget library — list',
       'List widgets. :param1=active (-1=all, 0/1 optional if column exists; else ignored).',
       q'~
SELECT w.WIDID,
       w.WIDNAME,
       w.WIDDESC,
       tn.TWLADESC AS WIDNAME_DESC,
       td.TWLADESC AS WIDDESC_DESC,
       w.WIDBEHAVIOR,
       w.WIDTABLE,
       w.WIDRSS,
       w.WIDCHART,
       w.WIDINFO,
       w.WIDWIDTH,
       w.WIDHEIGHT,
       w.WIDROWS,
       w.WIDSNAP,
       w.WIDSNAPFILE,
       w.WIDCHARTX,
       w.WIDCHARTDATA,
       w.WIDCHARTLEGEND,
       w.WIDCHARTLEGENDINFO,
       w.WIDCHARTNBSET,
       w.WIDCHARTTYPE,
       w.WIDCHARTUNIT,
       w.WIDCARD,
       w.WIDMAINID,
       w.WIDDCRE,
       w.WIDDMAJ,
       w.WIDUTIL
  FROM WIDGET w
  LEFT JOIN TRA_WIDGETS tn
    ON tn.TWLAID = w.WIDNAME
   AND tn.TWLALANGUE = 'us_US'
  LEFT JOIN TRA_WIDGETS td
    ON td.TWLAID = w.WIDDESC
   AND td.TWLALANGUE = 'us_US'
 ORDER BY UPPER(NVL(tn.TWLADESC, w.WIDNAME)), w.WIDID
~',
       ':param1=active_filter',
       'WIDID,WIDNAME,WIDDESC,WIDNAME_DESC,WIDDESC_DESC,WIDBEHAVIOR,WIDTABLE,WIDRSS,WIDCHART,WIDINFO,WIDWIDTH,WIDHEIGHT,WIDROWS,WIDSNAP,WIDSNAPFILE,WIDCHARTX,WIDCHARTDATA,WIDCHARTLEGEND,WIDCHARTLEGENDINFO,WIDCHARTNBSET,WIDCHARTTYPE,WIDCHARTUNIT,WIDCARD,WIDMAINID,WIDDCRE,WIDDMAJ,WIDUTIL',
       0, 0, 0 FROM dual;

-- WDG0000101 — Widget by id
INSERT INTO LIBQUERY (QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'WDG0000101',
       'Widget library — one widget',
       'Get widget by id. :param1=widid.',
       q'~
SELECT w.WIDID,
       w.WIDNAME,
       w.WIDDESC,
       tn.TWLADESC AS WIDNAME_DESC,
       td.TWLADESC AS WIDDESC_DESC,
       w.WIDBEHAVIOR,
       w.WIDTABLE,
       w.WIDRSS,
       w.WIDCHART,
       w.WIDINFO,
       w.WIDWIDTH,
       w.WIDHEIGHT,
       w.WIDROWS,
       w.WIDSNAP,
       w.WIDSNAPFILE,
       w.WIDCHARTX,
       w.WIDCHARTDATA,
       w.WIDCHARTLEGEND,
       w.WIDCHARTLEGENDINFO,
       w.WIDCHARTNBSET,
       w.WIDCHARTTYPE,
       w.WIDCHARTUNIT,
       w.WIDCARD,
       w.WIDMAINID,
       w.WIDDCRE,
       w.WIDDMAJ,
       w.WIDUTIL
  FROM WIDGET w
  LEFT JOIN TRA_WIDGETS tn
    ON tn.TWLAID = w.WIDNAME
   AND tn.TWLALANGUE = 'us_US'
  LEFT JOIN TRA_WIDGETS td
    ON td.TWLAID = w.WIDDESC
   AND td.TWLALANGUE = 'us_US'
 WHERE w.WIDID = :param1
~',
       ':param1=widid',
       'WIDID,WIDNAME,WIDDESC,WIDNAME_DESC,WIDDESC_DESC,WIDBEHAVIOR,WIDTABLE,WIDRSS,WIDCHART,WIDINFO,WIDWIDTH,WIDHEIGHT,WIDROWS,WIDSNAP,WIDSNAPFILE,WIDCHARTX,WIDCHARTDATA,WIDCHARTLEGEND,WIDCHARTLEGENDINFO,WIDCHARTNBSET,WIDCHARTTYPE,WIDCHARTUNIT,WIDCARD,WIDMAINID,WIDDCRE,WIDDMAJ,WIDUTIL',
       0, 0, 0 FROM dual;

-- WDG0000102 — MERGE widget definition (WIDGET table)
INSERT INTO LIBQUERY (QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'WDG0000102',
       'Widget library - save widget',
       'POST :param1=REQUESTID. values[]: WIDID,WIDNAME,WIDDESC (TRA TWLAID refs),flags,chart fields,WIDMAINID,ACTOR.',
       q'~MERGE INTO WIDGET t USING (SELECT TRIM(j.WIDID) WIDID,TRIM(j.WIDNAME) WIDNAME,TRIM(j.WIDDESC) WIDDESC,NVL(j.WIDBEHAVIOR,1) WIDBEHAVIOR,NVL(j.WIDTABLE,0) WIDTABLE,NVL(j.WIDRSS,0) WIDRSS,NVL(j.WIDCHART,0) WIDCHART,NVL(j.WIDINFO,0) WIDINFO,NVL(j.WIDWIDTH,4) WIDWIDTH,NVL(j.WIDHEIGHT,3) WIDHEIGHT,NVL(j.WIDROWS,25) WIDROWS,NVL(j.WIDSNAP,0) WIDSNAP,TRIM(j.WIDSNAPFILE) WIDSNAPFILE,TRIM(j.WIDCHARTX) WIDCHARTX,TRIM(j.WIDCHARTDATA) WIDCHARTDATA,TRIM(j.WIDCHARTLEGEND) WIDCHARTLEGEND,TRIM(j.WIDCHARTLEGENDINFO) WIDCHARTLEGENDINFO,TRIM(j.WIDCHARTNBSET) WIDCHARTNBSET,TRIM(j.WIDCHARTTYPE) WIDCHARTTYPE,TRIM(j.WIDCHARTUNIT) WIDCHARTUNIT,NVL(j.WIDCARD,0) WIDCARD,TRIM(j.WIDMAINID) WIDMAINID,TRIM(j.ACTOR) ACTOR FROM json_table((SELECT r.requestbody FROM request_query_body r WHERE r.requestid=TO_NUMBER(:param1)),'$.values[*]' COLUMNS (WIDID VARCHAR2(20) PATH '$."WIDID"',WIDNAME VARCHAR2(20) PATH '$."WIDNAME"',WIDDESC VARCHAR2(20) PATH '$."WIDDESC"',WIDBEHAVIOR NUMBER PATH '$."WIDBEHAVIOR"',WIDTABLE NUMBER PATH '$."WIDTABLE"',WIDRSS NUMBER PATH '$."WIDRSS"',WIDCHART NUMBER PATH '$."WIDCHART"',WIDINFO NUMBER PATH '$."WIDINFO"',WIDWIDTH NUMBER PATH '$."WIDWIDTH"',WIDHEIGHT NUMBER PATH '$."WIDHEIGHT"',WIDROWS NUMBER PATH '$."WIDROWS"',WIDSNAP NUMBER PATH '$."WIDSNAP"',WIDSNAPFILE VARCHAR2(500) PATH '$."WIDSNAPFILE"',WIDCHARTX VARCHAR2(500) PATH '$."WIDCHARTX"',WIDCHARTDATA VARCHAR2(500) PATH '$."WIDCHARTDATA"',WIDCHARTLEGEND VARCHAR2(500) PATH '$."WIDCHARTLEGEND"',WIDCHARTLEGENDINFO VARCHAR2(500) PATH '$."WIDCHARTLEGENDINFO"',WIDCHARTNBSET VARCHAR2(200) PATH '$."WIDCHARTNBSET"',WIDCHARTTYPE VARCHAR2(20) PATH '$."WIDCHARTTYPE"',WIDCHARTUNIT VARCHAR2(200) PATH '$."WIDCHARTUNIT"',WIDCARD NUMBER PATH '$."WIDCARD"',WIDMAINID VARCHAR2(20) PATH '$."WIDMAINID"',ACTOR VARCHAR2(50) PATH '$."ACTOR"')) j WHERE TRIM(j.WIDID) IS NOT NULL) s~'
       || q'~ ON (t.WIDID=s.WIDID) WHEN MATCHED THEN UPDATE SET t.WIDNAME=s.WIDNAME,t.WIDDESC=s.WIDDESC,t.WIDBEHAVIOR=s.WIDBEHAVIOR,t.WIDTABLE=s.WIDTABLE,t.WIDRSS=s.WIDRSS,t.WIDCHART=s.WIDCHART,t.WIDINFO=s.WIDINFO,t.WIDWIDTH=s.WIDWIDTH,t.WIDHEIGHT=s.WIDHEIGHT,t.WIDROWS=s.WIDROWS,t.WIDSNAP=s.WIDSNAP,t.WIDSNAPFILE=s.WIDSNAPFILE,t.WIDCHARTX=s.WIDCHARTX,t.WIDCHARTDATA=s.WIDCHARTDATA,t.WIDCHARTLEGEND=s.WIDCHARTLEGEND,t.WIDCHARTLEGENDINFO=s.WIDCHARTLEGENDINFO,t.WIDCHARTNBSET=s.WIDCHARTNBSET,t.WIDCHARTTYPE=s.WIDCHARTTYPE,t.WIDCHARTUNIT=s.WIDCHARTUNIT,t.WIDCARD=s.WIDCARD,t.WIDMAINID=s.WIDMAINID,t.WIDDMAJ=SYSDATE,t.WIDUTIL=s.ACTOR WHEN NOT MATCHED THEN INSERT (WIDID,WIDBEHAVIOR,WIDTABLE,WIDRSS,WIDCHART,WIDINFO,WIDWIDTH,WIDHEIGHT,WIDROWS,WIDDCRE,WIDDMAJ,WIDUTIL,WIDSNAP,WIDSNAPFILE,WIDNAME,WIDDESC,WIDCHARTX,WIDCHARTDATA,WIDCHARTLEGEND,WIDCHARTLEGENDINFO,WIDCHARTNBSET,WIDCHARTTYPE,WIDCHARTUNIT,WIDCARD,WIDMAINID) VALUES (s.WIDID,s.WIDBEHAVIOR,s.WIDTABLE,s.WIDRSS,s.WIDCHART,s.WIDINFO,s.WIDWIDTH,s.WIDHEIGHT,s.WIDROWS,SYSDATE,SYSDATE,s.ACTOR,s.WIDSNAP,s.WIDSNAPFILE,s.WIDNAME,s.WIDDESC,s.WIDCHARTX,s.WIDCHARTDATA,s.WIDCHARTLEGEND,s.WIDCHARTLEGENDINFO,s.WIDCHARTNBSET,s.WIDCHARTTYPE,s.WIDCHARTUNIT,s.WIDCARD,s.WIDMAINID)~',
       ':param1=REQUESTID',
       '',
       0, 0, 1 FROM dual;

-- WDG0000110 — MERGE TRA_WIDGETS row (TWLAID = translation id, TWLADESC = us_US text)
INSERT INTO LIBQUERY (QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'WDG0000110',
       'Widget library - save TRA_WIDGETS row',
       'POST :param1=REQUESTID. values[]: TWLAID, TWLADESC, ACTOR. us_US text max 100 chars.',
       q'~MERGE INTO TRA_WIDGETS tt USING (SELECT TRIM(j.TWLAID) TWLAID,'us_US' TWLALANGUE,SUBSTR(NVL(NULLIF(TRIM(j.TWLADESC),''),' '),1,100) TWLADESC,TRIM(j.ACTOR) TWLAUTIL FROM json_table((SELECT r.requestbody FROM request_query_body r WHERE r.requestid=TO_NUMBER(:param1)),'$.values[*]' COLUMNS (TWLAID VARCHAR2(20) PATH '$."TWLAID"',TWLADESC VARCHAR2(100) PATH '$."TWLADESC"',ACTOR VARCHAR2(50) PATH '$."ACTOR"')) j WHERE TRIM(j.TWLAID) IS NOT NULL) src ON (tt.TWLAID=src.TWLAID AND tt.TWLALANGUE=src.TWLALANGUE) WHEN MATCHED THEN UPDATE SET tt.TWLADESC=src.TWLADESC,tt.TWLADMAJ=SYSDATE,tt.TWLAUTIL=src.TWLAUTIL WHEN NOT MATCHED THEN INSERT (TWLAID,TWLADESC,TWLALANGUE,TWLADCRE,TWLADMAJ,TWLAUTIL) VALUES (src.TWLAID,src.TWLADESC,src.TWLALANGUE,SYSDATE,SYSDATE,src.TWLAUTIL)~',
       ':param1=REQUESTID',
       '',
       0, 0, 1 FROM dual;

-- WDG0000103 — DELETE widget (cascades related rows)
INSERT INTO LIBQUERY (QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'WDG0000103',
       'Widget library - delete widget',
       'POST :param1=REQUESTID. values[]: WIDID. Cascades child rows then WIDGET.',
       q'~
BEGIN
  FOR rec IN (
    SELECT TRIM(j.WIDID) AS wid
      FROM json_table(
             (SELECT r.requestbody
                FROM request_query_body r
               WHERE r.requestid = TO_NUMBER(TRIM(:param1))),
             '$.values[*]'
             COLUMNS (WIDID VARCHAR2(20) PATH '$."WIDID"')
           ) j
     WHERE TRIM(j.WIDID) IS NOT NULL
  ) LOOP
    DELETE FROM WIDGETRESULT WHERE WRSID = rec.wid;
    DELETE FROM WIDGETLINK WHERE LWQMWIDID = rec.wid OR LWQCWIDID = rec.wid;
    DELETE FROM USER_WIDGET WHERE UWPWIDID = rec.wid;
    DELETE FROM WIDGETUSERPREF WHERE WPFWIDID = rec.wid;
    DELETE FROM TRA_WIDGETS WHERE TWLAID IN (
      SELECT w.WIDNAME FROM WIDGET w WHERE w.WIDID = rec.wid
      UNION
      SELECT w.WIDDESC FROM WIDGET w WHERE w.WIDID = rec.wid
    );
    DELETE FROM WIDGET WHERE WIDID = rec.wid;
  END LOOP;
END;
~',
       ':param1=REQUESTID',
       '',
       0, 0, 1 FROM dual;

-- WDG0000104 — List widget result columns
INSERT INTO LIBQUERY (QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'WDG0000104',
       'Widget library — result columns',
       'List result columns. :param1=widid.',
       q'~
SELECT WRSID,
       WRSFIELD,
       WRSHEADER,
       WRSPOSITION,
       WRSDCRE,
       WRSDMAJ,
       WRSUTIL
  FROM WIDGETRESULT
 WHERE WRSID = :param1
 ORDER BY WRSPOSITION, WRSFIELD
~',
       ':param1=widid',
       'WRSID,WRSFIELD,WRSHEADER,WRSPOSITION,WRSDCRE,WRSDMAJ,WRSUTIL',
       0, 0, 0 FROM dual;

-- WDG0000105 — MERGE widget result column
INSERT INTO LIBQUERY (QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'WDG0000105',
       'Widget library — save result column',
       'POST :param1=REQUESTID. values[]: WRSID, WRSFIELD, WRSHEADER, WRSPOSITION, ACTOR.',
       q'~
MERGE INTO WIDGETRESULT t
USING (
  SELECT TRIM(j.WRSID) AS WRSID,
         TRIM(j.WRSFIELD) AS WRSFIELD,
         TRIM(j.WRSHEADER) AS WRSHEADER,
         CASE WHEN NULLIF(TRIM(j.WRSPOSITION), '') IS NOT NULL THEN TO_NUMBER(TRIM(j.WRSPOSITION)) END AS WRSPOSITION,
         TRIM(j.ACTOR) AS ACTOR
    FROM json_table(
           (SELECT r.requestbody FROM request_query_body r WHERE r.requestid = TO_NUMBER(TRIM(:param1))),
           '$.values[*]'
           COLUMNS (
             WRSID       VARCHAR2(20)  PATH '$."WRSID"',
             WRSFIELD    VARCHAR2(100) PATH '$."WRSFIELD"',
             WRSHEADER   VARCHAR2(100) PATH '$."WRSHEADER"',
             WRSPOSITION VARCHAR2(20)  PATH '$."WRSPOSITION"',
             ACTOR       VARCHAR2(50)  PATH '$."ACTOR"'
           )
         ) j
) s
ON (t.WRSID = s.WRSID AND t.WRSFIELD = s.WRSFIELD)
WHEN MATCHED THEN UPDATE SET
  t.WRSHEADER = s.WRSHEADER,
  t.WRSPOSITION = s.WRSPOSITION,
  t.WRSDMAJ = SYSDATE,
  t.WRSUTIL = s.ACTOR
WHEN NOT MATCHED THEN INSERT (
  WRSID, WRSFIELD, WRSHEADER, WRSPOSITION, WRSDCRE, WRSDMAJ, WRSUTIL
) VALUES (
  s.WRSID, s.WRSFIELD, s.WRSHEADER, s.WRSPOSITION, SYSDATE, SYSDATE, s.ACTOR
)
~',
       ':param1=REQUESTID',
       '',
       0, 0, 1 FROM dual;

-- WDG0000106 — DELETE widget result column
INSERT INTO LIBQUERY (QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'WDG0000106',
       'Widget library — delete result column',
       'POST :param1=REQUESTID. values[]: WRSID, WRSFIELD.',
       q'~
DELETE FROM WIDGETRESULT r
 WHERE EXISTS (
   SELECT 1
     FROM json_table(
            (SELECT x.requestbody FROM request_query_body x WHERE x.requestid = TO_NUMBER(TRIM(:param1))),
            '$.values[*]'
            COLUMNS (
              WRSID    VARCHAR2(20)  PATH '$."WRSID"',
              WRSFIELD VARCHAR2(100) PATH '$."WRSFIELD"'
            )
          ) j
    WHERE r.WRSID = TRIM(j.WRSID)
      AND r.WRSFIELD = TRIM(j.WRSFIELD)
 )
~',
       ':param1=REQUESTID',
       '',
       0, 0, 1 FROM dual;

-- WDG0000107 — List widget links (for a widget id)
INSERT INTO LIBQUERY (QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'WDG0000107',
       'Widget library — links',
       'List links. :param1=widid.',
       q'~
SELECT LWQMWIDID,
       LWQCWIDID,
       LWQMFIELD,
       LWQCFIELD,
       LWQDCRE,
       LWQDMAJ,
       LWQUTIL
  FROM WIDGETLINK
 WHERE (:param1 = '-1' OR LWQMWIDID = :param1 OR LWQCWIDID = :param1)
 ORDER BY LWQMWIDID, LWQCWIDID, LWQMFIELD, LWQCFIELD
~',
       ':param1=widid_or_-1',
       'LWQMWIDID,LWQCWIDID,LWQMFIELD,LWQCFIELD,LWQDCRE,LWQDMAJ,LWQUTIL',
       0, 0, 0 FROM dual;

-- WDG0000108 — MERGE widget link
INSERT INTO LIBQUERY (QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'WDG0000108',
       'Widget library — save link',
       'POST :param1=REQUESTID. values[]: LWQMWIDID, LWQCWIDID, LWQMFIELD, LWQCFIELD, ACTOR.',
       q'~
MERGE INTO WIDGETLINK t
USING (
  SELECT TRIM(j.LWQMWIDID) AS LWQMWIDID,
         TRIM(j.LWQCWIDID) AS LWQCWIDID,
         TRIM(j.LWQMFIELD) AS LWQMFIELD,
         TRIM(j.LWQCFIELD) AS LWQCFIELD,
         TRIM(j.ACTOR)     AS ACTOR
    FROM json_table(
           (SELECT r.requestbody FROM request_query_body r WHERE r.requestid = TO_NUMBER(TRIM(:param1))),
           '$.values[*]'
           COLUMNS (
             LWQMWIDID VARCHAR2(20)  PATH '$."LWQMWIDID"',
             LWQCWIDID VARCHAR2(20)  PATH '$."LWQCWIDID"',
             LWQMFIELD VARCHAR2(100) PATH '$."LWQMFIELD"',
             LWQCFIELD VARCHAR2(100) PATH '$."LWQCFIELD"',
             ACTOR     VARCHAR2(50)  PATH '$."ACTOR"'
           )
         ) j
) s
ON (
  t.LWQMWIDID = s.LWQMWIDID
  AND t.LWQCWIDID = s.LWQCWIDID
  AND NVL(t.LWQMFIELD, ' ') = NVL(s.LWQMFIELD, ' ')
  AND NVL(t.LWQCFIELD, ' ') = NVL(s.LWQCFIELD, ' ')
)
WHEN MATCHED THEN UPDATE SET
  t.LWQDMAJ = SYSDATE,
  t.LWQUTIL = s.ACTOR
WHEN NOT MATCHED THEN INSERT (
  LWQMWIDID, LWQCWIDID, LWQMFIELD, LWQCFIELD, LWQDCRE, LWQDMAJ, LWQUTIL
) VALUES (
  s.LWQMWIDID, s.LWQCWIDID, s.LWQMFIELD, s.LWQCFIELD, SYSDATE, SYSDATE, s.ACTOR
)
~',
       ':param1=REQUESTID',
       '',
       0, 0, 1 FROM dual;

-- WDG0000109 — DELETE widget link
INSERT INTO LIBQUERY (QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'WDG0000109',
       'Widget library — delete link',
       'POST :param1=REQUESTID. values[]: LWQMWIDID, LWQCWIDID, LWQMFIELD, LWQCFIELD.',
       q'~
DELETE FROM WIDGETLINK l
 WHERE EXISTS (
   SELECT 1
     FROM json_table(
            (SELECT x.requestbody FROM request_query_body x WHERE x.requestid = TO_NUMBER(TRIM(:param1))),
            '$.values[*]'
            COLUMNS (
              LWQMWIDID VARCHAR2(20)  PATH '$."LWQMWIDID"',
              LWQCWIDID VARCHAR2(20)  PATH '$."LWQCWIDID"',
              LWQMFIELD VARCHAR2(100) PATH '$."LWQMFIELD"',
              LWQCFIELD VARCHAR2(100) PATH '$."LWQCFIELD"'
            )
          ) j
    WHERE l.LWQMWIDID = TRIM(j.LWQMWIDID)
      AND l.LWQCWIDID = TRIM(j.LWQCWIDID)
      AND NVL(l.LWQMFIELD, ' ') = NVL(TRIM(j.LWQMFIELD), ' ')
      AND NVL(l.LWQCFIELD, ' ') = NVL(TRIM(j.LWQCFIELD), ' ')
 )
~',
       ':param1=REQUESTID',
       '',
       0, 0, 1 FROM dual;

COMMIT;

SET DEFINE ON;

