-- Users & Profiles — USER_WIDGET CRUD (dashboard layout per user)
--
-- Heinens USER_WIDGET columns:
--   UWPUSERID, UWPWIDID, UWPDESC, UWPCONTAINER, UWPW_X, UWPW_Y, UWPWIDTH, UWPHEIGHT,
--   UWPROWS, UWPSNAPFILE, UWPDCRE, UWPDMAJ, UWPUTIL, UWPCHARTX, UWPCHARTDATA,
--   UWPCHARTLEGEND, UWPCOLLAPSE, UWPPARAM, UWPENABLE
--
-- Deploy after 34_settings_users_corporate_libquery.sql and 63_widget_library_libquery.sql.

SET DEFINE OFF;

DELETE FROM LIBQUERY WHERE QUERYNUM IN (
  'SET0000035', 'SET0000036', 'SET0000037', 'SET0000038'
);

-- SET0000035 — List dashboard widgets for a user
INSERT INTO LIBQUERY (QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'SET0000035',
       'User widget - list',
       'USER_WIDGET rows for user. :param1=UWPUSERID.',
       q'~
SELECT uw.UWPUSERID,
       uw.UWPWIDID,
       uw.UWPPARAM,
       uw.UWPDESC,
       uw.UWPCONTAINER,
       uw.UWPW_X,
       uw.UWPW_Y,
       uw.UWPWIDTH,
       uw.UWPHEIGHT,
       uw.UWPROWS,
       uw.UWPCOLLAPSE,
       uw.UWPENABLE,
       uw.UWPDCRE,
       uw.UWPDMAJ,
       uw.UWPUTIL,
       tn.TWLADESC AS WIDNAME_DESC
  FROM USER_WIDGET uw
  LEFT JOIN WIDGET w ON w.WIDID = uw.UWPWIDID
  LEFT JOIN TRA_WIDGETS tn ON tn.TWLAID = w.WIDNAME AND tn.TWLALANGUE = 'us_US'
 WHERE uw.UWPUSERID = :param1
 ORDER BY uw.UWPW_Y, uw.UWPW_X, uw.UWPWIDID, uw.UWPPARAM
~',
       ':param1=userid',
       'UWPUSERID,UWPWIDID,UWPPARAM,UWPDESC,UWPCONTAINER,UWPW_X,UWPW_Y,UWPWIDTH,UWPHEIGHT,UWPROWS,UWPCOLLAPSE,UWPENABLE,UWPDCRE,UWPDMAJ,UWPUTIL,WIDNAME_DESC',
       0, 0, 0 FROM dual;

-- SET0000036 — One assignment
INSERT INTO LIBQUERY (QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'SET0000036',
       'User widget - one',
       'Single USER_WIDGET row. :param1=UWPUSERID; :param2=UWPWIDID; :param3=UWPPARAM.',
       q'~
SELECT uw.UWPUSERID,
       uw.UWPWIDID,
       uw.UWPPARAM,
       uw.UWPDESC,
       uw.UWPCONTAINER,
       uw.UWPW_X,
       uw.UWPW_Y,
       uw.UWPWIDTH,
       uw.UWPHEIGHT,
       uw.UWPROWS,
       uw.UWPCOLLAPSE,
       uw.UWPENABLE,
       uw.UWPDCRE,
       uw.UWPDMAJ,
       uw.UWPUTIL
  FROM USER_WIDGET uw
 WHERE uw.UWPUSERID = :param1
   AND uw.UWPWIDID = :param2
   AND NVL(uw.UWPPARAM, '-1') = NVL(:param3, '-1')
~',
       ':param1=userid,:param2=widid,:param3=uwparam',
       'UWPUSERID,UWPWIDID,UWPPARAM,UWPDESC,UWPCONTAINER,UWPW_X,UWPW_Y,UWPWIDTH,UWPHEIGHT,UWPROWS,UWPCOLLAPSE,UWPENABLE,UWPDCRE,UWPDMAJ,UWPUTIL',
       0, 0, 0 FROM dual;

-- SET0000037 — MERGE user widget assignment
INSERT INTO LIBQUERY (QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'SET0000037',
       'User widget - MERGE',
       'POST :param1=REQUESTID. values[]: UWPUSERID,UWPWIDID,UWPPARAM,UWPDESC,UWPW_X,UWPW_Y,UWPWIDTH,UWPHEIGHT,UWPROWS,UWPCOLLAPSE,UWPENABLE,UWPUTIL.',
       q'~
MERGE INTO USER_WIDGET t
USING (
  SELECT TRIM(j.UWPUSERID) UWPUSERID,
         TRIM(j.UWPWIDID) UWPWIDID,
         NVL(NULLIF(TRIM(j.UWPPARAM), ''), '-1') UWPPARAM,
         SUBSTR(NVL(TRIM(j.UWPDESC), ' '), 1, 100) UWPDESC,
         NVL(TO_NUMBER(j.UWPW_X), 0) UWPW_X,
         NVL(TO_NUMBER(j.UWPW_Y), 0) UWPW_Y,
         NVL(TO_NUMBER(j.UWPWIDTH), 4) UWPWIDTH,
         NVL(TO_NUMBER(j.UWPHEIGHT), 3) UWPHEIGHT,
         NVL(TO_NUMBER(j.UWPROWS), 0) UWPROWS,
         NVL(TRIM(j.UWPCOLLAPSE), 'expand') UWPCOLLAPSE,
         NVL(TO_NUMBER(j.UWPENABLE), 1) UWPENABLE,
         TRIM(j.UWPUTIL) UWPUTIL
    FROM REQUEST_QUERY_BODY rb,
         JSON_TABLE(rb.REQUESTBODY, '$.values[0]'
           COLUMNS (
             UWPUSERID   VARCHAR2(20)  PATH '$."UWPUSERID"',
             UWPWIDID    VARCHAR2(20)  PATH '$."UWPWIDID"',
             UWPPARAM    VARCHAR2(500) PATH '$."UWPPARAM"',
             UWPDESC     VARCHAR2(100) PATH '$."UWPDESC"',
             UWPW_X      VARCHAR2(10)  PATH '$."UWPW_X"',
             UWPW_Y      VARCHAR2(10)  PATH '$."UWPW_Y"',
             UWPWIDTH    VARCHAR2(10)  PATH '$."UWPWIDTH"',
             UWPHEIGHT   VARCHAR2(10)  PATH '$."UWPHEIGHT"',
             UWPROWS     VARCHAR2(10)  PATH '$."UWPROWS"',
             UWPCOLLAPSE VARCHAR2(20)  PATH '$."UWPCOLLAPSE"',
             UWPENABLE   VARCHAR2(5)   PATH '$."UWPENABLE"',
             UWPUTIL     VARCHAR2(20)  PATH '$."UWPUTIL"'
           )
         ) j
   WHERE rb.REQUESTID = :param1
) s
ON (t.UWPUSERID = s.UWPUSERID AND t.UWPWIDID = s.UWPWIDID AND NVL(t.UWPPARAM, '-1') = s.UWPPARAM)
WHEN MATCHED THEN UPDATE SET
  t.UWPDESC = s.UWPDESC,
  t.UWPW_X = s.UWPW_X,
  t.UWPW_Y = s.UWPW_Y,
  t.UWPWIDTH = s.UWPWIDTH,
  t.UWPHEIGHT = s.UWPHEIGHT,
  t.UWPROWS = s.UWPROWS,
  t.UWPCOLLAPSE = s.UWPCOLLAPSE,
  t.UWPENABLE = s.UWPENABLE,
  t.UWPDMAJ = SYSDATE,
  t.UWPUTIL = s.UWPUTIL
WHEN NOT MATCHED THEN INSERT (
  UWPUSERID, UWPWIDID, UWPPARAM, UWPDESC,
  UWPW_X, UWPW_Y, UWPWIDTH, UWPHEIGHT, UWPROWS, UWPCOLLAPSE, UWPENABLE,
  UWPDCRE, UWPDMAJ, UWPUTIL
) VALUES (
  s.UWPUSERID, s.UWPWIDID, s.UWPPARAM, s.UWPDESC,
  s.UWPW_X, s.UWPW_Y, s.UWPWIDTH, s.UWPHEIGHT, s.UWPROWS, s.UWPCOLLAPSE, s.UWPENABLE,
  SYSDATE, SYSDATE, s.UWPUTIL
)
~',
       ':param1=REQUESTID',
       '',
       0, 0, 1 FROM dual;

-- SET0000038 — DELETE user widget assignment
INSERT INTO LIBQUERY (QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'SET0000038',
       'User widget - delete',
       'POST :param1=REQUESTID. values[]: UWPUSERID,UWPWIDID,UWPPARAM.',
       q'~
DELETE FROM USER_WIDGET uw
 WHERE EXISTS (
   SELECT 1
     FROM REQUEST_QUERY_BODY rb,
          JSON_TABLE(rb.REQUESTBODY, '$.values[0]'
            COLUMNS (
              UWPUSERID VARCHAR2(20)  PATH '$."UWPUSERID"',
              UWPWIDID  VARCHAR2(20)  PATH '$."UWPWIDID"',
              UWPPARAM  VARCHAR2(500) PATH '$."UWPPARAM"'
            )
          ) j
    WHERE rb.REQUESTID = :param1
      AND uw.UWPUSERID = TRIM(j.UWPUSERID)
      AND uw.UWPWIDID = TRIM(j.UWPWIDID)
      AND NVL(uw.UWPPARAM, '-1') = NVL(NULLIF(TRIM(j.UWPPARAM), ''), '-1')
 )
~',
       ':param1=REQUESTID',
       '',
       0, 0, 1 FROM dual;

COMMIT;

SET DEFINE ON;
