-- Phase 1 i18n — LANGUAGE catalog + ICR_MENU_LABEL (menu translations separate from TRA_LABELS)
-- Run once on ICR app DB. Re-runnable MERGE on LANGUAGE; CREATE TABLE skipped if exists.

SET DEFINE OFF;

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE ICR_MENU_LABEL (
      MENU_CODE   VARCHAR2(60)  NOT NULL,
      MLLANGUE    VARCHAR2(10)  NOT NULL,
      LABEL_TEXT  VARCHAR2(120) NOT NULL,
      MLDCRE      DATE DEFAULT SYSDATE,
      MLDMAJ      DATE DEFAULT SYSDATE,
      MLUTIL      VARCHAR2(20),
      CONSTRAINT PK_ICR_MENU_LABEL PRIMARY KEY (MENU_CODE, MLLANGUE),
      CONSTRAINT FK_ICR_MENU_LABEL FOREIGN KEY (MENU_CODE)
        REFERENCES ICR_MENU_ENTRY (MENU_CODE)
    )]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

CREATE INDEX IX_ICR_MENU_LABEL_LANG ON ICR_MENU_LABEL (MLLANGUE, MENU_CODE);

MERGE INTO LANGUAGE t
USING (SELECT 'us_US' LANID, 'American' LANDESC FROM DUAL) s
ON (t.LANID = s.LANID)
WHEN MATCHED THEN UPDATE SET t.LANDESC = s.LANDESC, t.LANDMAJ = SYSDATE
WHEN NOT MATCHED THEN INSERT (LANID, LANDESC, LANDCRE, LANDMAJ, LANUTIL)
VALUES (s.LANID, s.LANDESC, SYSDATE, SYSDATE, 'admin');

MERGE INTO LANGUAGE t
USING (SELECT 'en_GB' LANID, 'English (UK)' LANDESC FROM DUAL) s
ON (t.LANID = s.LANID)
WHEN MATCHED THEN UPDATE SET t.LANDESC = s.LANDESC, t.LANDMAJ = SYSDATE
WHEN NOT MATCHED THEN INSERT (LANID, LANDESC, LANDCRE, LANDMAJ, LANUTIL)
VALUES (s.LANID, s.LANDESC, SYSDATE, SYSDATE, 'admin');

MERGE INTO LANGUAGE t
USING (SELECT 'fr_FR' LANID, 'French' LANDESC FROM DUAL) s
ON (t.LANID = s.LANID)
WHEN MATCHED THEN UPDATE SET t.LANDESC = s.LANDESC, t.LANDMAJ = SYSDATE
WHEN NOT MATCHED THEN INSERT (LANID, LANDESC, LANDCRE, LANDMAJ, LANUTIL)
VALUES (s.LANID, s.LANDESC, SYSDATE, SYSDATE, 'admin');

COMMIT;

SET DEFINE ON;
