-- Phase 1 i18n — TRA_LABELS bulk LIBQUERY + login label bundle
-- Deploy after existing Dictionary DIC0000001-0012 (if present). Safe to run standalone.

SET DEFINE OFF;

DELETE FROM LIBQUERY WHERE QUERYNUM IN (
  'LAB0000002', 'DIC0000013', 'DIC0000014', 'DIC0000015'
);

-- LAB0000002 — All TRA_LABELS for one language (login bundle; replaces/enhances LAB0000001)
INSERT INTO LIBQUERY (QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'LAB0000002',
       'Labels - list by language',
       'All TRA_LABELS for :param1=TLALANGUE. Client builds key map at login.',
       q'~
SELECT l.TLAID, l.TLADESC, l.TLAMENU, l.TLASCREEN, l.TLALANGUE
  FROM TRA_LABELS l
 WHERE l.TLALANGUE = :param1
 ORDER BY l.TLAID
~',
       ':param1=language',
       'TLAID,TLADESC,TLAMENU,TLASCREEN,TLALANGUE',
       1, 0, 0 FROM dual;

-- DIC0000013 — Labels for one screen + language
INSERT INTO LIBQUERY (QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'DIC0000013',
       'Labels - by screen',
       ':param1=TLASCREEN or -1; :param2=TLALANGUE or -1 for all langs.',
       q'~
SELECT TLAID, TLADESC, TLAMENU, TLASCREEN, TLALANGUE, TLADCRE, TLADMAJ, TLAUTIL
  FROM TRA_LABELS
 WHERE (:param1 = '-1' OR TLASCREEN = :param1)
   AND (:param2 = '-1' OR TLALANGUE = :param2)
 ORDER BY TLASCREEN, TLAID, TLALANGUE
~',
       ':param1=screen,:param2=language',
       'TLAID,TLADESC,TLAMENU,TLASCREEN,TLALANGUE,TLADCRE,TLADMAJ,TLAUTIL',
       0, 0, 0 FROM dual;

-- DIC0000014 — Bulk MERGE TRA_LABELS (CSV import)
INSERT INTO LIBQUERY (QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'DIC0000014',
       'Labels - bulk MERGE',
       'POST :param1=REQUESTID. values[]: TLAID, TLADESC (CLOB), TLAMENU, TLASCREEN, TLALANGUE, TLAUTIL. Requires script 109 (TLADESC CLOB).',
       q'~
MERGE INTO TRA_LABELS t
USING (
  SELECT SUBSTR(TRIM(j.TLAID), 1, 15) TLAID,
         TO_CLOB(NVL(TRIM(j.TLADESC), ' ')) TLADESC,
         NVL(TO_NUMBER(j.TLAMENU), 0) TLAMENU,
         NVL(TRIM(j.TLASCREEN), ' ') TLASCREEN,
         NVL(NULLIF(TRIM(j.TLALANGUE), ''), 'us_US') TLALANGUE,
         TRIM(j.TLAUTIL) TLAUTIL
    FROM REQUEST_QUERY_BODY rb,
         JSON_TABLE(rb.REQUESTBODY, '$.values[*]'
           COLUMNS (
             TLAID     VARCHAR2(60)   PATH '$."TLAID"',
             TLADESC   VARCHAR2(4000) PATH '$."TLADESC"',
             TLAMENU   VARCHAR2(5)   PATH '$."TLAMENU"',
             TLASCREEN VARCHAR2(20)  PATH '$."TLASCREEN"',
             TLALANGUE VARCHAR2(10)  PATH '$."TLALANGUE"',
             TLAUTIL   VARCHAR2(20)  PATH '$."TLAUTIL"'
           )
         ) j
   WHERE rb.REQUESTID = :param1
     AND TRIM(j.TLAID) IS NOT NULL
) s
ON (t.TLAID = s.TLAID AND t.TLALANGUE = s.TLALANGUE)
WHEN MATCHED THEN UPDATE SET
  t.TLADESC = s.TLADESC, t.TLAMENU = s.TLAMENU, t.TLASCREEN = s.TLASCREEN,
  t.TLADMAJ = SYSDATE, t.TLAUTIL = s.TLAUTIL
WHEN NOT MATCHED THEN INSERT (
  TLAID, TLADESC, TLAMENU, TLASCREEN, TLALANGUE, TLADCRE, TLADMAJ, TLAUTIL)
VALUES (s.TLAID, s.TLADESC, s.TLAMENU, s.TLASCREEN, s.TLALANGUE, SYSDATE, SYSDATE, s.TLAUTIL)
~',
       ':param1=REQUESTID',
       '',
       0, 0, 1 FROM dual;

-- DIC0000015 — Translation coverage (missing rows vs us_US baseline)
INSERT INTO LIBQUERY (QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'DIC0000015',
       'Labels - coverage report',
       ':param1=target language (en_GB/fr_FR). Lists us_US keys missing in target lang.',
       q'~
SELECT b.TLAID, b.TLASCREEN, b.TLADESC AS BASE_DESC,
       t.TLADESC AS TARGET_DESC,
       CASE WHEN t.TLAID IS NULL THEN 0 ELSE 1 END AS HAS_TARGET
  FROM TRA_LABELS b
  LEFT JOIN TRA_LABELS t
    ON t.TLAID = b.TLAID AND t.TLALANGUE = :param1
 WHERE b.TLALANGUE = 'us_US'
 ORDER BY b.TLASCREEN, b.TLAID
~',
       ':param1=target_language',
       'TLAID,TLASCREEN,BASE_DESC,TARGET_DESC,HAS_TARGET',
       0, 0, 0 FROM dual;

COMMIT;

SET DEFINE ON;
