-- Phase 1 i18n — seed ICR_MENU_LABEL us_US from ICR_MENU_ENTRY.LABEL_TEXT
-- Deploy after 65 + 66. Idempotent MERGE.

SET DEFINE OFF;

MERGE INTO ICR_MENU_LABEL t
USING (
  SELECT m.MENU_CODE,
         'us_US' AS MLLANGUE,
         m.LABEL_TEXT,
         'admin' AS MLUTIL
    FROM ICR_MENU_ENTRY m
   WHERE m.LABEL_TEXT IS NOT NULL
) s
ON (t.MENU_CODE = s.MENU_CODE AND t.MLLANGUE = s.MLLANGUE)
WHEN MATCHED THEN UPDATE SET
  t.LABEL_TEXT = s.LABEL_TEXT, t.MLDMAJ = SYSDATE, t.MLUTIL = s.MLUTIL
WHEN NOT MATCHED THEN INSERT (MENU_CODE, MLLANGUE, LABEL_TEXT, MLDCRE, MLDMAJ, MLUTIL)
VALUES (s.MENU_CODE, s.MLLANGUE, s.LABEL_TEXT, SYSDATE, SYSDATE, s.MLUTIL);

COMMIT;

SET DEFINE ON;
