-- Phase 4 i18n — LANGUAGE display names: American, English (UK), French
-- Removes legacy en_EN row; repoints users. Deploy after 65.

SET DEFINE OFF;

MERGE INTO LANGUAGE t
USING (SELECT 'us_US' LANID, 'American' LANDESC FROM DUAL) s
ON (t.LANID = s.LANID)
WHEN MATCHED THEN UPDATE SET t.LANDESC = s.LANDESC, t.LANDMAJ = SYSDATE
WHEN NOT MATCHED THEN INSERT (LANID, LANDESC, LANDCRE, LANDMAJ, LANUTIL)
VALUES (s.LANID, s.LANDESC, SYSDATE, SYSDATE, 'admin');

MERGE INTO LANGUAGE t
USING (SELECT 'en_GB' LANID, 'English (UK)' LANDESC FROM DUAL) s
ON (t.LANID = s.LANID)
WHEN MATCHED THEN UPDATE SET t.LANDESC = s.LANDESC, t.LANDMAJ = SYSDATE
WHEN NOT MATCHED THEN INSERT (LANID, LANDESC, LANDCRE, LANDMAJ, LANUTIL)
VALUES (s.LANID, s.LANDESC, SYSDATE, SYSDATE, 'admin');

MERGE INTO LANGUAGE t
USING (SELECT 'fr_FR' LANID, 'French' LANDESC FROM DUAL) s
ON (t.LANID = s.LANID)
WHEN MATCHED THEN UPDATE SET t.LANDESC = s.LANDESC, t.LANDMAJ = SYSDATE
WHEN NOT MATCHED THEN INSERT (LANID, LANDESC, LANDCRE, LANDMAJ, LANUTIL)
VALUES (s.LANID, s.LANDESC, SYSDATE, SYSDATE, 'admin');

UPDATE USERSROOM SET USERLANG = 'en_GB', USERDMAJ = SYSDATE
 WHERE USERLANG IN ('en_EN', 'en_US', 'en_UK');

BEGIN
  DELETE FROM LANGUAGE WHERE LANID = 'en_EN';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2292 THEN RAISE; END IF; -- FK — users still on en_EN
END;
/

COMMIT;

SET DEFINE ON;
