-- =============================================================================
-- 93_spaceplanning_exclude_pos.sql
-- Syndigo — CRUD for SPACEPLANNING_EXCLUDEPOS (UPCs excluded from POS extract to Space Planning)
-- Table lives on the Heinens custom DB: SPACEPLANNING_EXCLUDEPOS@HEINENS_CUSTOM_PROD
-- Deploy LIBQUERY + menu to ICR app DB. Re-runnable (DELETE+INSERT on LIBQUERY / menu).
-- Requires DB link HEINENS_CUSTOM_PROD (same as other ICR → HNCUSTOM2 paths).
-- =============================================================================

-- ── Remote table (on link target — do not create on ICR app DB) ───────────────
-- SPACEPLANNING_EXCLUDEPOS@HEINENS_CUSTOM_PROD
--   UPC VARCHAR2(50), INFOCOMMENT VARCHAR2(2000), CREATED_ON/UPDATED_ON DATE, UPDATED_BY VARCHAR2(50)

-- ── LIBQUERY SYN0000005 – SYN0000008 (001–004 used by Syndigo / Space Planning) ─
DELETE FROM LIBQUERY WHERE QUERYNUM IN ('SYN0000005', 'SYN0000006', 'SYN0000007', 'SYN0000008');

-- SYN0000005 — List exclusions (:param1 = UPC filter or -1 for all)
INSERT INTO LIBQUERY (
    QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE
)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'SYN0000005',
       'Space Planning POS exclude — list',
       'UPCs excluded from POS extract to Space Planning (@HEINENS_CUSTOM_PROD). :param1=UPC or -1.',
       q'~
SELECT UPC, INFOCOMMENT, CREATED_ON, UPDATED_ON, UPDATED_BY
  FROM SPACEPLANNING_EXCLUDEPOS@HEINENS_CUSTOM_PROD
 WHERE (:param1 = '-1' OR UPPER(UPC) LIKE '%' || UPPER(TRIM(:param1)) || '%')
 ORDER BY UPC
~',
       ':param1=upc_filter_or_-1',
       'UPC,INFOCOMMENT,CREATED_ON,UPDATED_ON,UPDATED_BY',
       1, 0, 0
  FROM dual;

-- SYN0000006 — Get one row by UPC
INSERT INTO LIBQUERY (
    QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE
)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'SYN0000006',
       'Space Planning POS exclude — get by UPC',
       ':param1=UPC (@HEINENS_CUSTOM_PROD)',
       q'~
SELECT UPC, INFOCOMMENT, CREATED_ON, UPDATED_ON, UPDATED_BY
  FROM SPACEPLANNING_EXCLUDEPOS@HEINENS_CUSTOM_PROD
 WHERE UPC = TRIM(:param1)
~',
       ':param1=upc',
       'UPC,INFOCOMMENT,CREATED_ON,UPDATED_ON,UPDATED_BY',
       1, 0, 0
  FROM dual;

-- SYN0000007 — MERGE insert/update
INSERT INTO LIBQUERY (
    QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE
)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'SYN0000007',
       'Space Planning POS exclude — MERGE',
       'Body {values:[{UPC,INFOCOMMENT,UPDATED_BY}]}. Target @HEINENS_CUSTOM_PROD.',
       q'~
MERGE INTO SPACEPLANNING_EXCLUDEPOS@HEINENS_CUSTOM_PROD tgt
USING (
  SELECT TRIM(jt.UPC) UPC,
         jt.INFOCOMMENT,
         TRIM(jt.UPDATED_BY) UPDATED_BY
    FROM REQUEST_QUERY_BODY rb,
         JSON_TABLE(rb.REQUESTBODY, '$.values[0]' COLUMNS (
           UPC VARCHAR2(50) PATH '$."UPC"',
           INFOCOMMENT VARCHAR2(2000) PATH '$."INFOCOMMENT"',
           UPDATED_BY VARCHAR2(50) PATH '$."UPDATED_BY"'
         )) jt
   WHERE rb.REQUESTID = :param1
) src
ON (tgt.UPC = src.UPC)
WHEN MATCHED THEN UPDATE SET
  tgt.INFOCOMMENT = src.INFOCOMMENT,
  tgt.UPDATED_ON  = SYSDATE,
  tgt.UPDATED_BY  = src.UPDATED_BY
WHEN NOT MATCHED THEN INSERT (UPC, INFOCOMMENT, CREATED_ON, UPDATED_ON, UPDATED_BY)
VALUES (src.UPC, src.INFOCOMMENT, SYSDATE, SYSDATE, src.UPDATED_BY)
~',
       ':param1=REQUESTID',
       '',
       1, 0, 1
  FROM dual;

-- SYN0000008 — DELETE by UPC
INSERT INTO LIBQUERY (
    QUERYID, QUERYNUM, QUERYTITLE, QUERYDESC, QUERYSQL, QUERYPARAM, QUERYRESULT, QUERYACCESS, QUERYTYPE, QUERYUPDATE
)
SELECT (SELECT NVL(MAX(QUERYID), 0) + 1 FROM LIBQUERY),
       'SYN0000008',
       'Space Planning POS exclude — delete',
       'Body {values:[{UPC}]}. Target @HEINENS_CUSTOM_PROD.',
       q'~
DELETE FROM SPACEPLANNING_EXCLUDEPOS@HEINENS_CUSTOM_PROD
 WHERE UPC = (
   SELECT TRIM(jt.UPC)
     FROM REQUEST_QUERY_BODY rb,
          JSON_TABLE(rb.REQUESTBODY, '$.values[0]' COLUMNS (
            UPC VARCHAR2(50) PATH '$."UPC"'
          )) jt
    WHERE rb.REQUESTID = :param1
 )
~',
       ':param1=REQUESTID',
       '',
       1, 0, 1
  FROM dual;

COMMIT;

-- ── Menu catalog (incremental — safe on existing DBs) ─────────────────────────
-- Under Space Planning (GRP_SPACE), not Syndigo
MERGE INTO ICR_MENU_ENTRY tgt
USING (
  SELECT 'ROUTE_SYNDIGOEXCLUDEPOS' MENU_CODE,
         'GRP_SPACE' PARENT_CODE,
         'ROUTE' MENU_TYPE,
         'STANDARD' MENU_MODE,
         '/syndigoexcludepos' ROUTE_PATH,
         'fas fa-ban' ICON_CLASS,
         'POS exclude UPC' LABEL_TEXT,
         165 SORT_ORDER,
         NULL EXPAND_KEY,
         1 ACTIVE
    FROM dual
) src
ON (tgt.MENU_CODE = src.MENU_CODE)
WHEN MATCHED THEN UPDATE SET
  tgt.PARENT_CODE = src.PARENT_CODE,
  tgt.MENU_TYPE   = src.MENU_TYPE,
  tgt.MENU_MODE   = src.MENU_MODE,
  tgt.ROUTE_PATH  = src.ROUTE_PATH,
  tgt.ICON_CLASS  = src.ICON_CLASS,
  tgt.LABEL_TEXT  = src.LABEL_TEXT,
  tgt.SORT_ORDER  = src.SORT_ORDER,
  tgt.ACTIVE      = src.ACTIVE
WHEN NOT MATCHED THEN INSERT (
  MENU_CODE, PARENT_CODE, MENU_TYPE, MENU_MODE, ROUTE_PATH, ICON_CLASS, LABEL_TEXT, SORT_ORDER, EXPAND_KEY, ACTIVE)
VALUES (
  src.MENU_CODE, src.PARENT_CODE, src.MENU_TYPE, src.MENU_MODE, src.ROUTE_PATH, src.ICON_CLASS,
  src.LABEL_TEXT, src.SORT_ORDER, src.EXPAND_KEY, src.ACTIVE);

-- Flag rules — Space Planning team + common ICR roles (not under Syndigo menu group)
INSERT INTO ICR_MENU_ACCESS_RULE (MENU_CODE, FLAG_NAME)
SELECT 'ROUTE_SYNDIGOEXCLUDEPOS', 'SPACE'
  FROM dual
 WHERE NOT EXISTS (
   SELECT 1 FROM ICR_MENU_ACCESS_RULE r
    WHERE r.MENU_CODE = 'ROUTE_SYNDIGOEXCLUDEPOS' AND r.FLAG_NAME = 'SPACE');

INSERT INTO ICR_MENU_ACCESS_RULE (MENU_CODE, FLAG_NAME)
SELECT 'ROUTE_SYNDIGOEXCLUDEPOS', 'DATAINTEGRITY'
  FROM dual
 WHERE NOT EXISTS (
   SELECT 1 FROM ICR_MENU_ACCESS_RULE r
    WHERE r.MENU_CODE = 'ROUTE_SYNDIGOEXCLUDEPOS' AND r.FLAG_NAME = 'DATAINTEGRITY');

INSERT INTO ICR_MENU_ACCESS_RULE (MENU_CODE, FLAG_NAME)
SELECT 'ROUTE_SYNDIGOEXCLUDEPOS', 'HELPDESK'
  FROM dual
 WHERE NOT EXISTS (
   SELECT 1 FROM ICR_MENU_ACCESS_RULE r
    WHERE r.MENU_CODE = 'ROUTE_SYNDIGOEXCLUDEPOS' AND r.FLAG_NAME = 'HELPDESK');

INSERT INTO ICR_PROFILE_MENU (PROFILE_ID, MENU_CODE, GRANTED)
SELECT 6, 'ROUTE_SYNDIGOEXCLUDEPOS', 1
  FROM dual
 WHERE NOT EXISTS (
   SELECT 1 FROM ICR_PROFILE_MENU p
    WHERE p.PROFILE_ID = 6 AND p.MENU_CODE = 'ROUTE_SYNDIGOEXCLUDEPOS');

MERGE INTO ICR_MENU_LABEL t
USING (SELECT 'ROUTE_SYNDIGOEXCLUDEPOS' MENU_CODE, 'us_US' MLLANGUE, 'POS exclude UPC' LABEL_TEXT FROM dual) s
ON (t.MENU_CODE = s.MENU_CODE AND t.MLLANGUE = s.MLLANGUE)
WHEN MATCHED THEN UPDATE SET t.LABEL_TEXT = s.LABEL_TEXT
WHEN NOT MATCHED THEN INSERT (MENU_CODE, MLLANGUE, LABEL_TEXT) VALUES (s.MENU_CODE, s.MLLANGUE, s.LABEL_TEXT);

MERGE INTO ICR_MENU_LABEL t
USING (SELECT 'ROUTE_SYNDIGOEXCLUDEPOS' MENU_CODE, 'fr_FR' MLLANGUE, 'Exclusion UPC POS' LABEL_TEXT FROM dual) s
ON (t.MENU_CODE = s.MENU_CODE AND t.MLLANGUE = s.MLLANGUE)
WHEN MATCHED THEN UPDATE SET t.LABEL_TEXT = s.LABEL_TEXT
WHEN NOT MATCHED THEN INSERT (MENU_CODE, MLLANGUE, LABEL_TEXT) VALUES (s.MENU_CODE, s.MLLANGUE, s.LABEL_TEXT);

-- Remove BUYER grant if screen was first deployed under Syndigo
DELETE FROM ICR_MENU_ACCESS_RULE
 WHERE MENU_CODE = 'ROUTE_SYNDIGOEXCLUDEPOS'
   AND FLAG_NAME = 'BUYER';

COMMIT;
