-- Rename Mass-change box menu: ROUTE_POPUSH "PO push" → "Push/Breakdown order"
-- Idempotent — safe on existing DBs. Re-login after deploy for sidebar refresh.

UPDATE ICR_MENU_ENTRY
   SET LABEL_TEXT = 'Push/Breakdown order'
 WHERE MENU_CODE = 'ROUTE_POPUSH';

MERGE INTO ICR_MENU_LABEL t
USING (SELECT 'ROUTE_POPUSH' MENU_CODE, 'us_US' MLLANGUE, 'Push/Breakdown order' LABEL_TEXT FROM dual) s
ON (t.MENU_CODE = s.MENU_CODE AND t.MLLANGUE = s.MLLANGUE)
WHEN MATCHED THEN UPDATE SET t.LABEL_TEXT = s.LABEL_TEXT, t.MLDMAJ = SYSDATE, t.MLUTIL = 'admin'
WHEN NOT MATCHED THEN INSERT (MENU_CODE, MLLANGUE, LABEL_TEXT, MLDCRE, MLDMAJ, MLUTIL)
VALUES (s.MENU_CODE, s.MLLANGUE, s.LABEL_TEXT, SYSDATE, SYSDATE, 'admin');

MERGE INTO ICR_MENU_LABEL t
USING (SELECT 'ROUTE_POPUSH' MENU_CODE, 'fr_FR' MLLANGUE, 'Commande push/repartition' LABEL_TEXT FROM dual) s
ON (t.MENU_CODE = s.MENU_CODE AND t.MLLANGUE = s.MLLANGUE)
WHEN MATCHED THEN UPDATE SET t.LABEL_TEXT = s.LABEL_TEXT, t.MLDMAJ = SYSDATE, t.MLUTIL = 'admin'
WHEN NOT MATCHED THEN INSERT (MENU_CODE, MLLANGUE, LABEL_TEXT, MLDCRE, MLDMAJ, MLUTIL)
VALUES (s.MENU_CODE, s.MLLANGUE, s.LABEL_TEXT, SYSDATE, SYSDATE, 'admin');

COMMIT;
